### ISSUE TITLE
feat: run tailcall in the browser

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1011]
Thanks to @ssddOnTop we are able to compile Tailcall in WASM format. One of the next steps for us is the ability to run Tailcall in the browser. This will allow us to create a playground like that of [Typescript](https://www.typescriptlang.org/play) and [Rust](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021) where developers can write the config and the query, run everything within the same browser window, and share a link with other people! We will also be able to leverage the awesome dev tools provided by chrome to debug API calls from within the browser.

**Technical Requirements**
- Publish an npm package `@tailcallhq/tailcall-wasm` with the contents of the wasm solution with a JS shim.
- A user should be able to install tailcall via npm and load it up in the browser window to play around with it.

**Comment by thesapan** [comment]
@tusharmath can you assign this to me?

**Comment by rishi-raj-jain** [comment]
Can I be assigned this?

**Comment by ayewo** [comment]
Please assign me ✋.

**Comment by ssddOnTop** [comment]
I think it is closely related to #1038, I'll attempt both

**Comment by tusharmath** [comment]
closing in favour of #1038
