### ISSUE TITLE
feature: add a `/showcase` url

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1012]
The `/showcase` url on tailcall takes a `config` query parameter.

```
curl https://tailcall.run/showcase/graphql?config=http://abc.com/tc.graphql
```
The `config` parameter takes a link to the GraphQL file and runs a GraphQL server in that context. 

**Technical Requirements**
- Similar code is written `cloudflare/handle` remove it from there.
- Ensure unit tests are added.
- All error messages while validating should be returned as a JSON response.
- Add a feature flag in `@server(showcase: Boolean)` to configure the feature enablement.

**Comment by ssddOnTop** [comment]
may I try?

**Comment by tobihans** [comment]
Can I get assigned this ?

**Comment by ssddOnTop** [comment]
should it merge configs or keep it standalone?

**Comment by kremedev** [comment]
I would like to work on this 👀

**Comment by mogery** [comment]
I'm also interested.

**Comment by Gua00va** [comment]
would like to work on this
