### ISSUE TITLE
Create a separate folder for generated files

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1019]
Auto-generated files currently lie in `examples` directory. Move them to a special directory — `/generated`. This is done so that we don't pollute the examples directory with generated files.

**Technical Requirements**
- Generated files don't need to be parsed or validated via Lint.
- Update references to generated files in the project.

**Comment by lazyfuhrer** [comment]
are you referencing the `.tailcallrc.schema.json` should be generated at `/generated` ? @tusharmath

**Comment by tusharmath** [comment]
Yes.
