### ISSUE TITLE
feat: publish tailcall WASM build on NPM

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1038]
Publish tailcall on npm under 

- `@tailcallhq/wasm-browser`
- `@tailcallhq/wasm-node`

**Public API**

```js
import {GraphQLExecutor} from '@tailcallhq/tailcall'


// YML, JSON or GraphQL
const jsonConfig = " ... <tailcall config> ... "; 


// Use the builder to create the configuration
const builder = new TailcallBuilder().withJSONConfig(jsonConfig).withYMLConfig(ymlConfig);

// Build an instance of Tailcall, resolving configurations
const tailcall = await builder.build();


// Execute queries using the builder.
const query = "query {users {name}}"
await executor.execute({query})
```

**Technical Requirements**
- I should be able to install the package via npm
- I should be able to use the package in the browser directly
- I should be able to use the package via node.js

**Comment by aabidsofi19** [comment]
can i get assigned to this , would love to work on this issue .

**Comment by ayewo** [comment]
✋

**Comment by ssddOnTop** [comment]
Can you explain more about the package `@tailcallhq/wasm-browser`? It's confusing, according to my understanding, there should be just 1 package published i.e. `@tailcallhq/wasm-node`which can be used in browser using nodejs. Or is it like we provide a js file (maybe via cdn) which can be used in browsers like 

```html
<!doctype html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <title>hello-wasm example</title>
  </head>
  <body>
    <script type="module">
      import init, { GraphQLExecutor } from "http://lint/to/tailcall.js";
      init().then(() => {
          const config = " ... <tailcall config> ... "; // YML, JSON or GraphQL
          const executor = new GraphQLExecutor(config);
          const query = "query {users {name}}"
          
          await executor.execute({query})
      });
    </script>
  </body>
</html>
```

**Comment by gabrieldemian** [comment]
is anyone still working on this? if not, I would like to get assigned

**Comment by ologbonowiwi** [comment]
This `GraphQLExecutor` being exported, do you imagine it being a Rust source code compiled to WASM or being a JS layer that interfaces with the binary @tusharmath?

**Comment by tusharmath** [comment]
Yes.

**Comment by webbdays** [comment]
@coderabbitai

**Comment by ssddOnTop** [comment]
waiting for completion of #1153 or should I start without the builder?

**Comment by webbdays** [comment]
@tusharmath 
can we have tailcall check also in this?

**Comment by webbdays** [comment]
helpful to check if config is good in the browser.
