### ISSUE TITLE
chore: seperate IO from cloudflare request handler 

### ISSUE THREAD

**Issue by ssddOnTop** [tailcallhq/tailcall#1055]
Currently instance of IO is created while handling request hence handle request needs instance of `worker::Env` to initiate IO, with this implementation we are confined to use implementation Cloudflare*IO and can not have unit tests, so the goal is to design the function in such a way that avoids passing `worker::Env` to `cloudflare/src/handle::fetch`.

**Proposal**:
1. Either make a struct which contains implementation of required IOs which can be passed to the function
2. Or ability to pass app context to the function.

**Must avoid**:
- Must avoid IO to be re instantiated for every request as the instantiation of AppContext occurs only once

**Comment by mogery** [comment]
This should be much easier once #1015 is merged.
