### ISSUE TITLE
chore: add version control to all the rust tooling

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1099]
Currently we use `rustc`, `cargo`, `clippy` `rustfmt` and `prettier` as our tools. The setup that we have right now doesn't support maintaining a version in the repository and thus your local lint tools version could be different than what's running on CI.

**Proposal**
- Have the ability to maintain consistent versions between the CI and local machine for all the above tools.

**Comment by meskill** [comment]
As a general solution for tools managing I know about next options:
- [Development containers](https://containers.dev/implementors/spec/) - use docker containers to start dev environment. It's supported mostly by Vs Code
- [nix](https://nixos.org/manual/nix/stable/introduction) - use additional tools that will manage dependencies

The good thing about both of those that it may help with versioning of any tool required, but both requires additional tools already available on dev machine.

Also all of the tools in descriptions except the prettier actually managed by `rustup` so may suggest to use it and we have already set up toolchains for it.

One more option to consider could be [cargo-make](https://github.com/sagiegurari/cargo-make?tab=readme-ov-file#usage-installing-native-dependencies) that have some kind of version checks and installation scripts for it. We could just migrate from custom `lint.sh` script to cargo-make

**Comment by ologbonowiwi** [comment]
@meskill thanks for the suggestion!

#1156 is ready to be reviewed
