### ISSUE TITLE
Use `script` field from `ConfigSet.Extensions` instead of `Config.Server` when loading js files

### ISSUE THREAD

**Issue by ologbonowiwi** [tailcallhq/tailcall#1103]
https://github.com/tailcallhq/tailcall/blob/834b19694e0291e5f02066b34d432d2d14ace715/src/config/reader.rs#L66-L74
We're loading the script and saving it into `Config.Server.script`, instead we should use the `ConfigSet.Extensions.script`.

spec:
- `@link` should be used instead of adding a field on `@server`
- tests should be changed to comply with the new implementation
- only one script should be allowed
- tests checking multiple scripts throwing error should be added

**Comment by lazyfuhrer** [comment]
Can I take this ?  @tusharmath
