### ISSUE TITLE
Use link to load cert and key

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1121]
Currently cert and key are given as file paths and are part of `Server`. The proposal is to move this implementation from `@server` to into the newly launched `@link` operator.

```graphql
schema
  @link(type: Cert src: "abc.cert")
  @link(type: Key src: "key.cert") {
  query: Query
}
```

**Comment by rajdip-b** [comment]
Can I give it a try?

**Comment by ssddOnTop** [comment]
We should keep this issue on hold for now, we do not know about possible changes in http* server
