### ISSUE TITLE
Wrong generated output for some types in `.tailcallrc.graphql` after calling `autogen`

### ISSUE THREAD

**Issue by meskill** [tailcallhq/tailcall#1212]
`autogen` package generates wrong output types for following cases:

Based on generated output for https://github.com/tailcallhq/tailcall/pull/1211

## 1. Optional fields in input types are marked as required:

```rust
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, schemars::JsonSchema)]
pub enum Jwks {
    Remote {
        url: String,
        #[serde(default = "default::jwt::remote::max_age")]
        max_age: NonZeroU64,
    },
}
```

generated output:

```graphql
input Remote {
  maxAge: Int!
  url: String!
}
```

## 2. A wrapper for vec type outputs just name of the type without actual type

```rust
pub struct Auth(pub Vec<AuthEntry>);
```

generated output:

```graphql
directive @server(
  auth: Auth
)

#/definitions/AuthEntry
input AuthEntry {
  id: String
}
```

i.e. only internal type is generated. This should actually generate output as `auth: [AuthEntry]` in place of usage since graphql sdl doesn't support type wrappers 

## 3. Type with a mix of scalar and enum fields generates only scalar fields

```rust
pub enum AuthProvider {
    Jwt(Jwt),
    Basic(Basic),
}

pub struct AuthEntry {
    pub id: Option<String>,
    pub provider: AuthProvider,
}
```

```graphql
input AuthEntry {
  id: String
}
```

i.e. output should also contain fields `jwt` and `basic`

**Comment by tusharmath** [comment]
100$
