### ISSUE TITLE
Allow for arbitrary text documentation in the `execution_spec`

### ISSUE THREAD

**Issue by meskill** [tailcallhq/tailcall#1213]
For now `execution_spec` description for md test file is pretty strict on what could be defined inside the md file itself.

Allow for arbitrary text around code blocks and inside heading so test files remind more like [Literate programming](https://en.wikipedia.org/wiki/Literate_programming) for writing the tests. Those texts will be used as documentation and description of behaviour of the functionality that could grow to user documentation eventually

**Comment by tusharmath** [comment]
This is a great idea. For it to work, we need to separate out the annotations from actual text. 

**Proposal**

	---
	foo: bar
	baz: qux
	---
	
	
	```graphql @config
	type Foo {
	  field: A
	}
	```

This differs from before because we are not using `#` to annotate different test sections.

**Comment by AayushMohan** [comment]
@tusharmath can I work on this?

**Comment by tusharmath** [comment]
@AayushMohan Please go ahead and use `/attempt` to start working on it.

**Comment by 35C4n0r** [comment]
@tusharmath I would like to make an attempt at it.

**Comment by tusharmath** [comment]
@AayushMohan @35C4n0r anyone of you picking this up?

**Comment by 35C4n0r** [comment]
Me.
/attempt #1213
