### ISSUE TITLE
Support custom GraphQL scalars

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1214]
Inspired by https://www.npmjs.com/package/graphql-scalars we could make the server a lot more type-safe by adding custom scalars. This should include type definitions that are auto-generated and validations for each type.
Some example scalars are

- EmailAddress
- PhoneNumber
- Date
- URL

**Comment by p1kalys** [comment]
Hey @tusharmath, I would like to work on this issue, please assign it to me.

**Comment by ssddOnTop** [comment]
Add me to the queue as backup :p
