### ISSUE TITLE
bug: make proto package id seperable by `.` 

### ISSUE THREAD

**Issue by ssddOnTop** [tailcallhq/tailcall#1226]
Currently method is expected to be in form of: `<package/proto_id>.<service>.<method>`. Currently it works only if the package id is in the form of `package foo;` but if the package id is in form of, say `package foo.bar;` then it will throw an error that `Invalid method format: {}. Expected format is <package/proto_id>.<service>.<method>`.

## Challenges
1. Currently we depend upon `id` field in `link` operator. But ideally we should use package id by default.
2. Currently only `LinkType::Protobuf` is defined in which we rely upon the `id` field but with implementation of grpc server reflection, we have ability to load all proto files or load proto file based on `package id`. So in those cases we would not have any id or we might just have `package id`. 
3. We need to define when to use package id, file name or link id respectively.

## Example
let there be some valid proto file in which package id is separated by `.`
```proto
syntax = "proto3";

package package news.foo;
```

Then gql query with `@grpc` operator should look like
```graphql
type Query {
  news: NewsData! @grpc(method: "news.foo.Service.Method")
}
```  

Tailcall is unable to parse with exception `Invalid method format: news.foo.Service.Method. Expected format is <package/proto_id>.<service>.<method> [at Query.news.@grpc]` because it expects the package name to be single string without `.`, which is a faulty implementation.

**Comment by tusharmath** [comment]
I think we should not depend on `id`. I am not 100% sure if we really have strong usecase for the `id` field in `@link`. Ideally, our CLI should be able to infer this automatically.

**Comment by ssddOnTop** [comment]
Our current implementation is based on linked id, thats why I wrote this
code to try to get package id else proto name or lastly it uses link id.

However me and @meskill discussed about this and finally settled on
decision that we must use package name. If there is no package name defined
then we should throw validation error
