### ISSUE TITLE
bug: `const` with mustache returns empty

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1239]
While using `const` with template at zero level, not value is returned

**Schema**
```graphql
schema {
  query: Query
}

type Query {
  a: A @const(data: {a: {b: {c: 1}}})
}

type A {
  b: B
  b0: B @const(data: "{{value.b}}")
}

type B {
  c: Int
}
```

**Query**
```graphql
query {a {b0}}
```

**Expected**
```
{data: {b0:{c: 1}}}
```

**Actual**
```
{}
```

**Technical Requirements**
- Make a fix and write tests.
- Clean up existing tests so that it's easier to maintain and understand.
- Ensure all edge cases are covered.

**Comment by amitksingh1490** [comment]
Invalid as query is incorrect
correct query
`query {a {b0 {c}}}
