### ISSUE TITLE
feat: add some object operators to expr

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1265]
Following this discussion https://github.com/tailcallhq/tailcall/discussions/928
I think it might be worth adding a `toPairs` operator https://ramdajs.com/docs/#toPairs in expr.

Refer to #933 for more context

**Technical Requirements**
- We need at least the following expr `path` `toPairs` `values` `keys`
- Write unit tests and integration tests.

**Comment by oleksandr-shvets** [comment]
@ologbonowiwi I've added a schema for the path operator and am now working on tests and implementation (in `src/lambda/relation.rs`). 
Tests should be located in the `src/blueprint/operators/expr.rs` and `tests/execution/test-expr-relation.md` files, correct?

https://github.com/tailcallhq/tailcall/compare/main...oleksandr-shvets:tailcall:feat/add-object-operators-to-expr

**Comment by ologbonowiwi** [comment]
Is this still relevant @tusharmath?

**Comment by tusharmath** [comment]
Closing since https://github.com/tailcallhq/tailcall/issues/1609
