### ISSUE TITLE
feat: ability to configure request handler

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1271]
**Current**
We can only setup one request handler in a JS worker file. This proposal intends to break that restriction

**Proposal**

```graphql
type schema @upstream(onRequest: "onRequest") {
  # ... 
}

type Query {
  foo: Foo @http(path: "/foo", onRequest: "onRequestFoo")
  bar: Bar @http(path: "/bar", onRequest: "onRequestBar")
  baz: Bar @http(path: "/baz")
}
```

```js
function onRequest (request) {
  // 
}

function onRequestFoo (request) {
  // 
}

function onRequestBar (request) {
  // 
}

```

In the above implementation when:
1. We query `foo`, `onRequestFoo` is called with the request params.
2. We query `bar`, `onRequestBar` is called with the request params.
3. We query `baz`, `onRequest` (default handler) is called with the request params.

**Comment by Bhavyajain21** [comment]
I can work on it. Can you please assign this to me? @tusharmath

**Comment by ologbonowiwi** [comment]
@tusharmath why not add a new file instead of new functions on the single file? For large applications, it'd make it more maintainable for the users, and it follows the idea of SRP (as serverless for example, that you have one single entry point to each file implementation).
What do you think?

**Comment by ologbonowiwi** [comment]
Just as suggestions, but anyways, I'll try to implement as it is.
/attempt #1271

**Comment by tusharmath** [comment]
@ologbonowiwi We could build that into tailcall. But I would leave that up to the developer to figure out how they would like to bundle their js file. They write code in smaller files but ultimately need to expose one file that can be imported and executed.

**Comment by webbdays** [comment]
@tusharmath 
I think the user can have a logic like this in js worker.
pseudo code :
```javascript
// onRequest being a generic handler/interceptor.
function onRequest ({request}) {
     // some logic to get path
     ......
    // switch case for path
    switch(request_path) {
        case "/foo":
            return onRequestFoo(request);
            break;
        case "/bar":
            return onRequestBar(request);
            break;
        default:
            // do nothing for others like Baz, just return request back to caller.
            return {request} ;
    }
}

function onRequestFoo ({request}) {
  //
}

function onRequestBar ({request}) {
  // 
}

``` 

This is very easy to user. Making onrequest a generic handler/interceptor.
No changes required in rust code.

**What is the advantage the user gets if supposed to configure it in .graphql format?**

**Comment by webbdays** [comment]
@tusharmath
is this still in plan?

**Comment by tusharmath** [comment]
Yes.

**Comment by webbdays** [comment]
@tusharmath 
all the http requests will go through the  on_request method of RequestFilter right?
Please confirm.

**Comment by tusharmath** [comment]
Yes. The global one defined in upstream. This is happening right now also.

**Comment by webbdays** [comment]
Hi @tusharmath,
I made it work by passing the onRequest as a header in the request to reach the on_request func in RequestFilter.
Once it reach the on_request func, i remove those headers and collect values so that we can use them there.
we should make sure we pass as headers and remove them before actual request is made.
we should handle like pass as headers only when js worker file is linked so that we can remove them in on_request func and use there.
which we can handle.
is this approach ok?
Thank you.

**Comment by webbdays** [comment]
@tusharmath 
Please comment on this.

**Comment by webbdays** [comment]
Hi @tusharmath,
done with requested changes.
Please review.
Thank you.

**Comment by webbdays** [comment]
Hi @Rutik7066,
its done.
merging is blocked due to #1570
try #1570

**Comment by varshith257** [comment]
/attempt #1271

I will take up on this import feature to be implemented as quickly as possible.

**Comment by webbdays** [comment]
Hi @tusharmath,
Please process this bounty.

**Comment by webbdays** [comment]
@tusharmath 
algora sent bounty now.
I have got 2 now.
PLease look into it.
