### ISSUE TITLE
Caching bug

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcall#1279]
### Observation

When the `@cache` directive is applied to the entire `Query` type, as shown in the first configuration, it doesn't enable caching for the egress requests made by the fields within the `Query` type. Specifically, the request made to `/posts` isn't cached:

```graphql
type Query @cache(maxAge: 30000) {
  posts: [Post] @http(path: "/posts")
}
```

In contrast, applying the `@cache` directive directly to the `posts` field within the `Query` type, as demonstrated below, successfully caches the egress request to `/posts`:

```graphql
type Query {
  posts: [Post] @http(path: "/posts") @cache(maxAge: 30000)
}
```

### Expected Behavior

The expectation is that applying the `@cache` directive at the `Query` type level should enable caching for all the egress IO operations defined within the `Query` type, for the specified `maxAge`. This means that all fields under the `Query` type should have their responses cached, based on the `maxAge` value provided in the `@cache` directive at the type level.

**Comment by adelinaenache** [comment]
May I attempt this?

**Comment by adelinaenache** [comment]
@amitksingh1490 I cannot reproduce this issue. When using `@cache` on the entire `Query` type, it works as expected, writing and reading from the cache. It may be from something else from the config?
![ScreenRecording2024-03-03at10 26 05-ezgif com-video-to-gif-converter](https://github.com/tailcallhq/tailcall/assets/17872311/beb76c51-e093-4013-8e56-47a3f528ca28)

**Comment by amitksingh1490** [comment]
@adelinaenache Are you on latest master?

**Comment by adelinaenache** [comment]
@amitksingh1490 yes I am

**Comment by amitksingh1490** [comment]
please check again. There is no log for cache in current version of main
