### ISSUE TITLE
Test cases failing on Windows OS

### ISSUE THREAD

**Issue by mehulmathur16** [tailcallhq/tailcall#1280]
### Prerequisites

The following tests are failing on windows, this is probably because of different path nomenclatures on windows & mac.

<img width="617" alt="image" src="https://github.com/tailcallhq/tailcall/assets/64700961/fe8ddcf1-3c15-4f04-a625-6d88f186be4f">

- [ ] I have checked the existing issues to ensure this is not a duplicate.
- [ ] I am running the latest version of Tailcall.

### Steps to reproduce

1.
2.
3. ... (add as many steps as needed)

### Expected behavior

A description of what you expected to happen.

### Actual behavior

A description of what actually happened.

### Environment information:

- **Operating System**: (e.g., Ubuntu 20.04, macOS Big Sur, Windows 10)
- **Tailcall Version**: (e.g., v1.0.2)
- **Rust Version**: (e.g., `rustc 1.58.0`)
- **GraphQL Client/version** (e.g., `curl/8.1.2`)

### Additional context

Add any other context about the problem here, such as relevant logs, error messages, or stack traces.

### Logs

```
Paste any relevant logs here.
```

**Comment by 35C4n0r** [comment]
@tusharmath I would like to attempt it

**Comment by xbjfk** [comment]
Hey, I'd like to give this a shot.

**Comment by mehulmathur16** [comment]
@xbjfk I'm currently working on this issue.
