### ISSUE TITLE
Validate schema using linters

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1322]
Tailcall should ensure consistency in building the final GraphQL schema. This is the standard it should follow:

**Case styles**
- Field names should use `camelCase`. 
- Type names should use `PascalCase`.
- Enum names should use `PascalCase`.
- Enum values should use `ALL_CAPS`, because they are similar to constants.

There are two approaches to solve this problem:
1. When the setting is enabled, we can throw a validation error that the developer see and fix using the `@modify` operator.
2. We can automatically fix it for the user.

**Proposal**
```graphql
schema @server(lint: {field: true, type: true, enum: true, enumValue: true, autoFix: false}) {
  query: Query
}
```

**Technical Requirements**
Use the `ConfigOptimizer` API defined over here https://github.com/tailcallhq/tailcall/issues/1653

**Comment by ssddOnTop** [comment]
I'll give it a try

**Comment by webbdays** [comment]
Please let me know the place where we parse the file and get final representation of the file for all .graphql, .yml,.json files.
When the start command is executed.
Thank you.

**Comment by tusharmath** [comment]
@webbdays check the blueprint module. All the validations are done there. Create a new file called lint.rs which performs these validations.

**Comment by webbdays** [comment]
Oh OK. I didn't properly understand the project structure.

I have directly used config struct.
I think blueprint is also get info from config struct right.

Created a linter. Working fine.
Pushing code changes now. Please look at it once to find any issues.
Thank you.

**Comment by webbdays** [comment]
@ssddOnTop
Are you still working on this?

**Comment by ssddOnTop** [comment]
> @ssddOnTop Are you still working on this?

Yessir

**Comment by webbdays** [comment]
ok

**Comment by ssddOnTop** [comment]
I am dropping this off as of now

**Comment by webbdays** [comment]
@ssddOnTop 
What is your progress on this until now and what is pending?

**Comment by webbdays** [comment]
I will try to finish what i have started.
/attempt

**Comment by ssddOnTop** [comment]
> @ssddOnTop What is your progress on this until now and what are pending things to work?

Almost everything is pending.. I didn't get much time to focus on this issue. You can check #1329

**Comment by webbdays** [comment]
@varshith257 
the first part is almost done.
I am having problem with auto fixing the issues. So, i am looking at different approaches to it.
You are welcomed to build on the work i have done in the PR #1671

**Comment by webbdays** [comment]
Here is the code for different approach i am trying;
in the pr #1795

**Comment by webbdays** [comment]
There are many cases we have to handle when auto fixing.
Because, some of the things like type or the field or the enum can be used in other parts of graphql schema. which we need to correct based of lint requirements. Which we cannot predict some times.

**Comment by webbdays** [comment]
There is this tool for graphql lint checker:
https://github.com/cjoudrey/graphql-schema-linter
User can use this while developing graphql schema.
or we can compile it to web assembly and run with wasm runtime. Also giving the user the cli option to lint.
But i think this is overhead to tailcall cli.

**Comment by webbdays** [comment]
Hi, @varshith257,
seems confused with approach word.
I have already done it. showing error to the user. (except that i have warned.) we can throw validation error.
Only problem is with autofixing.

**Comment by webbdays** [comment]
@varshith257 
You can make a pr.
I am out of ideas.

**Comment by tusharmath** [comment]
Sounds good. You need a stable identifier.

**Comment by menkotoglou** [comment]
Hey @tusharmath, is this still up?

**Comment by tusharmath** [comment]
Yes. Check out the transformer modules for inspiration

**Comment by menkotoglou** [comment]
Good to know. Thank you @tusharmath, I'll give it a try next week that I'll be having more time :)

**Comment by zeul22** [comment]
/attempt #1322
I would love to try this out for learning.

**Comment by Sadaf-A** [comment]
Greetings @tusharmath, do I need to be assigned or can I start working on this?
