### ISSUE TITLE
bug: sort scalar generation

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1344]
`gen_gql_schema.rs` keeps generating different versions of `.tailcallrc.graphql` every time we run. 
The problem lies in the order of scalars definitions that's generated. Fix the order such that it's consistent between each runs. 

**Solutions**
- We could use a btreemap instead of hashmap for scalar.
- Sort the scalars alphabetically before printing.

**Comment by ssddOnTop** [comment]
isn't it covered in #1331

**Comment by tusharmath** [comment]
@ssddOnTop  This is going to be a quick fix and help us move fast.

**Comment by tusharmath** [comment]
fixed in https://github.com/tailcallhq/tailcall/pull/1346
