### ISSUE TITLE
fix `KeyValue` directive definition

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1359]
`.tailcallrc.graphql` has the wrong definition for `KeyValues`. For eg:

Update the `gen_gql_schema.rs` so that it generates the correct .graphql and .json schema files.

**Current**
```graphql
directive @http(headers: KeyValues)
scalar KeyValues
```

**Expected**
```graphql
directive @http(headers: [KeyValue])

input KeyValue {
  key: String
  value: String
}
```

**Comment by 35C4n0r** [comment]
I would like to work on this
