### ISSUE TITLE
chore: install protobuf-compiler

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1360]
`protobuf-compiler` needs to be installed for all build steps and platforms. Currently main is broken because protobuf compiler isn't installed on all platforms.

**Expectations**
- Builds should pass on all platforms.
- Use https://github.com/marketplace/actions/setup-protoc instead of manually installing
- Reduce duplication as much as possible in ci.yml

**Comment by webbdays** [comment]
@neo773
Are you still working on this.
I am done with changes.
Can i proceed?

**Comment by neo773** [comment]
@webbdays 
Yes, but haven't made a PR yet

**Comment by webbdays** [comment]
Ok. proceed.

**Comment by webbdays** [comment]
Change seems straight forward.
isn't
may be i am wrong.
Does this take much time?

**Comment by webbdays** [comment]
@neo773 
can i proceed to open pr?

**Comment by tusharmath** [comment]
This has been fixed.
