### ISSUE TITLE
ci: add all builds tag

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1375]
On addition of `ci: build all` label, ci should build the PR on all supported platforms.

**Technical Requirements**
- Reuse the matrix defined here: https://github.com/tailcallhq/tailcall/blob/main/.github/workflows/ci.yml#L181
- Use `labels.json` to create the new `ci: build matrix` label

**Comment by 35C4n0r** [comment]
I would like to work on this, kindly assign

**Comment by tusharmath** [comment]
Taking an alternative approach of running tests on all PRs going forward https://github.com/tailcallhq/tailcall/issues/1427
