### ISSUE TITLE
support method enum in `@rest` directive

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1377]
`rest.rs` is created from the `@rest` directive, however currently the method right now is defined as a string (check this https://github.com/tailcallhq/tailcall/blob/main/tests/execution/rest-api.md?plain=1#L6)

**Proposal**
Instead of specifying the method as a string, we should leverage the existing Method enum (check this https://github.com/tailcallhq/tailcall/blob/main/generated/.tailcallrc.graphql#L674)

**Comment by tusharmath** [comment]
@ssddOnTop You already have 3 active attempts.

**Comment by ssddOnTop** [comment]
> @ssddOnTop You already have 3 active attempts.

cancelled #1321 and I think I was not the 1st to attempt #1375 so I'll pull off

**Comment by murtaza030** [comment]
#/attempt 1377

**Comment by tusharmath** [comment]
fixed in https://github.com/tailcallhq/tailcall/pull/1379
