### ISSUE TITLE
Headers passed via playground are not being passed.

### ISSUE THREAD

**Issue by shridhar52war** [tailcallhq/tailcall#1384]
### Prerequisites

- [x] I have checked the existing issues to ensure this is not a duplicate.
- [x] I am running the latest version of Tailcall.

### Describe the bug

The headers passed via graphql-playground are not being propagated in the `onRequest` method.

### Steps to reproduce

1. Specify required headers(keys) in the `allowedHeaders` option of the @upstream directive.
2. Execute the operation via playground by adding the required HTTP headers. 
3. Monitor the log within the `onRequest` method.

### Expected behavior

The headers passed via play ground should have propagated to `onRequest` method.

### Actual behavior

The headers passed via playground are not being logged in the `onRequest` method.

### Environment information:

- **Operating System**: macOS Monterey
- **Tailcall Version**: 0.0.48
- **Rust Version**: 
- **GraphQL Client/version** 

![Screenshot 2024-03-11 at 1 46 05 PM](https://github.com/tailcallhq/tailcall/assets/56016210/cebefe6d-8b7c-4e4e-8845-4770f9fffaed)
![Screenshot 2024-03-11 at 1 46 13 PM](https://github.com/tailcallhq/tailcall/assets/56016210/49b6637d-2c90-40bd-8095-d4f82ad7786b)

**Comment by tusharmath** [comment]
```graphql
schema
  @server(graphiql: true)
  @upstream(baseURL: "http://jsonplaceholder.typicode.com")
  @link(type: Script, src: "scripts/echo.js") {
  query: Query
}

type Query {
  posts: [Post] @http(path: "/posts")
}


type Post {
  id: Int!
  userId: Int!
  title: String!
  body: String!
}
```

```js
function onRequest({request}) {
  console.log(request)
  return {request}
}
```

Here is the minimal reproduction configuration.

Making this request from the IDE with the following headers:

```json
{
  "foo":"bar"
}
```



**Actual**
Here are the actual logs produced from `console.log`
```js
{"url":"http://jsonplaceholder.typicode.com/posts","method":"GET"}
```

**Expected**
{"url":"http://jsonplaceholder.typicode.com/posts","method":"GET", "headers": {"foo", "bar"}}
