### ISSUE TITLE
add support for set-cookie header

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1397]
Update `request_context.rs` to hold all `set-cookie` `header` when enabled, and send them in the final response.

```graphql
schema @server(headers: {setCookie: true}) {
  query: Query
}
```

The final response of the API should send combine all the `set-cookie` headers and add it to the final response.

Update the documentation for **server** here: https://tailcall.run/docs/operators/server

**Comment by ssddOnTop** [comment]
I am cancelling my attempt..

**Comment by tusharmath** [comment]
This is quite a simple change @ssddOnTop ru sure you want to cancel?

**Comment by ssddOnTop** [comment]
> This is quite a simple change @ssddOnTop ru sure you want to cancel?

Ill give it a try in some time

**Comment by mobley-trent** [comment]
Is it okay if I work on this @tusharmath @ssddOnTop ?

**Comment by ssddOnTop** [comment]
@mobley-trent sorry for late response. I was occupied with some other stuff..
