### ISSUE TITLE
move `server.responseHeaders` to `server.headers.custom`

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1400]
Currently response headers add additional headers to the final response. Move this setting from `@server` to `@server.headers.custom`.

**Current**

```graphql
schema @server(responseHeaders: [{key: "X-Allowed-Roles", value: "admin,user"}]) {
  query: Query
  mutation: Mutation
}
```
**Proposed**
```graphql
schema @server(headers: {custom: [{key: "X-Allowed-Roles", value: "admin,user"}]}) {
  query: Query
  mutation: Mutation
}
```

**NOTE:** Update the documentation here https://tailcall.run/docs/operators/server/#responseheaders

**Comment by tusharmath** [comment]
@neo773 Are you still on this?

**Comment by neo773** [comment]
@tusharmath 
no
