### ISSUE TITLE
chore: add tests for JsRequest

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1410]
The following tests are needed for `JsRequest`

**Unit Tests**
- Add unit tests for `impl From<&reqwest::Url> for Uri` with 100% coverage
- Add unit tests for `impl Display for Uri` with 100% coverage

**Integration Tests**
Write these in `.md` format in `tests/execution`.
- Make sure the JSRequest is correctly sent to JS.
- Make sure the JSRequest is correctly sent back from JS to Rust.

**Comment by tusharmath** [comment]
Work can start by taking a pull from https://github.com/tailcallhq/tailcall/pull/1409

**Comment by ssddOnTop** [comment]
> Work can start by taking a pull from #1409

I am taking over.. discussed with @thesapan

**Comment by ssddOnTop** [comment]
@lazyfuhrer hey I was working on it.. had been busy with some other work

**Comment by lazyfuhrer** [comment]
Apologies. I saw it was inactive for some days so I chose it up @ssddOnTop
