### ISSUE TITLE
add support for experimental headers

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1413]
Update `request_context.rs` to hold all `x-*` headers, and send them in the final response.

```graphql
schema @server(headers: {experimental: "x-csrf-token"}) {
  query: Query
}
```

The final response of the API should send the `x-csrf-token` headers.

Update the documentation for **server** here: https://tailcall.run/docs/operators/server

**Comment by onyedikachi-david** [comment]
@tusharmath please assign to me. Thanks.

**Comment by ologbonowiwi** [comment]
I'll give this a shot as I closed a few headers-related tickets recently /attempt #1413

**Comment by ologbonowiwi** [comment]
@tusharmath I think the spec to this could be
```graphql
schema @server(headers: {experimental: ["x-csrf-token"]}) {
  query: Query
}
```

instead of the original proposed on the issue. In this way, users could add multiple `x-something` headers. it does make sense?

**Comment by tusharmath** [comment]
Yes, I made a typo there.
