### ISSUE TITLE
refactor: drop `check_identity` from ExecutionSpec

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1414]
CheckIdentity should be enabled for all specifications, we don't need this configuration in ExecutionSpec.

**Comment by 35C4n0r** [comment]
I would like to try it.

**Comment by 35C4n0r** [comment]
@tusharmath tests fail on removing it from the execution_spec.rs and the .md files.

```
SUPER_IMPOPRTANAT_IDENTITY: 
schema @server @upstream {
  query: Query
}

type Query @addField(name: "username", path: ["users", "0", "name"]) {
  users: [User] @http(baseURL: "http://jsonplaceholder.typicode.com", path: "/users")
}

type User {
  name: String
}
```
```
SUPER_IMPOPRTANAT_CONTENT: 
schema {
  query: Query
}

type User {
  name: String
}

type Query @addField(name: "username", path: ["users", "0", "name"]) {
  users: [User] @http(path: "/users", baseURL: "http://jsonplaceholder.typicode.com")
}
```

```
Diff < left / right > :
<schema {
>schema @server @upstream {
   query: Query
 }
 
<type User {
<  name: String
>type Query @addField(name: "username", path: ["users", "0", "name"]) {
>  users: [User] @http(baseURL: "http://jsonplaceholder.typicode.com", path: "/users")
 }
 
<type Query @addField(name: "username", path: ["users", "0", "name"]) {
<  users: [User] @http(path: "/users", baseURL: "http://jsonplaceholder.typicode.com")
>type User {
>  name: String
 }
```

**Comment by tusharmath** [comment]
How many of such tests fail? Ideally they shouldn't fail.

**Comment by 35C4n0r** [comment]
@tusharmath around 77 tests fails

**Comment by 35C4n0r** [comment]
@tusharmath the tests fail, in all of them (graphql and json server) there are either changes in the order of the parameters, methods or type declarations + schema --> schema @server @upstream, ig this is becuse these tests were not written with identity check in mind, should I try to create a script which fixes the test mds

**Comment by ssddOnTop** [comment]
@35C4n0r are you still on it?

**Comment by 35C4n0r** [comment]
@ssddOnTop Sure, feel free to use the code here https://github.com/tailcallhq/tailcall/pull/1643/commits/e2e3e370993b9493f99f063a0922b04e812c012d#diff-e47f835532ae836901521cecc2e77863f98286e977c1920b9ca545a9d4291aa0
There was one issue that was Empty directives still remained on `types`, maybe I'm doing something wrong.
I'll cancel my attempt.

**Comment by ssddOnTop** [comment]
closing my PR for now, will be doing after #2026
