### ISSUE TITLE
Create `MergeRight` trait

### ISSUE THREAD

**Issue by ologbonowiwi** [tailcallhq/tailcall#1421]
**Is your feature request related to a problem? Please describe.**
We have an issue in the code where we usually need to wrap types (e.g.: `pub struct KeyValues(Vec<KeyValue>)`), so then we can specify specific behaviors to them.
While working on #1400, we noticed this brings unnecessary code complexity as we can't implement external types (as where implementing `merge_right` for `Vec<KeyValue>`).

**Describe the solution you'd like**

Our solution to this is refactoring the codebase so `merge_right` implementations are implementing it using a common `MergeRight` trait.
Some benefits we can get from this refactor:
- The possibility of implementing `merge_right` for external types
- Less code to maintain (we'll be able to remove lots of types gymnastics we do to merge types – these should be possible AFTER this issue is close, will be an upcoming ticket)
- Concise documentation (type wrappers will not hide the actual types, instead)

**Describe alternatives you've considered**
- Use wrapper types
- Don't use the types at all; use methods called `merge_something`.

**Additional context**
I'm willing to work on it.

**Comment by tusharmath** [comment]
Proposed trait structure

```rust
trait MergeRight {
  fn merge_right(self, other) -> Self;
}

impl<A: MergeRight> MergeRight for Option<A> {
  fn merge_right(self, other) -> Option<A> {
     // ...
  }
}

```

**Comment by ologbonowiwi** [comment]
Hey @ssddOnTop, appreciate it if you let this one on me. I have some code locally for it already

**Comment by ssddOnTop** [comment]
@ologbonowiwi just did all code :/
