### ISSUE TITLE
fix: docker CI

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcall#1433]
In the docker file install latest version of tailcall globally using curl as mentioned here https://tailcall.run/docs/getting_started/#curl

Currently docker file is starting the server drop that.
 
Fix the CI to have versioning, right now version is set as main
Check the details of published versions here. Latest is still pointing to v0.18.0
https://github.com/tailcallhq/tailcall/pkgs/container/tailcall%2Ftc-server

**Comment by harshbisle** [comment]
Can I get this assigned to me, please?

**Comment by neo773** [comment]
@harshbisle 
Hi, I'm already working on this and making a PR

**Comment by harshbisle** [comment]
Ohh! alright @neo773 good luck!
