### ISSUE TITLE
ability to add multiple IOs in a config

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1475]
Currently `config::Field` can support only one resolver at a time. These resolvers can either be a GRPC, HTTP GraphQL or a Const. This proposal intends to change it by providing a vector of IO operations that can be piped into one another.

**Change in `config.rs`:**
```diff
  pub struct Field {            
      pub args: BTreeMap<String, Arg>,            
      pub cache: Option<Cache>,
      pub doc: Option<String>,            
      pub expr: Option<Expr>,        
      pub graphql: Option<GraphQL>,            
      pub list_type_required: bool,            
      pub list: bool,            
      pub modify: Option<Modify>,            
      pub omit: Option<Omit>,            
      pub required: bool,            
      pub script: Option<JS>,            
      pub type_of: String,            
-     pub call: Option<Call>,            
-     pub const_field: Option<Const>,            
-     pub grpc: Option<Grpc>,            
-     pub http: Option<Http>,            
+     pub resolver: Vec<Resolver>,
  }

+ pub enum Resolver {
+   Call(Call),
+   Const(Const),
+   Grpc(Grpc),
+   Http(Http),
+ }
```

**Change in Blueprint**
- The structure for blueprint remains the same with each resolver compiling into an Expression. However incase of multiple resolvers the expressions should be composed with each other using the `and_then` operation on Expression.

**Change in `from_document.rs`**
The following is a totally valid configuration:
```graphql
type Query {
  abc: ABC 
    @http(path: "/abc")  # assuming it returns {a: {b: {c: "abc"}}}
    @const(data: "{{value.a}}") 
    @const(data: "{{value.b}}") 
    @const(data: "{{value.c}}")
}
```
The `value` which is accessible via context contains the output of the previous resolver. This is already implemented by `and_then`

**Technical Requirements**
- Make sure there are enough integration tests.

**Comment by tusharmath** [comment]
Will hold on to this for a bit. There is an alternative way to do the same thing.

**Comment by ssddOnTop** [comment]
We are working on alternate method. Closing the issue
