### ISSUE TITLE
Call should take a sequence of `Call` instead of just one

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1482]
Currently, each call field can only support one call. Change that to support a sequence of calls.

**Before**
```graphql
type Foo {
  bar: Bar @call(query: "bar")
}
```

**After**
```graphql
type Foo {
  bar: Bar @call(steps: [{query: "bar"}, {query: "baz"}])
}
```

These steps are composed together using the `and_then`.

**Comment by lazyfuhrer** [comment]
Are u working on this @ssddOnTop ?

**Comment by ssddOnTop** [comment]
@lazyfuhrer yes sir

**Comment by lazyfuhrer** [comment]
> @lazyfuhrer yes sir

Okay go ahead. Let's not make multiple PRs
