### ISSUE TITLE
refactor execution spec

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1500]
Execution spec is getting out of control. Let's refactor! 

**Requirements**
- Create a mod for execution_spec
- Mod should have a `parse.rs` which parses the md files and creates ExecutionSpec
- `spec.rs` that actually creates and executes the spec.
- create a `runtime.rs` that contains all the mock runtime.
- Use https://crates.io/crates/datatest to generate tests via spec.rs.
- Rename `@assert` to `@test` everywhere in the spec.

**Comment by ssddOnTop** [comment]
huh

**Comment by 35C4n0r** [comment]
Then I would like to take a shot at it.

**Comment by webbdays** [comment]
i will be in queue.

**Comment by 35C4n0r** [comment]
@webbdays @ssddOnTop, I've cancelled my attempt, feel free to attempt it.

**Comment by webbdays** [comment]
Ok.
@35C4n0r 
/attempt 1500

**Comment by ssddOnTop** [comment]
I’ll attempt in case @webbdays pulls out

**Comment by webbdays** [comment]
Hi @tusharmath,
Any example how we use insta snapshots assertion and this datatest library together.
Thanks.

**Comment by webbdays** [comment]
Hi @tusharmath,
Actually, insta is good and sufficient for test assertions right.
What is the reason for using the datatest here.

**Comment by tusharmath** [comment]
@webbdays We will use insta for the assertions you are right. But instead of writing everything in one test, we will test each file separately as a real test

**Comment by webbdays** [comment]
Hi @tusharmath,
Please look into this:
https://github.com/commure/datatest?tab=readme-ov-file#notes-on-rust-channel

**Comment by tusharmath** [comment]
Thanks @webbdays   is there an alternative that you can suggest?

**Comment by webbdays** [comment]
we can look at insta::glob!(...)

**Comment by webbdays** [comment]
@tusharmath 
using datatest-stable which a  file based test runner from nextest-rs
https://github.com/nextest-rs/datatest-stable

**Comment by webbdays** [comment]
that project didnt have much popularity but its was developed by github organisation which is also maintaining Nextest.

**Comment by webbdays** [comment]
Rename @assert to @test everywhere in the spec - still it is pending thing. will do.

**Comment by webbdays** [comment]
done

**Comment by webbdays** [comment]
Rename https://github.com/Assert to @test - this was done as said.
