### ISSUE TITLE
Format runtime errors using CLIError

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1508]
Currently the errors aren't formatted using `CLIError` and look poorly formated on the console. Below is an example of a 404 error.
```
ERROR error=HTTP status client error (404 Not Found)
ERROR error=IOException: HTTP status client error (404 Not Found)
ERROR err=Error { message: "IOException: HTTP status client error (404 Not Found)", extensions: None }
```

**Expected**
Error should look something like below.
```
ERROR Http Error
Caused by:
  - HTTP status client error (404 Not Found)
```

**NOTE**
Error should not be printed 3 times.

**Comment by ssddOnTop** [comment]
@neo773 cancelling my attempt

**Comment by neo773** [comment]
This is open to anyone who wants to attempt
