### ISSUE TITLE
refactor: re-write `gen_gql_schema.rs` 

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1510]
Current implementation takes a schemars and directly writes a .graphql file. The expectation is to create a `async_graphql::ServiceDocument` and then leverage the `crate::document::print` to print it.

**Expectations**
- Rewrite the module to create a `ServiceDocument` and use `document::print` to print it.
- Drop all the `write!` calls from `gen_gql_schema.rs`
- Split the large file into smaller logical files that's easy to understand.
- Write documentation for different files and modules created.
- Make sure the final generated file doesn't change.

**Comment by tusharmath** [comment]
@harshbisle Go for it.

**Comment by harshbisle** [comment]
> @harshbisle Go for it.

On it!

**Comment by ologbonowiwi** [comment]
@tusharmath, we have a limitation, though: our `From<Config> for ServiceDocument` accounts only for filled fields.

I see two ways we can go for this:
1. Write a new version accounting for the empty fields to generate the `.graphql` based on the `ServiceDocument`
2. Fill all the fields so we have the filled version and can easily run `.to_sdl()`

2. It looks the worst to me as every new field would require changing the mock, sort of what we do today (when adding directives). Let me know if 1. makes sense or if you have any other ideas to accomplish this.

**Comment by VasuDevrani** [comment]
No one assigned. Can i work on it?

**Comment by nickelulz** [comment]
@harshbisle I'm interested in this project and I see that it hasn't been completed yet. Let me know if you're open to collaboration. Otherwise, as there's nobody assigned to this, I'd like to just get started. Thanks

**Comment by Subh231004** [comment]
Is this resolved ?

**Comment by 0xa48rx394r83e9** [comment]
I am interested in doing this. Please confirm whether this is still up for grabs or not (given it has been 3 months this issue was opened and a month since a PR was created)
