### ISSUE TITLE
Validation Error on invalid configurations

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1517]
Tailcall CLI doesn't bail out configurations with additional fields in recognized directives. For eg:

```graphql
type Query {
  foo: Foo @http(url: "/users")
}
```
As per the [docs](https://tailcall.run/docs/operators/http/) there is no recognized field called `url` however tailcall will never give an errors when it happens. The expectation is that Tailcall should bail out with an error stating that a field in unrecognized.

**Additional Information**
This feature should be possible to implement via [deny_unknown_fields](https://serde.rs/container-attrs.html#deny_unknown_fields)

**Technical Requirements**
- The validation should cover all directives.
- Add integration tests like https://github.com/tailcallhq/tailcall/tree/main/tests/execution

**Comment by 35C4n0r** [comment]
@tusharmath, this looks good ?
![image](https://github.com/tailcallhq/tailcall/assets/70096901/d1124e73-a678-4f17-8bef-3645187a23b9)
