### ISSUE TITLE
bug(bug): Sandbox loaded files in execution spec

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1570]
Currently when we use the `@file:abc.js` annotation in a file like `foo.md`, and try to access it in `bar.md` we succeed. The expected behaviour is that all files defined in `foo.md` should be local to that file and sandboxed for that tests defined in `foo.md`. Those file should never be accessible from `bar.md`  or any other file.

**Comment by Ameer-officials** [comment]
Implement access control system , you could enforce a rule that files included via [@file ] annotations can only be accessed from the same directory.
Ensure that the runtime environment enforces these access restrictions.

**Comment by webbdays** [comment]
we can access in any other files?

**Comment by webbdays** [comment]
There are two options:
1. define separate new scope other than global every time for each script.
2. clear global scope everytime.

**Comment by webbdays** [comment]
dropping.

**Comment by webbdays** [comment]
it needs knowledge on v8

**Comment by tusharmath** [comment]
Anyone working on this?

**Comment by tusharmath** [comment]
Feel free to create a thread on discord to discuss or get clarifications.
