### ISSUE TITLE
refactor: Create a Resource Reader

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1618]
Create a module `resource_reader.rs` that reads a file from local or absolute paths or an HTTP URL. This implementation currently resides in the `config::reader` module. Refactor it and take it out into the root module. The `FileRead` type which is defined in the `config::reader` should also be moved out into `resource_reader.rs`.

**Technical Requirements**
- Ensure the tests are migrated from config::reader

**Comment by webbdays** [comment]
I will try it for the next 1hr.

**Comment by tusharmath** [comment]
Awesome @webbdays!

**Comment by ssddOnTop** [comment]
I'll attempt in case @webbdays drops

**Comment by webbdays** [comment]
there is no direct use of read_file and read_files in tests.
So, no need to move any tests i guess.

**Comment by webbdays** [comment]
@tusharmath Please review
Thank you.
