### ISSUE TITLE
bug(config): input types loose out on provided graphQL documentation

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1625]
Documentation isn't copied into the blueprint for input types from configurations. For eg:

```graphql
"""
Some Documentation
"""
input Foo {
  id: Int!
}
```

While using a configuration with an input type like the above, documentation isn't copied in the final schema. 

**Technical Requirements**
- Copy the documentation into the blueprint
- Ensure integration tests are added

**Comment by ssddOnTop** [comment]
cancelling my attempt.. I am busy with some other work to do.

For anyone who wants to attempt:
in `from_document.rs`

convert:
```rust
TypeKind::InputObject(input_object_type) => {
                to_input_object(input_object_type, &type_definition.node.directives).some()
}
```
to
```
TypeKind::InputObject(input_object_type) => {
                to_input_object(input_object_type, &type_definition.node.description, &type_definition.node.directives)
}
```

and the new function should look like:

```rust
fn to_input_object(
    input_object_type: InputObjectType,
    description: &Option<Positioned<String>>,
    directives: &[Positioned<ConstDirective>],
) -> Valid<config::Type, String> {
    to_input_object_fields(&input_object_type.fields)
        .fuse(Protected::from_directives(directives.iter()))
        .map(|(fields, protected)| {
            let doc = description.to_owned().map(|pos| pos.node);
            config::Type { fields, protected, doc, ..Default::default() }
        })
}
```

now you just need to make sure it's passed to blueprint and write the tests as described in issue.

**Comment by sn99** [comment]
@tusharmath I made the PR based on the suggestions above: https://github.com/tailcallhq/tailcall/issues/1625#issuecomment-2031426868.
