### ISSUE TITLE
bug(grpc): Enums with aliases don't work in GRPC

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1626]
**Proto File**
```proto
syntax = "proto3";

package greetings;

service Greeter {
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}

message HelloRequest {
  string name = 1;
}

message HelloReply {
  string message = 1;
  repeated OBJECT_TYPE objects = 2;
}

enum OBJECT_TYPE {
  option allow_alias   = true;
  ONE = 0;
  TWO = 1;
  O_NE = 0;
  T_WO = 1;
}
```

**Configuration**
```graphql
schema
  @server(port: 8000, graphiql: true)
  @upstream(baseURL: "...", httpCache: true, batch: {delay: 10})
  @link(src: "./enums.proto", type: Protobuf) {
  query: Query
}

type Query {
  hello(name: JSON): HelloReply!
    @grpc(
      method: "greetings.Greeter.SayHello"
      body: "{{args.name}}"
    )
}

type HelloReply {
  message: String
  objects: [ObjectType]!
}

enum ObjectType {
  ONE
  TWO
}
```

**Actual**
```
ERROR Invalid Configuration
Caused by:
  • expected Enum type [at Query.hello.@grpc.HelloReply.objects]
```

**Expected**
Should start the server without errors and successfully query the GRPC endpoint.

**Comment by b4s36t4** [comment]
@tusharmath I have doubt, in the grpc schema we have `4` values inside enum but in the graphql we have only two values which is causing this issue, you want to run the server even there is a mismatch between grpc and graphql? 

How you want this to be handled?

**Comment by ssddOnTop** [comment]
kickstart:

`from_proto_file` function in protobuf.rs converts descriptor to all `fields` and `messages` and it does not preserve options in EnumDescriptorProto.

Along with EnumDescriptorProto, there can be options in: `DescriptorProto`, `FieldDescriptorProto`, `EnumValueDescriptorProto` and `FileDescriptorProto`. So I think we should have some flow that either separately handles options or some kind of map which can be used directly with ProtobufService

**Comment by webbdays** [comment]
Hi @tusharmath,

I guess the issue resolve with maintaining enum values order.
By default, if number is not given, we take defined order.
And then compare.
Raised a pull request.
Please review.
Thank you.

**Comment by webbdays** [comment]
@tusharmath 
the enums
ONE, TWO

here:
enum ObjectType {
  ONE
  TWO
}

should be one of 
the enums 
ONE, TWO, O_NE, T_WO

here
enum OBJECT_TYPE {
  option allow_alias   = true;
  ONE = 0;
  TWO = 1;
  O_NE = 0;
  T_WO = 1;
}

right?

**Comment by webbdays** [comment]
i mean subset.

**Comment by webbdays** [comment]
graphql defined enums should be subset of that defined in proto files?

**Comment by tusharmath** [comment]
In a way, basically all unique variants of the enum should be supported for.

**Comment by ssddOnTop** [comment]
> graphql defined enums should be subset of the enums defined in proto files?

if any only if `allow_alias` is set to true. If it's set to true then all fields of enum in tailcall config must be subset of proto, else it must be equivalent to enum in proto.

**Comment by webbdays** [comment]
ok.
what i am saying is
subset handles both cases
A is subset to A which is equivalent case.
we dont need to check for allow_alias here.

it was being handled in code:
i have tried this
```proto

syntax = "proto3";

package greetings;

service Greeter {
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}

message HelloRequest {
  string name = 1;
}

message HelloReply {
  string message = 1;
  repeated OBJECT_TYPE objects = 2;
}

enum OBJECT_TYPE {
  ONE = 0;
  TWO = 1;
  O_NE = 0;
  T_WO = 1;
}

```

then tailcall currently raises Invalid configuration error:

```
ERROR Invalid Configuration
Caused by:
  • enum number '0' has already been used [at Query.hello.@grpc]
```

**Comment by webbdays** [comment]
if we set allow_alias option to false and the aliases are there for enum variants
then it also throws error.

so what we left to handle is handle if it is graphql is subset of proto.

**Comment by webbdays** [comment]
```proto
syntax = "proto3";

package greetings;

service Greeter {
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}

message HelloRequest {
  string name = 1;
}

message HelloReply {
  string message = 1;
  repeated OBJECT_TYPE objects = 2;
}

enum OBJECT_TYPE {
  option allow_alias = false;
  ONE = 0;
  TWO = 1;
  O_NE = 0;
  T_WO = 1;
}
```

error:
```

ERROR Invalid Configuration
Caused by:
  • enum number '0' has already been used [at Query.hello.@grpc]
```

**Comment by webbdays** [comment]
```proto
syntax = "proto3";

package greetings;

service Greeter {
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}

message HelloRequest {
  string name = 1;
}

message HelloReply {
  string message = 1;
  repeated OBJECT_TYPE objects = 2;
}

enum OBJECT_TYPE {
  option allow_alias = true;
  ONE = 0;
  TWO = 1;
  O_NE = 0;
  T_WO = 1;
}
```
Error:
```

ERROR Invalid Configuration
Caused by:
  • expected {"ONE", "TWO", "four"} but found {"ONE", "O_NE", "TWO", "T_WO"} [at Query.hello.@grpc.HelloReply.objects]
```
