### ISSUE TITLE
bug(grpc): generation from proto

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1653]
Generation from proto currently doesn't differentiate between input and output types. We need to have separate types for input and output. 

**Proposal**

```rust
// src/optimizer/lib.rs

trait ConfigOptimizer {
  fn modify(&self, config: Config) -> Config
}


// src/optimizer/diff_input_output.rs
enum Strategy {
  Prefix,
  Suffix
}

struct DiffInputOutput {text: String, strategy: Strategy}


impl ConfigOptimizer for DiffInputOutput {
 // ...
}
```

This implementation will find all the types that are of used in args (inputs), and create a new type with the provided suffix or prefix and update all the usage of those types in the configuration. 

Call optimizers to optimize the generated configuration via GRPC

**Update**
This architecture should be extended for https://github.com/tailcallhq/tailcall/issues/1322

**Comment by ssddOnTop** [comment]
Cancelling my attempt for now

It's open for all

**Comment by atamakahere-git** [comment]
Trying to /attempt 
Might drop if it takes longer for me to start with.

**Comment by shanretoo** [comment]
@tusharmath @ssddOnTop Hi, is this still open?

**Comment by tusharmath** [comment]
@ssddOnTop can you link the pr and close this issue.

**Comment by meskill** [comment]
fixed by https://github.com/tailcallhq/tailcall/pull/1718
