### ISSUE TITLE
bug:  Error message on Authentication Faliure

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcall#1665]
The error message for not Providing Header and Invalid(random string) Header is giving the same error like given below

```
{
  "data": null,
  "errors": [
    {
      "message": "Authentication Failure: Parameters not provided in the request.",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ]
    }
  ]
}
```

Expected behaviour: 
1. Header not provided
Authentication Failure: Missing Authorization Header
2. Invalid Value Provided
Authentication Failure: Invalid Authorization Header

**Comment by webbdays** [comment]
Can i know, which feature or component this relates to in codebase.

**Comment by webbdays** [comment]
is this:
https://github.com/tailcallhq/tailcall/blob/5770bb5e8b752e917ecc3fddcd03e38c598017d0/src/auth/jwt/jwt_verify.rs#L41
https://github.com/tailcallhq/tailcall/blob/5770bb5e8b752e917ecc3fddcd03e38c598017d0/src/auth/jwt/jwt_verify.rs#L70

**Comment by amitksingh1490** [comment]
I think If we provide link both the verification Basic and jwt and provide a basic auth token, jwt is giving Error.Missing. Ideally it should give the error from basic auth.
Also errors can be fixed in 
errors.rs file inside Auth folder

**Comment by amitksingh1490** [comment]
problem seems to be there in `basic.rs`
```rust
async fn verify(&self, req_ctx: &RequestContext) -> Verification {
    let header = req_ctx.allowed_headers.typed_get::<Authorization<Basic>>();
    println!("{:?}", header);
    let Some(header) = header else {
        return Verification::fail(Error::Missing);
    };

    if self.verifier.check(header.username(), header.password()) {
        Verification::succeed()
    } else {
        Verification::fail(Error::Invalid)
    }
}
```
Header is coming as None even If its invalid

**Comment by webbdays** [comment]
@amitksingh1490 
seems you are testing the query on browser via graphiql UI.
in that case we wont be sending authorisation token along with request.
So you are getting headers None.

**Comment by webbdays** [comment]
I have tested with
token
Getting header fine.
printed:
Header: Some(Authorization(Basic { decoded: "testuser1:$apr1$e3dp9qh2$fFIfHU9bilvVZBl8TxKzL/", colon_pos: 9 }))

**Comment by webbdays** [comment]
we can pass http headers via ui as well.

**Comment by webbdays** [comment]
When i try to change the length of header to expect invalid token message.
But it says no parameters passed.
Headers now is None printed.

**Comment by amitksingh1490** [comment]
i am passing the header from graphiql ui, but sending a random value. which is invalid still getting none

**Comment by webbdays** [comment]
Ha.

**Comment by webbdays** [comment]
.typed_get::<Authorization<Basic>>()
this to get value the token its seems the token need to be some specific way.
otherwise it is returning None.

**Comment by amitksingh1490** [comment]
<img width="1728" alt="image" src="https://github.com/tailcallhq/tailcall/assets/23661702/c186fcc5-9e9c-437d-a548-f7fcf326fb1c">

Incorrect Header
```
{
  "Authorization": "Basic dGVzdHVzZXIyOm15cGFzc3dvcmQ"
}
```

<img width="1724" alt="image" src="https://github.com/tailcallhq/tailcall/assets/23661702/6e8b502a-520d-4632-9cf0-e37b134d1f4d">

correct Header

```
{
  "Authorization": "Basic dGVzdHVzZXIyOm15cGFzc3dvcmQ="
}
```
No header
<img width="1728" alt="image" src="https://github.com/tailcallhq/tailcall/assets/23661702/75781002-e514-45e0-ac79-f00db4fb1801">

**Comment by ssddOnTop** [comment]
oh sorry I didn't see @mehulmathur16 have their PR open.. 

I can close my pr if there's are any objections

**Comment by webbdays** [comment]
And here is mine:
```rust
let Some(header) = header else {
    if !req_ctx.allowed_headers.contains_key("Authorization") {
        return Verification::fail(Error::Missing);
    };
    return Verification::fail(Error::Invalid);
};
```

**Comment by webbdays** [comment]
Currently the error Missing  seems to be for missing parameters.
Its better to have error enums to be more specific like Error::MissingHeader
