### ISSUE TITLE
bug(grpc): proto files are not found

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1686]
While running from the CLI to generate a tailcall configuration the paths of the proto dependencies aren't correctly resolved, often resulting in errors as files aren't found. 

**Technical Requirements**
Current, implementation is hand written, we should use leverage Protox's file resolution capabilities to do this.

https://docs.rs/protox/0.6.0/protox/file/index.html

**Comment by ssddOnTop** [comment]
originally we were using protox crate but we dropped it (in #1041) for WASM support because it uses `std::fs`.

**Comment by amitksingh1490** [comment]
Fixed in https://github.com/tailcallhq/tailcall/pull/1705
