### ISSUE TITLE
feature: Use QuickJS instead of V8

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1690]
Migrate from the current JS implementation to use QuickJS. 

**Technical Requirements**
- Use https://docs.rs/rquickjs/latest/rquickjs/
- Ensure all existing tests pass
- Perform a benchmark to compare differences in performance

**Additional Details**
- Here are the existing benchmarks https://bellard.org/quickjs/bench.html

**Comment by webbdays** [comment]
/attempt
I will try.

**Comment by webbdays** [comment]
@abhishek818 
I will try first, if no pr from me by tomorrow.
it is up for grabs.

**Comment by ologbonowiwi** [comment]
On the queue. As my main focus is Node, it'd be very fun to work on this :smile:

**Comment by webbdays** [comment]
@abhishek818 
@ologbonowiwi 
i am dropping.

**Comment by webbdays** [comment]
this might be helpful.
https://github.com/DelSkayn/rquickjs/issues/97

**Comment by ologbonowiwi** [comment]
@tusharmath, why not use a node-compatible runtime?

Having non-V8-based/backward compatibility can bring issues for users, as everyone is already used to V8 and knows how it works.

If we move forward in getting something non-V8 compatible, we need extensive examples/docs from the users. If I were using JS with tailcall and suddenly my stuff stopped working because of a different runtime, I'd think deeply about dropping from tailcall.

**Comment by webbdays** [comment]
as the doc says
http filter feature is for only simple
https://tailcall.run/docs/guides/http-filters/https://tailcall.run/docs/guides/http-filters/
Any example for diff where it breaks?

**Comment by ologbonowiwi** [comment]
I don't have any examples @webbdays, nor I'm sure it'll break 😅

Only adding this concern to the discussion 🚀

**Comment by tusharmath** [comment]
> @tusharmath, why not use a node-compatible runtime?

Node is an independent runtime, nothing is truly node compatible, not even deno or bunjs. Tailcall doesn't need to be a full-fledged JS runtime because JS is just used to write light weight logic to modify requests and responses. 

>Having non-V8-based/backward compatibility can bring issues for users, as everyone is already used to V8 and knows how it works.

V8 and QuickJS might not be all that different. Here is the feature comparison https://test262.fyi/#|v8,qjs

>If we move forward in getting something non-V8 compatible, we need extensive examples/docs from the users. If I were using JS with tailcall and suddenly my stuff stopped working because of a different runtime, I'd think deeply about dropping from tailcall.

I don't think users even know if they are on v8 or not. QuickJS has a reasonable coverage of features, so I don't things will just stop working.

Also checkout what AWS is doing in their LLRT https://github.com/awslabs/llrt/blob/main/Cargo.toml#L21
