### ISSUE TITLE
Add `Pos` to `Config`

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1698]
Currently `Config` type doesn't hold any position information in its fields. This makes it extremely difficult to debug and attach meaningful traces. In this issue, we want to insert tracing information in the config. That way we could see better errors:

**Current**
```bash
❯ tailcall check ./examples/jsonplaceholder.graphql
 INFO Env file: "/Users/tushar/Documents/Projects/tailcall/.env" loaded
 INFO File read: ./examples/jsonplaceholder.graphql ... ok
 WARN A new release of tailcall is available: v0.74.1 ➜ v0.74.12
 WARN To upgrade, run: brew upgrade tailcall
 WARN https://github.com/tailcallhq/tailcall/releases/tag/v0.74.12
ERROR Invalid Configuration
Caused by:
  • No base URL defined [at Post.user.@call.@http]
  • No base URL defined [at Query.posts.@http]
  • No base URL defined [at Query.user.@http]
  • No base URL defined [at Query.users.@http]
```

**Expected**
```bash
❯ tailcall check ./examples/jsonplaceholder.graphql
 INFO Env file: "/Users/tushar/Documents/Projects/tailcall/.env" loaded
 INFO File read: ./examples/jsonplaceholder.graphql ... ok
 WARN A new release of tailcall is available: v0.74.1 ➜ v0.74.12
 WARN To upgrade, run: brew upgrade tailcall
 WARN https://github.com/tailcallhq/tailcall/releases/tag/v0.74.12
ERROR Invalid Configuration
Caused by:
  • No base URL defined [at ./examples/jsonplaceholder.graphql#8:17]
```

Going forward we would be able to extract a piece of text from the source file and display it on the CLI with swiggly lines under it.

**Technical Requirements**
- Add a new type called `Pos` for each field in `Config`. This field is essentially transparent to the serializer/deserializer
  
  
  ```rust
  struct Pos<A> {
    line: u64,
    offset: u64,
    value: A
  }
  ```
- Implement `merge_right` on `Pos` in such a way that position information is correctly merged. Ensure information is stored in Pos from wherever the data is read from.

**Comment by timburrows** [comment]
I'm still looking into this but I haven't determined a good way to maintain Pos data on each of the fields without a lot of otherwise unused members on each struct. I was considering that if the only use case was for tracing, keeping a key value pair might suffice?
