### ISSUE TITLE
bug: make tailcall build offline

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1722]
Currently when you try to build Tailcall without internet it throws up the following error

```
error: failed to run custom build command for `async-graphql-extension-apollo-tracing v3.2.14 (https://github.com/tailcallhq/async_graphql_apollo_studio_extension/#b7537c56)`

Caused by:
  process didn't exit successfully: `/Users/tushar/Documents/Projects/tailcall/target/debug/build/async-graphql-extension-apollo-tracing-072eed78a261821c/build-script-build` (exit status: 1)
  --- stderr
  Error: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("usage-reporting.api.apollographql.com")), port: None, path: "/proto/reports.proto", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("dns error", Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })) }

```

**Comment by tusharmath** [comment]
@abhishek818 Is this the only way we can fix the issue? The idea was that a developer should be able to build Tailcall CLI locally without depending on the internet once all the dependencies are installed. Vendoring the dependencies like this seems like a bit of maintenance overhead for us.

**Comment by abhishek818** [comment]
@tusharmath  Alternatives seems to be mirroring crates/deps using [panamax](https://github.com/panamax-rs/panamax) and romt. 
Found few stackoverflow answers recommending `cargo vendor` for offline builds and starred repos using vendor.
I went with vendoring only git revision deps.
