### ISSUE TITLE
Duplicated CLI output related to read files

### ISSUE THREAD

**Issue by meskill** [tailcallhq/tailcall#1734]
### Prerequisites

- [x] I have checked the existing issues to ensure this is not a duplicate.
- [x] I am running the latest version of Tailcall.

### Describe the bug

When running `examples/grpc.graphql` example that has `@link` operator the read proto files are showed twice i.e.

```sh
[wsl] nixos in ❯ cargo run -- start examples/grpc.graphql
   Compiling tailcall v0.1.0 (/home/nixos/Projects/tailcall/tailcall)
    Finished dev [unoptimized + debuginfo] target(s) in 30.76s
     Running `target/debug/tailcall start examples/grpc.graphql`
 INFO File read: examples/grpc.graphql ... ok
 INFO File read: examples/../src/grpc/tests/proto/news.proto ... ok
 INFO File read: examples/../src/grpc/tests/proto/news.proto ... ok
 INFO N + 1 detected: 0
 INFO 🚀 Tailcall launched at [127.0.0.1:8000] over HTTP/1.1
 INFO 🌍 Playground: http://127.0.0.1:8000
 ```
 
 for file /src/grpc/tests/proto/news.proto

### Expected behavior

Output logs should show every file only once

### Actual behavior

Read files (at least related to protobuf) are showed twice for each file

### Additional context

Make sure it doesn't replicate for different types of link

**Comment by tusharmath** [comment]
This is happening because we are reading the file multiple times.
