### ISSUE TITLE
fix: drop `unwrap` from `from_proto`

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1739]
`from_proto` contains a few `unwrap`. Remove them and use `Valid` type here. Make sure to use `Valid::from_iter` for when one needs to check iterables.

**Comment by timburrows** [comment]
In the queue

**Comment by VasuDevrani** [comment]
is it still valid or fixed?

**Comment by Shylock-Hg** [comment]
@tusharmath Currently, there is only one `unwrap` called in `from_proto.rs:138`, and I think it will never panic because the container is not empty. Should we still remove it?
