### ISSUE TITLE
feat: make tailcall "GraphQL over HTTP" compliant

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1766]
Currently, tailcall doesn't support [GraphQL over HTTP Spec](https://graphql.org/learn/serving-over-http/)

**Technical Requirements**
- All existing tests should pass
- Add new tests for every compliance violation
- Ensure there is no performance degradation

**Additional Information**
Use https://graphql-http.com to check for spec compliance.

**Related Issues**
- For the `/graphql` route refer to https://github.com/tailcallhq/tailcall/issues/1790

Use the following configuration for testing.

```graphql
schema
  @server(
    port: 8000
    graphiql: true
    hostname: "0.0.0.0"
    headers: {cors: {allowOrigins: ["*"], allowHeaders: ["*"], allowMethods: [POST, GET, OPTIONS]}}
  )
  @upstream(baseURL: "http://jsonplaceholder.typicode.com") {
  query: Query
}

type Query {
  posts: [Post] @http(path: "/posts")
}

type Post {
  id: Int!
  userId: Int!
  title: String!
  body: String!
}

```

**Comment by tusharmath** [comment]
@syedbarimanjan Fixed it, thanks!

**Comment by syedbarimanjan** [comment]
/attempt #1766 @tusharmath can you assign me the issue

**Comment by webbdays** [comment]
I would like to follow this https://graphql.github.io/graphql-over-http/draft/ .
And work on one by one compliance requirement.

**Comment by webbdays** [comment]
there are previous releases?
https://spec.graphql.org/October2021/
Should we use this?

**Comment by ologbonowiwi** [comment]
I'd love to work on this. Putting myself on the queue 🤚🏽

**Comment by tusharmath** [comment]
> Hi @tusharmath,
> 
> But that specification is still in draft.
> Any other specification to follow?

It's going to be in the draft state for a while I think. Supporting it however will become a necessity very soon because most tooling will start depending on it. 

I think the best way to start is to pick items based on the severity of the issues.

**Comment by ologbonowiwi** [comment]
@tusharmath, our playground is currently `/graphql`; should we change it to `/graphiql` so that `/graphql` is used as described in the spec?

**Comment by tusharmath** [comment]
> @tusharmath, our playground is currently `/graphql`; should we change it to `/graphiql` so that `/graphql` is used as described in the spec?

We can use https://tailcall.run/playground/ instead of the current self hosted one.

**Comment by webbdays** [comment]
sorry, i am confused.

**Comment by ologbonowiwi** [comment]
Ok, now no one else is on the queue I'll /attempt.

**Comment by webbdays** [comment]
i am in.
Currently working on the Accept header spec requirement.
You can working parallel on other spec requirements.

**Comment by webbdays** [comment]
@ologbonowiwi

**Comment by ologbonowiwi** [comment]
Oh, sorry, @webbdays; as for the comment from the Algora bot, I thought you had dropped your attempt.

I plan to start from GET/POST on the `/graphql` route.

**Comment by webbdays** [comment]
ok.
POST is must
GET is optional
according to spec.

**Comment by webbdays** [comment]
in spec
5.2 and 5.2.1 contradicts, isn't it?

**Comment by webbdays** [comment]
@ologbonowiwi 
let me know which section you are currently plan to work on?

**Comment by ologbonowiwi** [comment]
Yeah, sure. For now, my only focus is to change the routing, so at least we can check against the app on https://graphql-http.com/

**Comment by webbdays** [comment]
> I think the best way to start is to pick items based on the severity of the issues

Can you mention those.

**Comment by tusharmath** [comment]
> > I think the best way to start is to pick items based on the severity of the issues
> @tusharmath 
> Can you mention those here as a priority list.

Check out the report generated.

**Comment by ssddOnTop** [comment]
/attempt #1766

(there are some problems with async-graphql, will fix those first)

**Comment by karatakis** [comment]
I made this [pull request](https://github.com/async-graphql/async-graphql/pull/1569) to async_graphql to dictate that the extensions property is optional according to GraphQL over HTTP spec file. 

https://github.com/async-graphql/async-graphql/pull/1569

**Comment by ssddOnTop** [comment]
@karatakis I am already working on this at #https://github.com/tailcallhq/tailcall/pull/2480

**Comment by karatakis** [comment]
They are similar, but different approach. Lets double our chances :smile:. @ssddOnTop lets hope any of them gets accepted. Then we will be a closer step to the compliance thing.

**Comment by ssddOnTop** [comment]
🤷
