### ISSUE TITLE
feat: update mustache syntax

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1767]
**Current**
```mustache
{a.b.c}
```

**Proposed**
```mustache
{.a.b.c}
```
There is an additional `.` in the beginning.

**Technical Requirements**
- Add unit tests.
- Ensure both, the current and the new one are working. 
- Update website documentation wherever mustache templates are used. 

ENSURE THE OLDER VERSION CONTINUES TO WORK AS IT IS

**Comment by hazyone** [comment]
btw, it will be useful if this syntax will support arrays. I haven't found info, that it has array support
