### ISSUE TITLE
feat: migrate playground

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1790]
1. Drop the `GET /graphql` route.
1. On start open `https://tailcall.run/playground/?u={{http://localhost:PORT}}` instead of the `/graphql` route.

**Comment by webbdays** [comment]
But this requires internet connection to simply test.

**Comment by tusharmath** [comment]
@webbdays Yeah, I think that's ok. We can provide a much better experience this way to our users.
