### ISSUE TITLE
bug: When specifying remote url in config cli tries to read file from FS

### ISSUE THREAD

**Issue by meskill** [tailcallhq/tailcall#1793]
### Prerequisites

- [x] I have checked the existing issues to ensure this is not a duplicate.
- [x] I am running the latest version of Tailcall.

### Describe the bug

Instead of path to local file try to specify remote url of this file in config. In that case check command with fail with error

```
Failed to read file: https://raw.githubusercontent.com/tailcallhq/tailcall/main/tailcall-fixtures/fixtures/protobuf/news.proto: No such file or directory (os error 2)
```

### Steps to reproduce

In `examples/grpc.graphql` specify link to proto file as url:

```
@link(id: "news", src: "https://raw.githubusercontent.com/tailcallhq/tailcall/main/tailcall-fixtures/fixtures/protobuf/news.proto", type: Protobuf)
```

And run `check` command with this config

### Expected behavior

File content should be loaded from remote.

### Actual behavior

CLI tries to resolve url as relative path and read the file from local FS instead

### Additional context

- [ ] config reader should first check that src is url instead of trying to resolve is as fs path
- [ ] add execution_spec test for it

**Comment by ranjitmahadik** [comment]
@meskill provided src isn't valid (giving 404 error), can help with the valid src?
