### ISSUE TITLE
Drop responseValidation in `@server`

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcall#1813]
We are currently performing explicit validation of responses within our GraphQL executor based on `responseValidation` setting in `@server` directive . However, this might be redundant as GraphQL inherently includes capabilities for validating values against the schema.

**Proposed Changes**
- [ ] Remove all code segments explicitly dedicated to response validation in the GraphQL executor.
- [ ] Refactor any affected tests.
- [ ] Update relevant documentation.

**Comment by ranjitmahadik** [comment]
@amitksingh1490 
current implementation don't validate the response with schema based on types (if we remove the responseValidation flag).
so in order to provide the option of type validation we have to support responseValidation setting in @server directive.
