### ISSUE TITLE
fix: Enable JS build for all architecture

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcall#1869]
**Issue Description:**

We recently migrated from `V8` to `QuickJS` for our `JavaScript` runtime. We initially utilized feature flags for disabling the build of `JS `features for architectures where V8 was incompatible.

Now, we aim to enable `JS` feature across all architectures. 

> Note: While this may potentially encounter issues on certain architectures, we should iteratively enable it for those where it works.

The expectation is to update the CI to build Tailcall on all supported platforms without any feature flags. 

**Additional Context:**

- Unsupported platforms
	- [ ] linux-x64-musl
	- [ ] linux-arm64-musl
	- [ ] linux-ia32-gnu
	- [ ] win32-x64-gnu
	- [ ] win32-arm64-msvc
	- [ ] win32-ia32-gnu

- How it works on CI
	https://github.com/tailcallhq/tailcall/blob/dd2114deb7c939d44798b945f8491b1801678125/.github/workflows/ci.yml#L266

**Comment by tusharmath** [comment]
/bounty 180$

**IMPORTANT:** The bounty is priced at 30$ per platform. So in case only two platforms are supported we will pay only 60$.

**Comment by tusharmath** [comment]
@varshith257 @mehulmathur16 The builds are failing on main. Which is not allowing us to make any releases. Can you please check this out URGENTLY.

https://github.com/tailcallhq/tailcall/actions/runs/9092466656/job/24989725401
https://github.com/tailcallhq/tailcall/actions/runs/9092466656/job/24989725711

**Comment by mehulmathur16** [comment]
> @varshith257 @mehulmathur16 The builds are failing on the main, which is not allowing us to make any releases. Can you please check this out URGENTLY?
> 
> https://github.com/tailcallhq/tailcall/actions/runs/9092466656/job/24989725401
> https://github.com/tailcallhq/tailcall/actions/runs/9092466656/job/24989725711
> 

@tusharmath on it

**Comment by varshith257** [comment]
> @varshith257 @mehulmathur16 The builds are failing on the main, which is not allowing us to make any releases. Can you please check this out URGENTLY?
> 
> https://github.com/tailcallhq/tailcall/actions/runs/9092466656/job/24989725401 https://github.com/tailcallhq/tailcall/actions/runs/9092466656/job/24989725711

Taking a look on it

**Comment by varshith257** [comment]
@tusharmath Got the solution for it. Can you provide suggestion on how to test the behaviour of release workflow with changes?

Is it run when packages updates?

**Comment by varshith257** [comment]
> @varshith257 @mehulmathur16 The builds are failing on the main, which is not allowing us to make any releases. Can you please check this out URGENTLY?
> 
> https://github.com/tailcallhq/tailcall/actions/runs/9092466656/job/24989725401
> https://github.com/tailcallhq/tailcall/actions/runs/9092466656/job/24989725711
> 

@tusharmath  Can re-run the workflows in above mentioned links? I think it's reverted pr got merged but I suscept feature flag  doesn't causing of release build fails. But let's check-in
