### ISSUE TITLE
Unclear error message for using ` batchkey` without enabling batching

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcall#2029]
The error message for enabling batching in upstream is not very clear if someone specifies the batchKey in the `@http` but forgets to enable batching in the `@upstream` directive.
## Steps to Reproduce
Use this config and start the server
```graphql
schema
@server(port: 8000)
@upstream(baseURL: "http://jsonplaceholder.typicode.com", httpCache: 42) {
  query: Query
}

type Query {
  posts: [Post] @http(path: "/posts")
}

type User {
  id: Int!
  name: String!
  username: String!
  email: String!
  phone: String
  website: String
}

type Post {
  id: Int!
  userId: Int!
  title: String!
  body: String!
  user: User @http(path: "/users", query: [{key: "id", value: "{{.value.userId}}"}], batchKey: ["id"])
}

```
## Actual
```bash 
 INFO File read: ./examples/jsonplaceholder_batch.graphql ... ok
 INFO N + 1 detected: 0
ERROR Invalid Configuration
Caused by:
  • GroupBy can only be applied if batching is enabled [at Post.user.@http]
```
## Expected
```bash 
 INFO File read: ./examples/jsonplaceholder_batch.graphql ... ok
 INFO N + 1 detected: 0
ERROR Invalid Configuration
Caused by:
  • "batchKey" can only be applied if batching is enabled in upstream [at Post.user.@http]
```

**Comment by bnchi** [comment]
@amitksingh1490 just wondering is it a simple text change here https://github.com/tailcallhq/tailcall/blob/e6d8e3885537213f749ca8edac288ef10b165afe/src/core/blueprint/operators/http.rs#L20 or is there a specific conditions that needs to be met for this to get triggered ?

**Comment by amitksingh1490** [comment]
Just a text change now that you pointed out the code, there is another message
 Valid::<(), String>::fail("GroupBy is only supported for GET requests".to_string())
 Where we have wrong message here also
