### ISSUE TITLE
Compile time check for preventing use of optional fields in Http

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcall#205]
**Description:**
The current compiler does not catch potential issues when a field that can be undefined or optional is used in the route parameter of Http. To enhance robustness and provide clearer developer feedback, the compiler should be improved in the following areas:

1. **Potentially Undefined Route Parameter:**
   When a field that can be undefined or optional is used in the route parameter of Http, the code should not compile to prevent potential runtime issues.

   **Examples:**
   ```graphql
   type Query {
      user(id: Int): User @http(path: "/user/{{args.id}}")
   }
   ```

   In this first example, since `id` is an optional parameter, using it directly in the route should trigger a compiler error.

   ```graphql
   type Post {
      id: ID
      userId: ID
      user: User @http(path: "/users/{{value.userId}}")
   }
   ```

   In the second example, the `userId` field is not guaranteed to always be present in a `Post`. Using it in the `path` should also raise a compiler error, as it can lead to unexpected behavior or failures.

2. **Undefined References:**
   The compiler should be enhanced to detect any values, fields, arguments, etc. that are used but not defined, and raise appropriate errors.

**Comment by ap172x** [comment]
@amitksingh1490 @tusharmath Can you help point me into the right direction?

**Comment by tusharmath** [comment]
I think you can start by looking at `blueprint::from_config.rs` That's the place where we convert the configuration into a blueprint. We need to write the following checks — 
- Get all the http directives
- Identify all the paths that are using mustache templates
- Go to the path of each template in config and make sure they are of required type.
