### ISSUE TITLE
bug: fix overflow issue in get_all_used_type_names in case of cyclic type.

### ISSUE THREAD

**Issue by laststylebender14** [tailcallhq/tailcall#2106]
### Bug:
when unused_types method of config is called with config having cyclic types, it goes into infinite loop.

```rust
let unused_types = config.unused_types();
```

### Expected:
`config.unused_types`  shouldn't go into infinite loop, should take cyclic types into account while calculating the unused types.

**Comment by bnchi** [comment]
In the PR I added a single unit test let me know if you think there are other cases where this might fail.
