### ISSUE TITLE
feat: Support Alias Mapping for Enum Values in GraphQL

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcall#2127]
### Description:
We need to extend the current functionality of the GraphQL `enum` type to support alias mappings for enum values. example, for the `enum Foo`, we want to map the value `A` to the aliases "Alpha" and "Ace". 

This feature will allow for more flexibility in handling enum values, particularly when integrating with external systems that may use different representations for the same logical value. The value should be parsed and the aliases should be correctly mapped to their respective enum values.

The config should look like this:

```graphql
enum Foo {
  A @alias(options: ["Alpha", "Ace"])
  B
}
```

In above example, the enum value `A` should be recognized for `A`, `Alpha`, and `Ace`.

### Acceptance Criteria:
1. Support for specifying aliases for enum values in the config.
2. Aliases should be correctly recognized and mapped to the corresponding enum values.
3. Add integration tests for this use case.
4. Update the documentation on the website

**Comment by tusharmath** [comment]
You will need to update the IR logic for this I think. A generic map of source to target values.
