### ISSUE TITLE
feat: tailcall init should be interactive

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#2195]
Tailcall init needs to be more interactive, here is the proposed design.

```
> tailcall init my-new-project
  ? File Format:
    - GraphQL
    - JSON
    - YML
  [INFO] File write: ./my-new-project/.tailcallrc.schema.json
  [INFO] File write: ./my-new-project/.tailcallrc.graphql
  [INFO] File write: ./my-new-project/.graphqlrc.yml
  [INFO] File write: ./my-new-project/main.graphql  
```

**Technical Requirements**

- Logs will be generated automatically if the runtime from CLI is used.
- Err if the user doesn't set a path to the init command.
- Create the directory recursively if it doesn't exit
- Create the files in the newly generated directory.
- By default create a file called `main` with the extension selected above.
- Create a simple Hello World config inside of the main.
  ```graphql
  schema {
    query: Query
  }
  type Query {
    greet: String @const(body: "Hello World!")
  }
  ```

**Comment by amitksingh1490** [comment]
It should also generate a base configuration file for a "Hello, World!" GraphQL server, similar to how cargo init creates a new project.

**Comment by varshith257** [comment]
@amitksingh1490 Almost everything is done. While generating user-selected file, do we need to create empty files or existing files   - .tailcallrc.graphql - .tailcallrc.schema.json  - .graphqlrc.yml in our project?

**Comment by webbdays** [comment]
@varshith257 
let tailcallrc = include_str!("../../generated/.tailcallrc.graphql");
let tailcallrc_json: &str = include_str!("../../generated/.tailcallrc.schema.json");

**Comment by webbdays** [comment]
comes from source code.
