### ISSUE TITLE
Write a transformer to create better type names for configurations using LLM

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#2200]
Currently autogenerated configurations can sometimes have not-so-readable type names. We want to use LLMs to produce more meaningful type-names

**Before**

```graphql
type T1 {
  name: String
  age: Int
  gender: Gender
}

type T2 {
  name: String
  address: Address
  reviews: [Review]
}
```

**After**
A simple instruction like below to chat gpt can produce a more meaningful configuration

>Generate better names for T1 and T2 and produce a new schema file with the new names.

```graphql
type Person {
  name: String
  age: Int
  gender: Gender
}

type Business {
  name: String
  address: Address
  reviews: [Review]
}
```

**Technical Requirements**
- It should work with very large configurations.
- It should ensure there are no conflicts.
- No information should be lost, such as comments, directives etc.
- Should be able to plug any LLM API

**Additional Information**
- Transformers are written over here: 	https://github.com/tailcallhq/tailcall/blob/main/src/core/config/transformer/improve_type_names.rs
- Start Locally by using Ollama: https://ollama.com/
- Use APIs documented here https://github.com/ollama/ollama/blob/main/docs/api.md

**Proposed Solution**
- Update `improve_type_names` transformer to also take in additional "hints" for each type name. 
- The hints are going to be in the form of:
	```rust
	type OriginalName: String; // Like T1
	type AIGeneratedName: String; // Like Business or Person
	HashMap<OriginalName, Vec<AIGeneratedName>>
	```
- At the time of name resolution or a name conflict, if a name hint is provided that name is going to be preferred over its own name resolution algorithm.

**Sample Prompt for OLLAMA**

```json
{
  "model": "llama3",
  "system": "Given the GraphQL type definition below, provide a response in the form of a JSONP callback. The function should be named \"callback\" and should return JSON suggesting at least five suitable alternative names for the type. Each suggested name should be concise, preferably a single word, and capture the essence of the data it represents based on the roles and relationships implied by the field names. \n\n```graphql\ntype T {\n  name: String,\n  age: Int,\n  website: String\n}\n```\n\n**Expected JSONP Format:**\n\n```javascript\ncallback({\n  \"originalTypeName\": \"T\",\n  \"suggestedTypeNames\": [\"Person\",\"Profile\",\"Member\",\"Individual\",\"Contact\"\n  ]\n});\n```",
  "prompt": "type T {title: String, body: String, userId: Int}"
}
```

**Comment by bnchi** [comment]
Canceling my attempt the model isn't as reliable and it's slow with generating responses, developing this require more time waiting for responses and making sure that the model is always responding with the correct format specially with large configs. 

If anyone want to build on my closed PR feel free.

**Comment by karatakis** [comment]
@tusharmath Can we use services that already host llama for quick development, for example:
- https://openrouter.ai
- https://www.lepton.ai/playground/chat/llama3-70b

The only drawback of those services is that they use the OpenAPI ChatGPT API format. But you can use the API with other services or local hosted versions in the future.

**Comment by tusharmath** [comment]
Yes. We could.
