### ISSUE TITLE
Issue: Tests Getting Stuck for Hours Without Timing Out

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcall#2205]
There are certain tests in our test suite that get stuck for hours, and ideally, they should timeout. We need a mechanism to set a timeout for each test to prevent this from happening. By default, the timeout should be set to 60 seconds for all the tests If not specified.

**Comment by webbdays** [comment]
i will pick this, this evening.

**Comment by alankritdabral** [comment]
Is this bounty still open @amitksingh1490 ? If it is can you share an example of thes test getting stuck?

**Comment by rogueloop** [comment]
I could not reproduce the issue after running `cargo test`. All test passed.
