### ISSUE TITLE
`@graphql` does not forward unknown directives to upstream GraphQL servers

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcall#2242]
Currently, when using the @graphql directive, directives included in the query are not forwarded to upstream GraphQL servers. This behavior can lead to issues when upstream servers have custom resolvers designed to interpret specific directives, such as @cascade as detailed in the [Dgraph documentation](https://dgraph.io/docs/graphql/queries/cascade/).

### Expected:
The `@graphql` handler should forward directives that `Tailcall` does not recognize to the upstream server. This allows the use of server-specific directives and ensures that custom resolvers on the server can function correctly.

**Comment by meskill** [comment]
Blocked by https://github.com/async-graphql/async-graphql/issues/1547

**Comment by amitksingh1490** [comment]
@meskill https://github.com/async-graphql/async-graphql/issues/1547 this is merged

**Comment by meskill** [comment]
> @meskill [async-graphql/async-graphql#1547](https://github.com/async-graphql/async-graphql/issues/1547) this is merged

pr is updated
