### ISSUE TITLE
refactor: Drop `pub` from all the fields of ConfigModule

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#2256]
**Technical Requirements**
- Derive getters to get access by reference to the internal fields.
- There is only one setter usage for ConfigModule that can be changed to use `config_module::Extension` which has pub fields.

**Comment by bnchi** [comment]
@tusharmath for config field it probably can't be done without doing some cloning for the entire configuration at this line here https://github.com/tailcallhq/tailcall/blob/main/src/core/config/reader.rs#L142

We reconstruct config in config_module and if we would to remove pub and get a reference we can't do that without having to _clone_ config field to get an owned value. If you think this is an acceptable compromise let me know

**Comment by Rutik7066** [comment]
@be-hunter  I was working on it. You should ask before raising PR
