### ISSUE TITLE
bug: Tailcall with deduplication doesn't respond after making multiple concurrent requests

### ISSUE THREAD

**Issue by beelchester** [tailcallhq/tailcall#2276]
### Prerequisites

- [x] I have checked the existing issues to ensure this is not a duplicate.
- [x] I am running the latest version of Tailcall.

### Describe the bug
On `dedupe:true`, If I make multiple concurrent n+1 query requests It doesn't respond.

### Steps to reproduce

1. Open codespace on https://github.com/tailcallhq/graphql-benchmarks
2. use `dedupe: true` in `graphql/tailcall/benchmark.graphql`
3. run the `./run.sh` script or `tailcall start benchmark.graphql` (for better logs)
4. In `wrk/wrk.lua` change `wrk.body` to `'{"operationName":null,"variables":{},"query":"{posts{id,userId,title,user{id,name,email}}}"}'
`
5. run `./wrk/bench.sh`.

### Expected behavior

Tailcall should respond and the benchmarks should work all the time.

### Actual behavior

On the first run of `./wrk/bench.sh` it might work correctly but try running it 2-3 more times. It doesn't respond and the benchmark shows all 0

### Screenshots

https://github.com/tailcallhq/tailcall/assets/73148455/7905b2de-45f0-419e-ad58-ef873ae772c3

### Environment information:

- **Operating System**: Github codespace
- **Tailcall Version**: 0.92.6
- **Rust Version**: rustc 1.79.0

### Additional context

I'm working on https://github.com/tailcallhq/graphql-benchmarks/pull/258

**Comment by bnchi** [comment]
For me this showed up at the 3rd run of _./wrk/bench.sh_  but then I restarted the server and tried to reproduce the issue but couldn't do it  

![Screen Shot 2024-06-24 at 1 38 59 PM](https://github.com/tailcallhq/tailcall/assets/77180905/05bf5d74-2d0e-4533-a555-5673b23890af)

Using 4 core 16GB RAM codespace

**Comment by meskill** [comment]
I've prepared a fix https://github.com/tailcallhq/tailcall/pull/2291 for this.

You can try it to see if it fixes the issue for you.

**Comment by beelchester** [comment]
Yes, it has fixed the issue for me. Thanks!
