### ISSUE TITLE
transformer to flatten out types with single field

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#2343]
Write a `config/transformer` that unwraps types with one field.

**FROM**
```graphql
type Query {
  foo: Foo
}

# Type with only one field
type Foo { 
  bar: Bar
}

# Type with only one field
type Bar {
  a: Int
}
```

**TO**

```graphql
type Query {
  foo: Int
}
```

This can be achieved by using the `addField` and `omit` operators. 

**Technical Requirements**
- Should be configurable via the `Preset` settings.
- Should be enabled by default in config generation.
- Should be added before BetterTypeName but after TreeShaking transformers.
- Add integration tests in `tests/execution`

**IMPORTANT**
- The "Before" is the server schema and the "After" is the expected client schema.
- Link:
	- https://tailcall.run/docs/tailcall-dsl-graphql-custom-directives/#addfield-directive 
	- https://tailcall.run/docs/tailcall-dsl-graphql-custom-directives/#modify-directive
	- https://tailcall.run/docs/contributors/integration-testing/

**Comment by LeoLeSommer** [comment]
/attempt #2343

I have never contributed to any open source project before, so I will just try to see if I can manage to do something. This is just a test for me, so please feel free to ignore my attempt if you want to try to solve the issue yourself.

**Comment by varshith257** [comment]
@LeoLeSommer I am in support of you. Have a chance to you to solve this issue and I'll take up if you give up on it

**Comment by LeoLeSommer** [comment]
Thanks, i tell you if I'm stuck

**Comment by LeoLeSommer** [comment]
@varshith257 You can try to solve the issue if you want

**Comment by varshith257** [comment]
Not yet

**Comment by varshith257** [comment]
Sure @Shylock-Hg I have occupied with other works. Maybe I didn't get time to solve it till this weekend
