### ISSUE TITLE
chore: Parameterize `json_placeholder.rs` 

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#2349]
Make it work for both `serde_json_borrow` and `ConstValue`

**Comment by db-keli** [comment]
/attempt #2349 
To parameterize the json_placeholder.rs file and make it work for both serde_json_borrow::Value and ConstValue, I'll introduce a generic type parameter that represents the JSON value type.
I'll create a trait that abstracts the common functionality needed from both serde_json_borrow::Value and ConstValue. I'll then implement the trait for both of them

**Comment by ssddOnTop** [comment]
I give up, it issue is open for attempts.

**Comment by tusharmath** [comment]
Closing in favour of https://github.com/tailcallhq/tailcall/issues/2482
