### ISSUE TITLE
feat: disable the default presets which are applied on configuration during config generation.

### ISSUE THREAD

**Issue by laststylebender14** [tailcallhq/tailcall#2351]
## Present Behaviour
- Currently even if we user don't add the preset's in configuration, we apply some default preset's on configuration which are written in `preset.rs` file.

## Objective
- The goal is to modify the configuration generation process to no longer apply these default presets automatically. Instead, the user should have the complete freedom to define their own transformers without any defaults being enforced.

In following configuration file, we can specify the transformers that we want to apply on generated configuration. only specified transformers in preset section will be applied on generated configuration.

eg. mergeType and consolidateURL transformers will be applied on generated configuration.

```json

{
  "preset": {
    "mergeType": 1.0,
    "consolidateURL": 0.5
  },
}
```

## Technical Requirements
- add unit and integration tests wherever necessary.
- update the docs

**Comment by bnchi** [comment]
I would like to try and tackle this feature improvement if you're not working on it, the description is clear enough for me.
