### ISSUE TITLE
create a HTTP client per thread

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#2370]
Currently Tailcall's HTTP client is created once and shared across all its threads, during times of high-contention it can create performance issues. We propose that an http-client is created per thread lazily with each incoming request. 

**Technical Requirements**
- All existing tests should pass
- There should be no code duplication
- It should overall improve performance (Check via the nginx benchmark on CI)

**Comment by ssddOnTop** [comment]
I'll be in the queue

**Comment by Shylock-Hg** [comment]
@tusharmath I plan to move `http client` out of `TargetRuntime` and use `std::thread_local` to implement it. How do you think about it?

**Comment by tusharmath** [comment]
I think you need a wrapper HttpClient on top our existing one. The wrapper picks the thread local instance if available or creates a new one if not. The wrapper is stored inside of the TargetRuntime, the shape of TargetRuntime shouldn't change.

**Comment by Shylock-Hg** [comment]
> I think you need a wrapper HttpClient on top our existing one. The wrapper picks the thread local instance if available or creates a new one if not. The wrapper is stored inside of the TargetRuntime, the shape of TargetRuntime shouldn't change.

Ok, if so. I think `ConcurrentMap<ThreadID, HttpClient>` is a good method, in this way, we provide a method `fn get_http_client(&self) -> HttpClient` to get `HttpClient` by current thread id. WDYT?

**Comment by bnchi** [comment]
@Shylock-Hg Are you addressing the issues in the closed PR ? If not I'll take your spot on this issue and attempt

**Comment by Shylock-Hg** [comment]
It's open to try.

**Comment by bnchi** [comment]
I don't think there's a massive improvement on the current benchmarks it's kinda worse in term of req/sec, I tried to maintain a hashmap of thread Id -> client that improved thread_local approach a bit. 

Probably I'm missing something not sure ! 

If anyone wants to give this issue a try feel free I'm canceling my attempt

**Comment by tusharmath** [comment]
We expected some improvements with this change, however, it isn't happening. Will close this issue for now. Also closing all related PRs.
