### ISSUE TITLE
Improve performance of `cargo build` whenever `src` changes by one order of magnitude.

### ISSUE THREAD

**Issue by tontinton** [tailcallhq/tailcall#2426]
This is the first rust project I opened where I need to get out of battery saver mode into high performance mode.

Even then, making a save and then waiting 5+ seconds until rust analyzer gives me feedback is way too long, I have no idea how you manage to keep working like this.

The solution is to separate as much as possible into subdirs, so that src will not need to compile the entire crate when saving a file.

WDYT?

**Comment by ssddOnTop** [comment]
Will need to move cli anyways

**Comment by bnchi** [comment]
My rust analyzer isn't that slow on neovim it's quite fast after the initial startup

**Comment by tusharmath** [comment]
@tontinton I don't know about you about build-time is like weight gain. You don't realize that you have gained weight unless you meet a friend after a long time and they tell you. 

I would love to shed some weight! Here is the initial report of `cargo build --timings` hopefully someone can take it from here.

<img width="611" alt="Screenshot 2024-07-13 at 3 26 13 PM" src="https://github.com/user-attachments/assets/f1210155-24a8-4b51-905b-58c651efa80e">


[cargo-timing-20240713T095153Z.html.zip](https://github.com/user-attachments/files/16201667/cargo-timing-20240713T095153Z.html.zip)

**Comment by tusharmath** [comment]
**Steps**

```bash
# Clean the project
cargo clean 

# Create first build
cargo build

# Modify a file
touch src/lib.rs

# Create second build
cargo build # Should be 10x faster than before 
```
**Requirements**
- There should be a 10x improvement in build performance of the second run.
- Update contribution guidelines for improving build times.

**Comment by bnchi** [comment]
> **Steps**
> 
> ```shell
> # Clean the project
> cargo clean 
> 
> # Create first build
> cargo build # 1-2 mins
> 
> # Modify a file
> touch src/lib.rs
> 
> # Create second build
> cargo build # Current: 6-7 secs, expected <600ms
> ```
> 
> **Requirements**
> 
>     * There should be a 10x improvement in the build performance of the second run.
> 
>     * Update contribution guidelines for improving build times.

I'm going to give this a shot hoping this will improve my workflow not sure about the 10x but any gains are good :p

**Comment by tusharmath** [comment]
Hope you wouldn't mind a tip if there is a realistic improvement in performance ;)

**Comment by webbdays** [comment]
@tusharmath 

[profile.dev]
opt-level = 0
codegen-units = no_of_processors
incremental = true
lto = false

These compiler options helped with decreasing 2nd build time from around 14 to around 10 secs.
It also changes when we choose different number of codegen-units.
So, it seems one need to pick the right number depending on the codebase and their computer.

**Comment by tusharmath** [comment]
@webbdays Feel free to create a PR. It's a good starting point.

**Comment by bnchi** [comment]
I'm still doing some analysis, one of the things that I saw in the flamegraph report for my machine was that tailcall binary crate linking is taking a big chunk of the time, if anyone is using linux they can try out mold, on macos most likely(I don't use a mac) you can try out lld linker if it's not a default.

**Comment by bnchi** [comment]
Link for mold https://github.com/rui314/mold

**Comment by karatakis** [comment]
I tried both with mold (clang) and without. With mold you can achieve a faster linking time that's true, but the recompile tame gains are not significant,

**normal-clean-build:**

![image](https://github.com/user-attachments/assets/3c78aea3-d440-4355-b4f1-de8e8ac45de3)

**mold-clean-build:**

![image](https://github.com/user-attachments/assets/3cae6ac7-1631-429c-bcba-f5ac8fb448a0)

**normal-rebuild:**

![image](https://github.com/user-attachments/assets/0b69a203-4d26-493a-aa06-0f7819d138ec)

**mold-rebuild:**

![image](https://github.com/user-attachments/assets/b0cd9dfc-e881-4245-9498-d9e2cdf0513f)

**Comment by bnchi** [comment]
If anyone is interested in a better/faster development experience on tailcall, I'm using bacon now for code checks and switched off rust analyzer checks and kept it to help me jump between definitions, references etc ... 

cargo check is a lot more faster than RA and takes much less memory now hence the improvement in dev time for me. 

https://github.com/Canop/bacon
