### ISSUE TITLE
refactor: Make `JsonPlaceholder.rs` parametric

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#2482]
Currently `json_placeholder.rs` is tightly coupled with `ConstValue` implementation. Refactor that out and use a generic `Value` type-parameter and leverage `JsonLike` internally.

**Comment by ssddOnTop** [comment]
Looks like duplicate issue

**Comment by ssddOnTop** [comment]
feel free to attempt even while I am working on this one.. I am not sure if I'll be able to close the issue.

**Comment by Anshgrover23** [comment]
@ssddOnTop thanks bro. i am also trying. best luck

**Comment by Anshgrover23** [comment]
@ssddOnTop sorry bro i am not able to do i think i am closing my attempt
