### ISSUE TITLE
Issue: DateTime Scalar Configuration Errors

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcall#2580]
**Description**  
There are issues with the `DateTime` scalar configuration in the GraphQL config. When the `DateTime` scalar is defined in the config, the following error occurs:  
- **Error 1**: "Scalar DateTime is Predefined"

When the `DateTime` scalar is not defined in the config, the following error occurs:  
- **Error 2**: "Type DateTime not found"

**Screenshots**  
![WhatsApp Image 2024-07-30 at 3 00 43 PM](https://github.com/user-attachments/assets/f9d430f1-4800-4b2b-acfd-9f4dad181be5)

**Comment by meskill** [comment]
for some reason DateTime is defined in the predefined list https://github.com/tailcallhq/tailcall/blob/e129a782eec5f5988fbfa0ddef5f37e2249e625a/src/core/scalar.rs#L11

but it's neither the part of the graphql spec nor part of our defined scalars
