### ISSUE TITLE
Update `wizard` to programatically control the LLM adapter and model

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#2658]
Currently based on environment variables the GenAI library uses a particular Adapter and Model. We wish to change that and provide a type-safe way to integrate it.

**Example**
```rust
let model = Adapter::Groq::Llama3_8b_8192;
let wiz = Wizard::new(model);
```

**Technical Requirements**
- `Adapter` shouild be defined in `llm/adapter.rs`.
- Secrets should be read as `TAILCALL_SECRET` and sent to the LLM

**Comment by palak2002** [comment]
> ## 💎 $50 bounty [• Tailcall Inc.](https://console.algora.io/org/tailcallhq)
> ### Steps to solve:
> 1. **Start working**: Comment `/attempt #2658` with your implementation plan
> 2. **Submit work**: Create a pull request including `/claim #2658` in the PR body to claim the bounty
> 3. **Receive payment**: 100% of the bounty is received 2-5 days post-reward. [Make sure you are eligible for payouts](https://docs.algora.io/bounties/payments#supported-countries-regions)
> 
> 🙏 Thank you for contributing to tailcallhq/tailcall! 🧐 Checkout our [guidelines](https://tailcall.run/docs/contribution-guidelines/) before you get started. 💵 More about our [bounty program](https://tailcall.run/docs/contributors/bounty/).
> 
> Attempt	Started (GMT+0)	Solution
> 🟢 @ssddOnTop	Aug 11, 2024, 9:05:39 AM	[#2659](https://github.com/tailcallhq/tailcall/pull/2659)
> 🟢 @dekkku	Aug 11, 2024, 9:53:07 AM	[#2660](https://github.com/tailcallhq/tailcall/pull/2660)

/attempt #2658
I plan to implement a type-safe `Adapter` and integrate it with the `Wizard` struct, replacing the current environment variable-based configuration. I'll define the `Adapter` enum in `llm/adapter.rs` and modify the `Wizard` struct to accept an adapter instance. Secrets will be read from the environment as `TAILCALL_SECRET` and securely passed to the library.
