### ISSUE TITLE
Discord invite link is invalid/expired

### ISSUE THREAD

**Issue by shricastic** [tailcallhq/tailcall#2668]
Please update the discord chat link.
![image](https://github.com/user-attachments/assets/f749b225-3f15-4159-b746-a967885dfd93)

**Comment by laststylebender14** [comment]
@shricastic Could you please let me know from where you're trying to use the Discord link? I’ve tested some GitHub links and they seem to be working fine. For example, [this invite link](https://discord.com/invite/kRZBPpkgwq) is working without any issues.

**Comment by shricastic** [comment]
Hey! The link given in README.md had some issues. I think its probably fixed
