### ISSUE TITLE
gRPC with Multiple .proto files: : No such file or directory (os error 2)

### ISSUE THREAD

**Issue by BenNeighbour** [tailcallhq/tailcall#2678]
### Prerequisites

- [x] I have checked the existing issues to ensure this is not a duplicate.
- [x] I am running the latest version of Tailcall.

### Steps to reproduce

1. Create a Tailcall server, that links to a gRPC server using Reflection.
2. Split the server protobufs into two files:
```proto
// dto.proto

syntax = "proto3";

package goodbye;

import "google/protobuf/timestamp.proto";

// The request message containing the user's name.
message GoodbyeRequest {
  string message = 1;
}

// The response message containing the greetings
message GoodbyeReply {
  string message = 1;
  string user_uuid = 2;
  google.protobuf.Timestamp timestamp = 3;
}

```
and,
```proto
// rpc.proto

syntax = "proto3";

package goodbye;

import "proto/b_service/goodbye/dto.proto";
import "google/protobuf/timestamp.proto";

// The greeting service definition.
service Goodbye {
  // Sends a goodbye
  rpc SayGoodbye (GoodbyeRequest) returns (GoodbyeReply) {}
}

```
3. Compile into language of choice (I'm using Golang), using Buf.
4. Enable Server reflection on the gRPC Server
5. Test the RPCs via Postman with Reflection (they work smoothly)
6. Hook this up to Tailcall

### Expected behavior

Tailcall to run smoothly. Any help would be much, much appreciated as this is a very common design pattern in production.

### Actual behavior

Gives an error saying it cannot read the file or directory of an imported proto file when using gRPC reflection. However, other gRPC reflection-based clients such as Postman and Insomnia work fine.

### Logs
<img width="1461" alt="Screenshot 2024-08-13 at 01 29 32" src="https://github.com/user-attachments/assets/0c14c240-50c3-4c24-9a5d-8bce1aec4996">

**Comment by ssddOnTop** [comment]
The path to proto files should be relative to the config file (even the imported ones)

**Comment by ssddOnTop** [comment]
this works for me:

```
.
├── examples
│   └── hello.graphql
└── protos
    ├── rpc.proto
    └── proto
        └── b_service
            └── goodbye
                └── dto.proto
```

where hello.graphql is:

```gql
schema
  @link(type: Protobuf, src: "../protos/rpc.proto")
  @server(port: 8000)
  @upstream(baseURL: "http://jsonplaceholder.typicode.com", httpCache: 42, batch: {delay: 100}) {
  query: Query
}

type Query {
  hello: String! @expr(body: "Hello, world!")
}
```

**Comment by karatakis** [comment]
@BenNeighbour, I am investigating the issue. I will let you know about my findings and give you a solution.

**Comment by karatakis** [comment]
The issue is on https://github.com/tailcallhq/tailcall/blob/c7c0b23ade61ce4d4ac4da532b60797e80426089/src/core/proto_reader/reader.rs#L118. The problem is that the current configuration reads either from google standard files or a local file, but there is no implementation for gRPC reflection reading. So, the software fails trying to read from a file that does not exist.

I will go ahead and extend the reader to read from the reflection API. I will open a PR when it is ready.

**Comment by BenNeighbour** [comment]
I thought it would be something of that nature, as it did not fail on my /google/*.proto files. Thank you @karatakis !

**Comment by karatakis** [comment]
@BenNeighbour I fixed the issue, here is the PR https://github.com/tailcallhq/tailcall/pull/2683

I will have it ready by tomorrow. I need to construct a test case so we do not regress in the future.

Thanks for reporting the issue to us.

**Comment by BenNeighbour** [comment]
Hey, any updates on this? Cheers
