### ISSUE TITLE
feat:  Query complexity and depth

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcall#2725]
**Is your feature request related to a problem? Please describe.**
I need a way to limit the depth of queries which can be accepted by my graphql server

**Describe the solution you'd like**
[Async graphQL supports this](https://async-graphql.github.io/async-graphql/en/depth_and_complexity.html#:~:text=Limiting%20Query%20depth,with%20a%20depth%20of%203%20.&text=You%20can%20limit%20the%20depth,too%20deep%20will%20be%20returned.)

**Comment by webbdays** [comment]
do we need to get those query complexity and depth as input from user in config?
