### ISSUE TITLE
Add Tailcall to the GraphQL Landscape

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#2750]
Update this — https://github.com/graphql/graphql-landscape/blob/main/landscape.yml

Update it for :
1. Tools
2. Services

**Technical Requirements**

- Add screenshots of the final look in the PR

[Tailcall Logos.zip](https://github.com/user-attachments/files/16735997/Tailcall.Logos.zip)

**Comment by shivamgupta88** [comment]
/attempt #2750
please assign me this issue i want to work on this
