### ISSUE TITLE
Use `option_env!` to capture GA secrets from the env variable from CI

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#2777]
Currently the GA Secrets and Measurement ID is embeded in code, we would like to embed it at compile time instead via Github Secrets.

**Comment by Hridoy000368** [comment]
@ridoyshak35

**Comment by Hridoy000368** [comment]
Attempt #2777

**Comment by neo773** [comment]
@Hridoy000368 
Can you please stop spamming with the constant random messages and then deleting them afterwards?
The issue is closed as completed.
