### ISSUE TITLE
feat: accept self-signed certificates for development

### ISSUE THREAD

**Issue by asimpleidea** [tailcallhq/tailcall#2801]
**Is your feature request related to a problem? Please describe.**
If you have REST APIs hosted somewhere with a self-signed certificate (for example while developing), tailcall will return an error like this:

```json
{
    "data": null,
    "errors": [
        {
            "message": "IOException: Request error: error sending request for url (https://example.com/api/v1/service): error trying to connect: invalid peer certificate: Other(CaUsedAsEndEntity)",
            "locations": [
                {
                    "line": 2,
                    "column": 5
                }
            ]
        }
    ]
}
```

**Describe the solution you'd like**
Some alternatives:

- `tailcall start --skip-insecure-tls` or
- on graphql schema (something similar on Json or yaml)
```graphql
schema   # Specify server configuration: Start GraphQL server at 0.0.0.0:8000
  @server(port: 8000)
  # Specify a base url for all http requests
  @upstream(baseURL: "https://example.com", skipInsecureTls: true) {
  query: Query
}
```

**Describe alternatives you've considered**
None.

**Additional context**
Still too new to tailcall so I am not very familiar with its code, but should involve using `.danger_accept_invalid_certs(true)` if using reqwest.

**Comment by tusharmath** [comment]
I like the upstream setting approach. We could call it - verifySSL setting it to true by default.

**Comment by tusharmath** [comment]
Would you be interested in adding this change?

**Comment by asimpleidea** [comment]
> Would you be interested in adding this change?

Sure, I have already implemented this.

I will polish the code and will create a PR ASAP :)

**Comment by tusharmath** [comment]
@asimpleidea did u managed to work on this @asimpleidea ?

**Comment by asimpleidea** [comment]
still working on it, sorry, I had to take care of some other things. Hopefully I will be able to introduce it this week
