### ISSUE TITLE
refactor: add support for `meta` in `@link`

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#2821]
Link doesn't support for additional meta information with the URLs. Let's add it, for eg:

```graphql
schema @link(
  src: "http://products:4000",
  type: SubGraph,
  meta: { 
    description: "Product service subgraph", 
    version: "1.2.0", 
    environment: "production"
  }
){
  query: Query
}
```

**Technical Requirements**
- Meta should accept any `JSON` scalar.
- Add concise tests for `meta`

**Comment by itsdheerajdp** [comment]
/attempt #2821

@tusharmath can i get it assigned so that i'll start working on it
