### ISSUE TITLE
Support for handle/format error response

### ISSUE THREAD

**Issue by vibhor-d11** [tailcallhq/tailcall#2884]
**Is your feature request related to a problem? Please describe.**
How do i handle error response? backend service may throw different error responses with different error codes, i might have to return custom formatted error response based on backend response, how do i do that?
**Describe the solution you'd like**
a support for custom error handler to format error and return based on requirement. Would be very beneficial if it could be provided with js support to write custom error handler

**Additional context**
Mostly error response sent to app via graphql may need custom error messages, status codes depending on backend response so a error handler is required to format error that is sent as response via graphql

**Comment by tusharmath** [comment]
Can you provide an example of how a typical error response would look like vs how would you want it to be.

**Comment by vibhor-d11** [comment]
like if my status code is between 500-599 , i may send a response with generic error  message, also error response might be sending me some key MsgCode eg, then i may have different error response mapping on graphql side also based on this msg code etc
