### ISSUE TITLE
Not able to fetch data from introspection query with latest version

### ISSUE THREAD

**Issue by vibhor-d11** [tailcallhq/tailcall#2912]
### Prerequisites

- [ ] I have checked the existing issues to ensure this is not a duplicate.
- [ ] I am running the latest version of Tailcall.

### Describe the bug

getting empty data response for introspection query with latest version  v0.114.2.

### Steps to reproduce

Started local server and hit the following query via postman

```
curl --location --request POST 'http://127.0.0.1:9999/graphql' \
--header 'Content-Type: application/json' \
--data-raw '{"query":"query  _service { _service { sdl } }","variables":{}}'
```

got following response

```
{
    "data": {}
}
```

### Expected behavior

Should return response for the introspection query

### Actual behavior

A description of what actually happened.

### Environment information:

- **Operating System**: (e.g., Ubuntu 20.04, macOS Big Sur, Windows 10)
- **Tailcall Version**: (e.g., v1.0.2)
- **Rust Version**: (e.g., `rustc 1.58.0`)
- **GraphQL Client/version** (e.g., `curl/8.1.2`)

### Additional context

Add any other context about the problem here, such as relevant logs, error messages, or stack traces.

### Logs

```
Paste any relevant logs here.
```

**Comment by tusharmath** [comment]
@vibhor-d11 can you try adding the following to the schema and check?

```graphql
type Greetings @expr(body: {greet: "Hello World!"}) {
  greet: String
}
```

**Comment by tusharmath** [comment]
The reason this doesn't work is because you might not have any entity defined in your schema. We can add a flag to support subgraph capabilities explicitly. Let me know what you think.

**Comment by vibhor-d11** [comment]
what is meant by entity i didn't get? i do have a query in schema which resolves a endpoint with a defined schema like:

```
schema
  @server(port: 9999, hostname: "0.0.0.0")
  @link(type: Operation, src: "health.graphql")
  @upstream(
    baseURL: "base-url"
    allowedHeaders: ["Authorization"]
  ) {
  query: Query
}

type Inventory {
  logo: String!
  campaignId: Int!
  viewAllUrl: String!
  brandName: String!
}

type Data {
  data: [Inventory]
}

type HealthCheckResponse {
  status: String!
}

type Query @addField(name: "inventory", path: ["inventory", "data"]) {
  inventory(realEstateName: String!, contextValue: String!): Data
    @http(
      path: "/inventory"
      query: [
        {
          key: "realEstateName"
          value: "{{.args.realEstateName}}"
          skipEmpty: false
        }
        {key: "contextValue", value: "{{.args.contextValue}}", skipEmpty: false}
      ]
    )
    @omit
  health: HealthCheckResponse @expr(body: {status: "Success"})
}
```

Now this query runs on a subgraph, and a different service query the subgraph for introspection query to register it with its schema.

**Comment by meskill** [comment]
@vibhor-d11 Thanks for creating an issue.
We fixed the federation introspection call in latest versions. Please update the tailcall and add [enableFederation](https://tailcall.run/docs/tailcall-dsl-graphql-custom-directives/#enablefederation) flag to your subgraph in order to be able to call the federation instrospection
