### ISSUE TITLE
When `@link` multiple subgraphs the @server port is overwritten from the last schema

### ISSUE THREAD

**Issue by karatakis** [tailcallhq/tailcall#2993]
### Prerequisites

- [X] I have checked the existing issues to ensure this is not a duplicate.
- [X] I am running the latest version of Tailcall.

### Describe the bug

When `@link` multiple subgraphs, the `@server` port from the main file is overwritten from the last schema.

### Steps to reproduce

**main.graphql**
```gql
schema
  @link(type: Config, src: "./a.graphql")
  @link(type: Config, src: "./b.graphql")
  @server(port: 8080)
  @upstream {
  query: Query
}

type Query {
  main_version: Int! @expr(body: 1)
}
```

**a.graphql**
```gql
schema
  @server(port: 8081)
  @upstream {
  query: Query
}

type Query {
  a_version: Int! @expr(body: 1)
}
```

**b.graphql**
```gql
schema
  @server(port: 8082)
  @upstream {
  query: Query
}

type Query {
  b_version: Int! @expr(body: 1)
}
```

### Expected behavior
The server should listen on port **8080**

### Actual behavior

The server listens at **8082**

**Comment by ssddOnTop** [comment]
it's because of our current merge_right implementation https://github.com/tailcallhq/tailcall/blob/a46a773f8a56fd2b9a22ec67dd4fd12d4415d266/src/core/merge_right.rs#L9C1-L19C1

we probably shouldn't directly implement merge right for `Option<u16>` as config::Server has `pub port: Option<u16>`
