### ISSUE TITLE
Move `valid` to a new repo

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#3002]
- Move valid type into https://github.com/tailcallhq/valid
- Integrate CI using https://github.com/emmanuelnk/github-actions-workflow-ts
	- Run Tests
	- Check for WASM compat
	- Publish as a lib on https://crates.io/
- Add a README with a simple example

**Comment by siddhakdak** [comment]
@tusharmath Can you please more elaborate about this issue like do I have to create a new repo and mode valid to that one ? Can you please explain this issue more.

**Comment by siddhakdak** [comment]
as much i had understood is that I have to move **src/core/valid** to **https://github.com/tailcallhq/tc_valid/tree/main/src** this one repo.  am I correct? should I move forward for it? one more query do I have to move this or do I have to make a copy of it.

**Comment by ssddOnTop** [comment]
Hey @siddhakdak I am already working on this and majority of the work is done
