### ISSUE TITLE
Bug in the nested queries when working with @graphql

### ISSUE THREAD

**Issue by MedHeikelBouzayene** [tailcallhq/tailcall#3088]
### Prerequisites

- [x] I have checked the existing issues to ensure this is not a duplicate.
- [x] I am running the latest version of Tailcall.

### Describe the bug

Let's have this schema:
```gql
schema @server(port: 8000, hostname: "0.0.0.0") {
  query: Query
}

type Query {
  queryNodeA: NodeA @graphQL(url: "http://localhost:8083", name: "nodeA")
}

type NodeA {
  name: String
  nodeB: NodeB
  nodeC: NodeC
}

type NodeB {
  name: String
  nodeA: NodeA
  nodeC: NodeC
}

type NodeC {
  name: String
  nodeA: NodeA
  nodeB: NodeB
}
```
when I send try this query:
```
query QueryNodeA {
    queryNodeA {
        name
        nodeB {
            name
        }
        nodeC {
            name
        }
    }
}
```
that's the query sent to the graphql server: > Body
`{ "query": "query { nodeA { name nodeB { name } nodeC } }" }`

### Expected behavior
That's the query expected to be sent to the graphql server:
> Body

`{ "query": "query { nodeA { name nodeB { name } nodeC  { name } } }" }`

**Comment by tusharmath** [comment]
This can be fixed by adding a `jit/transform/graphql.rs`. This transformer will be responsible to building the exact GraphQL query for each source GraphQL query.

**Comment by laststylebender14** [comment]
@MedHeikelBouzayene Can you try this [PR](https://github.com/tailcallhq/tailcall/pull/3106) and see if it resolves your use case?

**Comment by MedHeikelBouzayene** [comment]
Yes it does resolve it, thank you
