### ISSUE TITLE
fix: validation error for auth-provider not being found

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#3144]
Currently when the auth provider isn't found the trace produced isn't correct.

**Integration Test**

- The trace for when protected is on a type should contain only the type name and the directive name.
- The trace for the field should contain type name, field name and directive name.
- Here is a initial snapshot test to get started with.

```md
	---
	error: true
	---
	
	# auth multiple
	
	```graphql @config
	schema @server @upstream @link(id: "a", src: ".htpasswd_a", type: Htpasswd) {
	  query: Query
	}
	
	type Query {
	  default: String @expr(body: "data") @protected(id: ["a", "b", "c"])
	  foo: Foo @expr(body: {bar: "baz"})
	}
	
	type Foo @protected(id: ["x"]) {
	  bar: String
	}
	```
	
	```text @file:.htpasswd_a
	testuser1:$apr1$e3dp9qh2$fFIfHU9bilvVZBl8TxKzL/
	testuser2:$2y$10$wJ/mZDURcAOBIrswCAKFsO0Nk7BpHmWl/XuhF7lNm3gBAFH3ofsuu
	```
```


**Expected Snapshot**


```
	---
	source: tests/core/spec.rs
	expression: errors
	snapshot_kind: text
	---
	[
	  {
	    "message": "Auth provider x not found",
	    "trace": [
	      "Foo",
	      "@protected"
	    ],
	    "description": null
	  },
	  {
	    "message": "Auth provider b not found",
	    "trace": [
	      "Query",
	      "default",
	      "@protected"
	    ],
	    "description": null
	  },
	  {
	    "message": "Auth provider c not found",
	    "trace": [
	      "Query",
	      "default",
	      "@protected"
	    ],
	    "description": null
	  }
	]

```


**NOTE**
Should be picked up after https://github.com/tailcallhq/tailcall/pull/3142

**Comment by Yash-sudo-web** [comment]
hey @dekkku, i am already working on this issue and attempted it first, my draft PR is already up, i think you cannot submit a PR until someone else's attempt is ongoing.
