### ISSUE TITLE
Remove redundant operators in Expression

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#330]
Drop the following operators from expression — 

  - [ ] Context
  - [ ] Literal
  - [ ] EqualTo
  - [ ] Input

`EvaluationContext` can provide direct access to these operations so at runtime we can access them directly.

**Comment by lprakashv** [comment]
attempt #330

**Comment by lprakashv** [comment]
@tusharmath I have couple of questions:

1. what about the `Literal` and the TODO over there: `// TODO: this should async_graphql::Value`? Do we still need to consider this or drop it altogether.
2. After dropping the above mentioned expressions, the original `Expression` would be left with just `Unsafe(Operation)`, so, should we call/refactor the `Expression` as `UnsafeOperation { JS(...), Endpoint(...) }`?

**Comment by tusharmath** [comment]
1. We should drop it.
2. You are right. We will have a `Path` operator and move some of the logic which is inside of `into_schema.rs` right into `Expression`. This will simplify `into_schema`. 
Hope this makes sense :)

**Comment by meskill** [comment]
@tusharmath could you put little more details on how you see the solution?

Currently, these operators are used to wrap logic of directive operators into single `FieldDefinition.resolver`. By removing it we need to move this logic somewhere else but this includes different actions and having some wrapper like `Expression` for this looks reasonable.

**Comment by tusharmath** [comment]
@meskill Those primitives aren't used anywhere just yet. That's the reason why we can drop them.

**Comment by meskill** [comment]
I see they are used in `src/blueprint/from_config.rs` file either [directly](https://github.com/tailcallhq/tailcall/blob/08008ea4de0c069397af61930ac955a38fd84af4/src/blueprint/from_config.rs#L422) or with [lambda abstraction](https://github.com/tailcallhq/tailcall/blob/08008ea4de0c069397af61930ac955a38fd84af4/src/blueprint/from_config.rs#L575)

**Comment by tusharmath** [comment]
I think we can still drop Context::Value and EqualTo and Input.

**Comment by meskill** [comment]
only `EqualTo` is not used actually
