### ISSUE TITLE
Docstrings are not preserved in the output schema

### ISSUE THREAD

**Issue by sujeetsr** [tailcallhq/tailcall#339]
### Description
Docstrings in the tailcall configuration graphql file are not present in the generated schema, and so do not show up in tools like graphiql

### Steps to reproduce
Add a docstring in `jsonplaceholder.graphql`, for example

```graphql
schema
  @server(
    port: 8000
    baseURL: "http://jsonplaceholder.typicode.com"
    enableHttpCache: true
    enableGraphiql: "/graphiql"
    enableQueryValidation: false
  ) {
  query: Query
}

type Query {
  posts: [Post] @http(path: "/posts")
}

"""
This is a User
"""
type User {
  id: Int!
  name: String!
  username: String!
  email: String!
  phone: String
  website: String
}

"""
This is a Post
"""
type Post {
  id: Int!
  userId: Int!
  title: String!
  body: String!
  user: User @http(path: "/users/{{value.userId}}")
}
```

Run `tc start jsonplaceholder.graphql` and hit [http:://localhost:8000/graphiql](http:://localhost:8000/graphiql) and note that there are no dosctrings in the output schema.

### Expected behavior
Docstrings from the input graphql file are preserved in the final (output) schema.

### Actual behavior
No docstrings are present in the output schema

**Comment by rishi-raj-jain** [comment]
Which url do I see to check the output schema?

**Comment by tusharmath** [comment]
@rishi-raj-jain Updated the issue with a sample config. You should hit `/graphiql` to get the output schema.
