### ISSUE TITLE
Optimize `RequestTemplate::to_request`

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#348]
**Problem**
The `to_request` implementation is supposed to be called for every http call. We want to make sure that it's as fast as possible.

**Solution**
We need to perform a deep analysis of how it can be implemented in the fastest way possible. We write benchmarks to showcase current performance of the function and then once optimized show % improvements.

**Technical Requirements**
- Write benchmarks and optimize `RequestTemplate::to_request`.
- Showcase initial performance number and numbers after optimizations.

**Additional Notes:**
- Performance can be improved by reducing allocations and using references.
- Reducing overall compute requirements.
- Pre-computing the request from a template in scenarios where it's possible.

**Comment by mahmoudfarouq** [comment]
Hi, can you please elaborate more on what kind of optimizations do you have in mind?

**Comment by tusharmath** [comment]
@mahmoudfarouq Updated the issue. Hope it makes sense, feel free to post questions on the discord channel for a faster response time :)

**Comment by tusharmath** [comment]
fixed in #407
