### ISSUE TITLE
Throw an error if `graphiql` uses a restricted route

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#349]
To enable graphiql we can set a route in the `@server` config for eg:

```graphql
schema @server(enableGraphiql: "/graphiql") {
  query: Query
  mutation: Mutation
}
```

Before starting the server we should check if the route matches any of the restricted routes for example — `/` and `/graphql`.
Incase it does an error should be thrown 

```yml
message: Cannot use restricted routes '/' for enabling graphiql 
trace: [schema, server, enableGraphiql]
```

**Comment by Vishal-Sikka** [comment]
@tusharmath  check my pr and give more info if there other restricted routes

**Comment by tusharmath** [comment]
@Vishal-Sikka The build is failing.

**Comment by Vishal-Sikka** [comment]
> @Vishal-Sikka The build is failing.

fixed
