### ISSUE TITLE
For optional properties in `Field` type replace usage of `Option` with serde(default)

### ISSUE THREAD

**Issue by meskill** [tailcallhq/tailcall#367]
Followed from [the discussion](https://github.com/tailcallhq/tailcall/pull/359#discussion_r1339730589)

For some fields there are `Option` wrapper is used to mark that the property might not be defined by the user and therefore should get some default value. But using `Option` instead of raw type like bool may lead to bugs like mentioned in https://github.com/tailcallhq/tailcall/issues/342

# Suggested solution

Instead of using `Option` for such cases use `#[serde(default)]` attribute as described in [serde doc](https://serde.rs/attr-default.html)

**Comment by tusharmath** [comment]
Closing in favour of #371
