### ISSUE TITLE
Autogenerate graphQL Schema for all the existing directives at build time

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#374]
**Problem**
While writing a .graphql file, the IDEs throw errors stating - `@server` and `@http` etc. are unrecognized directives.

**Solution**
- We will generate a .graphql file which will have all the directive definitions that tailcall supports as described here — https://tailcall.run/docs/intro/operators/
- We will use a [graphql-config] to link them together to help the IDE

[graphql-config]: https://the-guild.dev/graphql/config/docs/user/usage

  ```yml
  #.graphql.yaml
  schema:
    - "./assets/tailcall.graphql" # generated
    - "./assets/jsonplaceholder.graphql" # existing configuration
  ```
  Generated `tailcall.graphql` would like this — 

  ```graphql
  # tailcall.graphql
  directive @server(
    baseURL: String
    port: Int
    # other fields ...
  ) on SCHEMA
  
  directive @http(
    path: String
    method: String
    # other fields ...
  ) on FIELD_DEFINITION
  ```
  

**Tech Requirements**
- At build time, we will generate a `tailcall.graphql`.
- The generated graphql file should always be in sync with the struct representing the operator defined as a struct. 
- If the struct changes shape, the generated file should should have the new changes.

**Comment by haruncurak** [comment]
Happy to work on this one! 
/attempt #374

**Comment by ologbonowiwi** [comment]
The first step that I see would be to get these "values" (by values, I mean field names and types) cause this will enable us to create an actual parser that'll turn from rust code to the `.graphql` definition that we expect

I'm unsure how we could do this sort of dynamic thing (read from the actual "type system" to parse it to the equivalent `.graphql` data); I found [struct_iterable](https://crates.io/crates/struct_iterable) that maybe can help but doesn't do exactly what we need. It turns the instance of the struct into an `[[key, value]]` iterable rather than the struct itself (that would be `[[key, type]]` rather than `[[key, value]]`)

If we stick with [struct_iterable](https://crates.io/crates/struct_iterable), one option would be to instantiate the struct, check/verify the value type, and then parse it to the `.graphql` equivalent.

Can you provide some guidance/your perspective here, @tusharmath?

**Comment by tusharmath** [comment]
Use macro API to get the schema of the structures and enumeration. Then
generate directives using the schema. You could use a crate alternatively,
im not aware of such a crate but could try to dig up something.

**Comment by tusharmath** [comment]
```graphql
use proc_macro::TokenStream;
use quote::quote;
use syn::{parse_macro_input, Data, DeriveInput, Fields, Field};

#[proc_macro]
pub fn schema(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);

    let expanded = match input.data {
        Data::Struct(data) => {
            let mut fields_tokens = vec![];
            for field in data.fields.iter() {
                if let Some(name) = &field.ident {
                    let ty = get_type_representation(&field.ty);
                    fields_tokens.push(quote! { 
                        Field { name: #name.to_string(), ty: #ty }
                    });
                }
            }

            quote! {
                Schema::Struct(vec![#(#fields_tokens),*])
            }
        }
        Data::Enum(data) => {
            let mut variants_tokens = vec![];
            for variant in data.variants.iter() {
                let variant_name = variant.ident.to_string();
                let mut fields_tokens = vec![];

                if let Fields::Named(fields) = &variant.fields {
                    for field in fields.named.iter() {
                        if let Some(name) = &field.ident {
                            let ty = get_type_representation(&field.ty);
                            fields_tokens.push(quote! {
                                Field { name: #name.to_string(), ty: #ty }
                            });
                        }
                    }
                }

                variants_tokens.push(quote! {
                    Variant {
                        name: #variant_name.to_string(),
                        fields: vec![#(#fields_tokens),*]
                    }
                });
            }

            quote! {
                Schema::Enum(vec![#(#variants_tokens),*])
            }
        }
        _ => panic!("Only struct and enum are supported!"),
    };

    expanded.into()
}

fn get_type_representation(ty: &syn::Type) -> proc_macro2::TokenStream {
    if let syn::Type::Path(type_path) = ty {
        if let Some(segment) = type_path.path.segments.first() {
            match segment.ident.to_string().as_str() {
                "bool" => return quote! { Type::Bool },
                "char" => return quote! { Type::Char },
                "str" => return quote! { Type::Str },
                "u8" => return quote! { Type::U8 },
                "u16" => return quote! { Type::U16 },
                "u32" => return quote! { Type::U32 },
                "u64" => return quote! { Type::U64 },
                "u128" => return quote! { Type::U128 },
                "i8" => return quote! { Type::I8 },
                "i16" => return quote! { Type::I16 },
                "i32" => return quote! { Type::I32 },
                "i64" => return quote! { Type::I64 },
                "i128" => return quote! { Type::I128 },
                "f32" => return quote! { Type::F32 },
                "f64" => return quote! { Type::F64 },
                _ => {
                    let other = segment.ident.to_string();
                    return quote! { Type::Other(#other.to_string()) };
                }
            }
        }
    }
    panic!("Unsupported type!");
}

// schema_def/src/lib.rs

pub enum Schema {
    Struct(Vec<Field>),
    Enum(Vec<Variant>),
}

pub struct Field {
    pub name: String,
    pub ty: Type,
}

pub struct Variant {
    pub name: String,
    pub fields: Vec<Field>,
}

pub enum Type {
    Bool,
    Char,
    Str,
    Byte,
    I8,
    I16,
    I32,
    I64,
    I128,
    U8,
    U16,
    U32,
    U64,
    U128,
    F32,
    F64,
    Other(String),
}

```

Some chat gpt help.

**Comment by ologbonowiwi** [comment]
Ok, I have a draft/skeleton to it

Here are the steps on top of my head to get it done:

- [x] Load a .rs file given a path
- [x] Add all structs to a HashMap, indexed by the struct name
- [ ] List all structs that map to [Operators](https://tailcall.run/docs/intro/operators/)
- [ ] Create GraphQL definitions given a struct
  - [ ] Create parser between rust type/graphql equivalent
  - [ ] Create "builder" to build the operator that matches with the struct (likely this will have manual strings, it'll not be a "one fits for all", and new operators can require new iterations over it)
  - [ ] [NEEDS-CLARIFICATION] Create the actual .graphql file
    - Where should we store this file?
    - How to trigger the file creation only at build time?
    - How the users will import this file into their IDEs?

**Comment by ologbonowiwi** [comment]
Some stuff that I'd appreciate your help with are the three questions of the message above (under the "Create the actual `.graphql` file" mark), and list all structs that map to [Operators](https://tailcall.run/docs/intro/operators/).

Would you mind give me the path to the structs that we'll need to map into the `.graphql` file?

**Comment by ologbonowiwi** [comment]
@tusharmath some stuff that I'd appreciate your help with are the three questions of the message above (under the "Create the actual `.graphql` file" mark), and list all structs that map to [Operators](https://tailcall.run/docs/intro/operators/).

Would you mind give me the path to the structs that we'll need to map into the `.graphql` file? I found `Http` under `config.rs` file but I'm not sure about the others.

I'll work in the rust->graphql parser (that'll parse the types) for now

**Comment by tusharmath** [comment]
@ologbonowiwi You will find most of them in config.rs for eg: `ModifyField` and also `InlineType`

>Where should we store this file?
Let's keep it in memory for now. We will write unit tests and test our codecs only in this PR.

> How to trigger the file creation only at build time?
Let's not put that in the scope of this PR. We will figure out how to generate and host the file separately.

> How the users will import this file into their IDEs?
Users can use a graphql config and import the files. Refer to https://the-guild.dev/graphql/config/docs/user/schema

**Comment by tusharmath** [comment]
We should implement it this way — 


```rust
use async_graphql_parser::types::service::DirectiveDefiniton;
#derive[DirectiveDefinition]
struct Http {
  path: String,
  method: Method
}

#[cfg(test)]
mod tests {
  #[test]
  fn test_http () {
    let actual = Http::directive_definition(); // DirectiveDefinition
    let expected = to_string(actual);
    assert_eq(actual, expected)
  }
}
```

- This is a grossly condensed implementation. the `directive_definition` function generates a DirectiveDefinition which is available in the `async_graphql` library. 
- We create a `ServiceDocument` from the `DirectiveDefinition`, which should be possible we do that in the project at couple of places.
- Then we print the `ServiceDocument` using the printer we have in `document::print`

**Comment by sujeetsr** [comment]
@ologbonowiwi I can help with this issue,  let me know if you have further questions after @tusharmath 's comment above.

**Comment by ologbonowiwi** [comment]
If you can split this into concret tasks I'd be more than happy to contribute on it @sujeetsr!

I don't have too much experience on the project so it's being quite a challenge. I want to work together on it but if you prefer to work alone go for it!

Don't forget to `/attempt #374` :smile:

**Comment by sujeetsr** [comment]
@ologbonowiwi I'll take a stab at splitting it into concrete tasks.

**Comment by sujeetsr** [comment]
@ologbonowiwi   Here are the tasks that you need to do:

1. Write a derive proc_macro that when applied to a  struct, implements a method named `directive_definition` that returns a  [DirectiveDefinition](https://github.com/async-graphql/async-graphql/blob/master/parser/src/types/service.rs#L184)  for that struct

For eg,
```rust
use async_graphql_parser::types::service::DirectiveDefiniton;
#derive[DirectiveDefinition]
struct Http {
  path: String,
  method: Method
}
```
generates a method on `Http` named `directive_definition`

Calling `Http::directive_definition()` will return a `DirectiveDefinition` for the `Http` struct

(ie a `DirectiveDefinition` with name `http`, `arguments` as the struct fields, `location` as Field, and other fields accordingly.)

2. Create a [ServiceDocument](https://github.com/async-graphql/async-graphql/blob/master/parser/src/types/service.rs#L11) with the above `DirectiveDefinition` 


3. Call [print](https://github.com/tailcallhq/tailcall/blob/main/src/document.rs#L213) with that `ServiceDocument` to print it. 

Steps 2 and 3 should be done in a test. We will figure out later how to combine all these outputs into a single graphql schema file that can be generated at build time.

Let me know if this clarifies things.

**Comment by sujeetsr** [comment]
@ologbonowiwi I'll work on this issue since it is higher priority for us.

**Comment by ologbonowiwi** [comment]
I created a draft on #406 with a simple directive definition (the only field set is the name). I'd likely take more time than you to fix it, but since it has high priority, you can go for it @sujeetsr.

**Comment by ologbonowiwi** [comment]
Hey folks, I see I'm starting to get somewhere. Can you take a look at #406 @sujeetsr @tusharmath?

I know this is a high-priority ticket, but I **really** want to help. If it's the best option, I'd happily split and work on it together.

**Comment by tusharmath** [comment]
Sure. How about we collaborate on discord? Its more realtime ☺️

**Comment by sujeetsr** [comment]
@ologbonowiwi can you implement the macro like I mentioned in my comment above listing out the steps to do? Your current PR will not work, since the method to generate the definition has to be created at build time by a macro, instead of separately writing it out for each directive, (which is the direction you're going in)
