### ISSUE TITLE
Support custom response headers

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#377]
### Description:

**Problem**
Currently, there's no mechanism to define custom response headers, restricting certain operational and security use-cases.

**Proposed Solution**
Introduce a `setHeaders` configuration:

```graphql
schema @server(http: {
  setHeaders: {
    "X-Custom-Header": "CustomValue",
    "Another-Header": "AnotherValue"
  }
}) {
  query: Query
  mutation: Mutation
}
```

**Additional Context**
Custom headers can aid in:
- Security enhancements (e.g., `Content-Security-Policy`).
- Operational information (e.g., `Server-Timing`).
- Handling CORS scenarios, by setting headers like `Access-Control-Allow-Origin`.

**Comment by tusharmath** [comment]
Yay!

**Comment by wrath-of-god** [comment]
@tusharmath could this be vec?
[{
    "X-Custom-Header": "CustomValue",
    "Another-Header": "AnotherValue"
}]
else it is problem?

**Comment by tusharmath** [comment]
We should use `KeyValues` to encode it @wrath-of-god. It would look like 

```graphql
[
  {key: "X-Custom-Header", value: "CustomValue"}
  {key: "Another-Header", value: "AnotherValue"}
]
```
