### ISSUE TITLE
dns resolution prefetch

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#379]
**Tech Requirements** 

```graphql
schema @server(http: {dns: {ttl: 1, prefect: true}}) {
  query: Query
  mutation: Mutation
}
```

Add a `dns` setting to allow the user to control them.

If prefetch is `true` the server should prefetch and resolve all the dns requirements by going thru the blueprint and identifying the endpoints.

**Comment by Kartik1397** [comment]
Hi @tusharmath, this feature seems interesting. I would like to work on this if possible.

**Comment by tusharmath** [comment]
@Kartik1397 Go for it!

**Comment by Kartik1397** [comment]
Hi @tusharmath,

What exactly `ttl` parameter will do? Can't we just rely on operating system's dns cache?

Does following example config looks good? (removed http and ttl from your example)
```
schema
  @server(port: 8000, queryValidation: false, dns: {prefetch: true})
  @upstream(baseURL: "http://jsonplaceholder.typicode.com") {
  query: Query
}
```

Here, tailcall will do dns lookup for baseURL provided in @upstream operator before starting the server.

Following operators have baseURL argument, so we can do dns-prefetch for these urls, are there any more places where we should check for urls?
```
@graphQL
@grpc
@http
@upstream (also proxy.url)
```
