### ISSUE TITLE
Drop `#![allow(clippy::too_many_arguments)]`

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#380]
**Problem**
There are functions where we are passing too many arguments and clippy exposes them to us as errors. We need to refactor those functions to make sure that we only pass the allowed number of arguments. Once the refactor is done, we remove the `too_many_arguments` directive.

**Solution**
There are various ways we can clean up the function signature:
1. **Use methods:** Convert functions to methods, that way the methods have context to a lot more information and you don't need to pass all of that information one by one as arguments.
2. **Reduce scope:** Create more specialized functions that don't require so many arguments and perform smaller operations. Compose these functions together higher up to perform the complete operation

**Additional Context:**

6 results - 6 files

- **src/endpoint.rs:**
  ```rust
  1: #![allow(clippy::too_many_arguments)]
  2  
  ```

- **src/main.rs:**
  ```rust
  1: #![allow(clippy::too_many_arguments)]
  2  
  ```

- **src/blueprint/from_config.rs:**
  ```rust
  1: #![allow(clippy::too_many_arguments)]
  2  
  ```

- **src/cli/tc.rs:**
  ```rust
  1: #![allow(clippy::too_many_arguments)]
  2  
  ```

- **src/config/from_document.rs:**
  ```rust
  1: #![allow(clippy::too_many_arguments)]
  2  
  ```

- **src/config/n_plus_one.rs:**
  ```rust
  3: pub fn n_plus_one(config: &Config) -> Vec<Vec<(String, String)>> {
  4:   #![allow(clippy::too_many_arguments)]
  5:   fn find_fan_out(
  ```

**Comment by yashwardhan-jyani** [comment]
is this what you had in mind?

Before - 
![Screenshot from 2023-09-30 13-51-59](https://github.com/tailcallhq/tailcall/assets/100014271/a14e593c-e843-4d91-8947-09359066dc79)

After - 
![Screenshot from 2023-09-30 13-52-16](https://github.com/tailcallhq/tailcall/assets/100014271/dcd47c64-1534-4097-95a2-a6361e09c2dc)

**Comment by tusharmath** [comment]
Nope. In this case the field has all the required args. We are unnecessarily passing them independently. We can simply pass the field directly.

**Comment by yashwardhan-jyani** [comment]
Can you provide an example?

**Comment by tusharmath** [comment]
for eg:In `to_object_type` you could pass type_definition directly instead of plucking each field and passing to it. The boolean option `is_interface` could be removed and set after calling `to_object_type`. Hope this helps! You will need to find innovative ways to reduce the functional arguments.
