### ISSUE TITLE
Support Running Project via WebAssembly (WASM) in the Browser

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#381]
**Problem**
Developers are required to download and install our product to test configurations and experience its features. This might deter potential users from trying out the product due to the initial setup overhead.

**Proposed Solution**
Convert our project to run in the browser using JavaScript, by compiling it to WebAssembly (WASM) and then interfacing with JS. This will serve as the foundation for future integrations, such as embedding it into a web-based playground.

**Additional Context**
By enabling our project to run in the browser through JavaScript:
- Final integration would be on https://tailcall.run/playground

**Comment by bharattech** [comment]
Hi Tushar @tusharmath ,

I am writing to express my interest in working on the Git issue with the number [381]

**Comment by ologbonowiwi** [comment]
This issue is to support WASM build only or it's needed to serve the solution under `/playground`?

**Comment by tusharmath** [comment]
In this issue we don't need to integrate it into the UI. We just need to build the ability to perform this operation.

**Comment by ologbonowiwi** [comment]
/attempt #381

Tokio doesn't support WASM, as seen on tokio-rs/tokio#1597. They're trying to use WebAssembly System Interface (WASI) over WASM.

Probably, this blocks the issue from a resolution, right @tusharmath?

**Comment by tusharmath** [comment]
@ologbonowiwi We might need to make it run using something like https://docs.rs/gloo-net/latest/gloo_net/

Basically move the http calls to the JS Realm.

**Comment by ologbonowiwi** [comment]
I can be wrong but [gloo_net](https://docs.rs/gloo-net/latest/gloo_net/) looks like a library to make requests than provide a server; likely we'll need to replace tokio packages (tokio itself and mio are the ones that I saw throwing compiling errors) by packages that run a server on WASM

**Comment by ologbonowiwi** [comment]
Can you describe the experience you expect to provide under the `/playground` route?

I am trying to understand here to see what options we have

**Comment by alexschrod** [comment]
I don't know if it's necessarily the solution, but a library like [MSW](https://mswjs.io/) lets you capture HTTP requests made by the browser and mock responses instead of letting them go through; maybe the same mechanism can be utilized here?

**Comment by tusharmath** [comment]
@ologbonowiwi If you checkout our [quick start guide](https://tailcall.run/docs/intro/quickstart/) you will see that one needs to install Tailcall locally to play around with it. This is a major impedance for people to try out the proxy server. 

We wanted an experience, where people can just run the server for their configuration within a few seconds on the browser itself. That way they will be able to get a feel of the software before installing anything locally.


**Actual Experience:**
- Use clicks on the playground link `/playground`, a window shows up where they enter their graphql configuration.
- Simultaneously we load a graphiql which points to this tailcal server, which is running on the browser.
- The graphiql allows the user to send graphql request to the tailcall wasm server running in the browser, however, the server makes real http calls upstream to orchestrate data from different sources and send back a graphql response.

We don't need to do all of that in this PR though. Our goal is to figure out a way to make sure that we can run the tailcall server on the browser and interact with it using JS. The UI and the UX around it like I explained above will be resolved later.

I hope this make sense.

**Comment by ologbonowiwi** [comment]
Yeah, it makes sense, @tusharmath.

This experience that you're describing it'd be incredible! But I think compiling to WASM is the cheapest way (saying in terms of infra) to provide this experience. Still, we have the trade-off that it'll require rewriting the core of tailcall to remove Tokio packages and find an I/O alternative compatible with WASM. 

Rather than do so, what if we run tailcall in an actual server and open a port to set it up a server via HTTP requests?

So when I go to the /playground, I upload (or paste) my graphql config, and this would POST https://tail-server.free-tier-somewhere.com/setup-server, and this would generate a https://tail-server.free-tier-somewhere.com/<uuid>/user-url-expectation where the graphql server it'll be up.

It's possible to achieve this by having a simple server with tailcall installed locally, and when a request comes, what the server does is run `tailcall <server-setup-command>`.

It likely provides an experience compatible with HTTP rather than the browser; it’d be more straightforward than removing all Tokio packages and finding WASM alternatives (when compiling to WASM).

Let me know if you see this as a nice way to provide the experience that you expect on /playground route.

**Comment by xmlking** [comment]
This could be a great feature to run BFF in the browser.  There will be always special need to run BFF in edge closer to users or  close to upstream data sources. 
 I saw some demos showcasing how to run SQLite in the browser via webassembly for local-first apps

**Comment by tusharmath** [comment]
@ologbonowiwi I think you have a point. May be we can create a `/playground-api` endpoint that:
- The UI could make a call to this endpoint and send a Query and Config together
- The server could evaluate the Config and respond with validation errors if any.
- If there are no errors, it could run the query against the provided `/playground-api` endpoint route. 
- The `/playground-api` endpoint doesn't need to be in `tailcall` instead a separate application which is only available for demo purposes. 
- Internally it would be a simple Rust based webserver that calls the Tailcall library functions to resolves it.


This is a rough sketch, but would run on the backend. I think it's a reasonable way to get a taste of the product without installing and from that point of view we should go ahead with it, let me know if you'd like to take a lead on spec-ing the finer details, happy to collab with you on this :)

The WASM bit opens many doors for us. Like what @xmlking said, running on the browser might be an interesting alternative for a lot of companies that don't want maintain GraphQL infrastructure. It would also open up doors for us to run it on — Mobile (Android, iOS, PWA), edge platforms such as Cloudflare Workers, Fermyon etc.

Strategically our goal is to support various WASM platforms as it could change the way you think about the product drastically, however, for this usecase may be we can simply deploy a dynamic server for Tailcall.
