### ISSUE TITLE
Implement `@unnest` on type in place of `@inline` on field

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#386]
**Problem**
The current inline operator has two issues —
1. It infers the type automatically, but requires the developer to specify some type for the field because of GraphQL's syntax requirements.
2. It can only be applied on existing fields and new fields can't be added.

**Proposal**
- Create an `unnest` operator that is applied to a type instead of a field. Unnest will create a new field. that resolves with the value at the provided path. 
- The type of the field will be using the same algorithm for inference that we were using for `inline`.

**Current**
```graphql
type U {
  b: A @inline(path: ["a","b"])
  c: A @inline(path: ["a","c"])
  d: A @inline(path: ["a","d"])
  e: String
}
```

**Proposed**
```graphql
type U 
  @unnest(name: "b", path: ["a", "b"])
  @unnest(name: "c", path: ["a", "c"])
  @unnest(name: "d", path: ["a", "d"]) {
  a: A
  e: String
}
```

**Comment by sujeetsr** [comment]
We decided to call the directrive `field` instead of `unnest`

**Comment by mainrs** [comment]
Since I'm currently working on refactoring from_config, this means that I can ignore the old @inline directive, am I right? I do need to add this new one though

**Comment by mainrs** [comment]
> > Since I'm currently working on refactoring from_config, this means that I can ignore the old @inline directive, am I right? I do need to add this new one though
> 
> I'm already working on adding a `addField` directive (which is what we decided to call `unnest`), there is a PR already. You can ignore `inline`. What refactoring are you doing to `from_config`?

Basically issue #384.
