### ISSUE TITLE
Headers should be case insensitive

### ISSUE THREAD

**Issue by ujjawal-khare-27** [tailcallhq/tailcall#387]
### Prerequisites

- [x] I have checked the existing issues to ensure this is not a duplicate.
- [x] I am running the latest version of Tailcall.

### Steps to reproduce

1. Pass header in http call as X-header
2. Check whether client receives x-header or X-header

... (add as many steps as needed)

### Expected behavior
1. Client should receive x-header instead of X-header

### Actual behavior
1. Client receive receive X-header

### Environment information:

- **Operating System**: (e.g., Ubuntu 20.04, macOS Big Sur, Windows 10)
- **Tailcall Version**: (e.g., v1.0.2)
- **Rust Version**: (e.g., `rustc 1.58.0`)
- **GraphQL Client/version** (e.g., `curl/8.1.2`)

### Additional context

Add any other context about the problem here, such as relevant logs, error messages, or stack traces.

### Logs

```
Paste any relevant logs here.
```

**Comment by tusharmath** [comment]
I think this should be alright since as per RFC 2616 headers are case-insensitive.
