### ISSUE TITLE
Re-order steps on CI

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#394]
**Problem**
Currently fmt and linting happens before building and running unit tests.

**Solution**
We should run the build first and make sure the code compiles, then run unit tests and in the end run clippy and fmt.

**Update 1**
Linting and Testing can be parallized and the developer can be informed about it independently.

**Comment by utsav00** [comment]
/attempt #394
I'll take this up, thank you

**Comment by alexschrod** [comment]
Seems kind of odd to want to spend all the time and energy on building and testing if a simple comma out of place is going to bring the whole CI step down at the end, but what do I know? 😅

**Comment by tusharmath** [comment]
Now I am having second thoughts about this LOL.

**Comment by Vishal-Sikka** [comment]
fmt and linting should happen first

**Comment by tusharmath** [comment]
I think we can do this in parallel also since they aren't related.

**Comment by tusharmath** [comment]
>Update 1
Linting and Testing can be parallized and the developer can be informed about it independently.

Based on the comments https://twitter.com/tusharmath/status/1708813317404520529
I think it's wise to do it in parallel.
