### ISSUE TITLE
Pass `operations` to `check` command

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#416]
**Problem**
As a user I wish to validate the generated graphql schema with a set of graphQL queries.

**Solution 1**
Since #438 we now support loading multiple graphQL files. Which means that we can pass the queries as a part of the configurations more easily. We should just validate the queries that are in the graphQL files without and special check parameter.

The command would look a lot simpler now:
```bash
tc check ./jsonplaceholder.graphql query1.graphql query2.graphql
```
All the above options should be allowed to test the graphQL schema against the provided queries and mutations. 

**Solution 2**
We will extend the check command on the CLI to support checking of the schema against provided queries and mutations:

```bash
# using operation parameter
tc check ./jsonplaceholder.graphql --operation query1.graphql --operation mutation1.graphql

# using comma as a delimiter
tc check ./jsonplaceholder.graphql --operation file1.graphql,file2.graphql

# using space as a delimeter
tc check ./jsonplaceholder.graphql --operation file1.graphql file2.graphql
```
All the above options should be allowed to test the graphQL schema against the provided queries and mutations.

**Technical Requirements**
- Use `ValidationError` to capture and display all the errors.
- Errors should be composed with errors `from_config`.

**Comment by b4s36t4** [comment]
@tusharmath can you explain a bit more on what you're thinking about validation? do we need to compare the the generated schema with the provided operations? or is there any existing implementation which can easily accepts graphql query to perform operation?

**Comment by tusharmath** [comment]
We need to check if the schema is compatible with an existing set of queries. Meaning - can I run those queries on the generated schema.

**Comment by ologbonowiwi** [comment]
One issue, though, is that the `Config::from_file_paths` does not load queries.

I've tried `query QueryName {`, `query {`, and only `{` (consider that the query would be on the following lines).
I'm seeing this error: 
![image](https://github.com/tailcallhq/tailcall/assets/100464352/502e9a30-552d-41b6-b6b0-07155a8d50c9)

Would you happen to have any suggestions on how to load queries @tusharmath?

Likely, we'll need to handle the queries differently than we do with the configs. Because of that, I recommend that we keep the initial idea of having a flag, but rather than `operations`, we could use `queries`, so the usage would be `tc check ./jsonplaceholder.graphql --queries query1.graphql query2.graphql`.

We can also add the handling on `Config::from_file_paths`, but I fear we'll overload this method. Please let me know what you think about this.

/attempt #416

**Comment by tusharmath** [comment]
@ologbonowiwi, Ah! I think this is problem with the parser unfortunately. We are just parsing the file here and validating it syntactically. Because it doesn't support queries right now, it would be better to just pass them as separate files, like it was in the original proposal. 

We should call it `operations` and not queries because operations includes both queries and mutations. 

I will revert the issue to it's previous state 🙈 

Thanks for pointing this out 🙏

**Comment by tusharmath** [comment]
Updated the issue with **Solution 1** and **Solution 2** :)

**Comment by ologbonowiwi** [comment]
Hey @tusharmath, I'm back to working on this one.

Where did you plan to parse the operations?

I was thinking about add
```rust
   let operations = Operation::from_file_paths(operations.iter()).await?;
```

and then find a way to check the operations against the configs.

Some questions:

- should I create an `operation.rs` to handle operations logic or do it under `config.rs`?
- where should we validate it? after, before the `display_details(&config, blueprint, &n_plus_one_queries, &schema)?;` call, or before the blueprint check?

**Comment by tusharmath** [comment]
`operations` could be part of `config::GraphQL {operations: Vec<Operation>}`, then we could perform a validation in the blueprint.

**Comment by ologbonowiwi** [comment]
Can you help me write tests for this issue, @tusharmath?

I'll start with the test, so it'll make easier to review and ensure the behavior

**Comment by ologbonowiwi** [comment]
I still think that it'd be easier to start this from teste, but after careful consideration, I'll not be able to handle this.

Anyone that wants to give it a shot, feel free to take up the bounty 🚀

**Comment by tobihans** [comment]
Hi 👋 @tusharmath. Can I give this a try ?

**Comment by tusharmath** [comment]
@tobihans Sure!

**Comment by tobihans** [comment]
I'm working on it @Shylock-Hg. Thanks

**Comment by ologbonowiwi** [comment]
Hey @tobihans, if you need help with it, let me know.

I added myself to the queue as I have looked at it in the past, and now I have availability now :smile:

PS: I'll not start to work on it as there are already other people working on it :smile:

**Comment by tobihans** [comment]
Thank you @ologbonowiwi. Yes, I've been working on it slowly 🐌. Currently, at the query parsing stage. Once I submit the draft, you'll be able to review and suggest. Thank you very much 😊.

**Comment by tusharmath** [comment]
That's cool @tobihans! Why don't you create a draft PR that @ologbonowiwi can help you with?

**Comment by tobihans** [comment]
Hi @tusharmath @ologbonowiwi, I just pushed the draft. I shifted from the original idea to parse the query after reading more about the `async_graphql` crate and looking into the codebase. The code is not that clean for now too, please bear with me. I'll fix it. Thanks
