### ISSUE TITLE
Bug: Invalid Configuration Error

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#417]
Given the following input 

1. Create the following `config.graphql` with a port that's not a number.
  ```graphql
  schema @server(port: "8000", baseURL: "http://jsonplaceholder.typicode.com") {
    query: Query
  }
  
  type Query {
    posts: [Post] @http(path: "/posts")
  }
  
  type Post {
    id: Int!
    userId: Int!
    title: String!
    body: String!
  }
  ```

2. Start the server using `tc start ./config.graphql` or `cargo run -- start ./config.graphql`

**Expectation**
A validation error should be shown for the value of the port.

**Actual**
```bash
Error: Invalid Configuration
Caused by:
  • No base URL defined [at Query.posts.@http]
```

**Comment by bharattech** [comment]
Hi @tusharmath 

it would be appropriate for me to continue in working on this issue?

**Comment by tusharmath** [comment]
You can collaborate with @amitksingh1490 i think he is looking at it.

**Comment by bharattech** [comment]
Hi @tusharmath @amitksingh1490 

Could you kindly review my code and provide your feedback?

**Comment by amitksingh1490** [comment]
@bharattech Do you wish to collaborate on this here 
https://github.com/tailcallhq/tailcall/pull/425

**Comment by bharattech** [comment]
Hi @amitksingh1490 
Yes, I'm open to collaboration. Can you please provide more details, How this works?
