### ISSUE TITLE
Have consistent names for CI Jobs

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#435]
Currently its uppercase, sometime lower-case sometime sentences etc. Make the job names consistent.

<img width="319" alt="Screenshot 2023-10-07 at 12 56 48 PM" src="https://github.com/tailcallhq/tailcall/assets/194482/c6be8537-9814-410c-a0cb-d838c018393c">

**Comment by ayewo** [comment]
@tusharmath What style would you like to adopt:
1. Initial capital;
2. all lower case;
3. Sentence Case;

**Comment by tusharmath** [comment]
Title case looks better IMO. Thanks for picking this up 🙏
