### ISSUE TITLE
Integrate CI for Running Benchmarks

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#436]
### Overview

We need to enhance our CI pipeline to not only run our existing Criterion benchmarks but also ensure that the build time stays within acceptable limits. Moreover, a clear and concise report should be generated and published on the PR for quick and easy understanding.

### Requirements

1. **Run Criterion Benchmarks:** Our CI should execute the existing Criterion benchmarks as part of the pipeline.
2. **Fail on Degradation:** The CI should fail if there's a performance degradation when compared to the `main` branch.
3. ~**Build Time Check:** The CI should compare the build time of the current PR with the average build time of the last few successful builds on the `main` branch. If the build time increases by more than 10%, the CI should fail.~
4. **Benchmark Report:** A tabular comparison of benchmarks should be published on the PR, similar to the code-cov report. It should display the current benchmark results alongside the results from the `main` branch for easy comparison.
5. **Conditional Execution:** Benchmarks and build time checks should only be executed when the `benchmark` label is added to a PR or commit.
6. **Support for Forks:** The CI process should be designed to run benchmarks on forks as well.

### Rationale

Performance is paramount for our project. It's essential to ensure that any changes do not adversely affect either the runtime performance (tracked by benchmarks) or the build time. By integrating these checks into our CI, we can maintain a high standard of performance and ensure that contributors receive immediate feedback on any potential issues.

**Comment by meskill** [comment]
Using Github Actions to measure performance could be quite unreliable due the way they are executing. That fact even mentioned in the [criterion's FAQ](https://bheisler.github.io/criterion.rs/book/faq.html#how-should-i-run-criterionrs-benchmarks-in-a-ci-pipeline)

**Comment by tusharmath** [comment]
Interesting @meskill. Have you used [iai]? It seems like it's not actively maintained.

[iai]: https://github.com/bheisler/iai

**Comment by meskill** [comment]
> Interesting @meskill. Have you used [iai](https://github.com/bheisler/iai)? It seems like it's not actively maintained.

I have only heard about this kind of benchmarking tools, but never used them. Indeed the project seems abandoned, but the [question](https://github.com/bheisler/iai/issues/37) has links to other projects that look more wealthy.

**Comment by tusharmath** [comment]
This seems like an alternative to iai: https://github.com/Joining7943/iai-callgrind

**Comment by tusharmath** [comment]
The approach that I have in mind is to use iai kinda tools to identify the following —

```bash
Instructions:                1733
  L1 Hits:                     2358
  L2 Hits:                        0
  RAM Hits:                       3
  Total read+write:            2361
  Estimated Cycles:            2463
```
Since these are exact values, whenever there is an increase in any of the parameters, we could fail the build.

**Comment by tusharmath** [comment]
@alankritdabral would you be taking the approach that I have described above using IAI?

**Comment by alankritdabral** [comment]
Yes i am taking the same approah @tusharmath

**Comment by tusharmath** [comment]
@alankritdabral As discussed on discord, we need both kind of benchmarks. They both signal orthogonal things. And it's possible that reduction in instructions still results in a performance regression.

**Comment by tusharmath** [comment]
fixed in #762

**Comment by epompeii** [comment]
@tusharmath I'm a little late to the party here, but down the road, if you want a more robust continuous benchmarking solution, you might consider checking out Bencher: https://github.com/bencherdev/bencher

**Comment by tusharmath** [comment]
> @tusharmath I'm a little late to the party here, but down the road, if you want a more robust continuous benchmarking solution, you might consider checking out Bencher: https://github.com/bencherdev/bencher

This is a nice tool. We are a small team so we take help from contributors to things done. Happy to add a bounty for integrating the tool into our ci.

**Comment by epompeii** [comment]
Thank you for the kind words! I would be more than happy to help with the integration. 😃
