### ISSUE TITLE
Implement Config Merge

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#440]
We should be able to merge more than one `Config` together to produce new configurations.

## Types of Conflicts
Merging GraphQL schemas can introduce a variety of conflicts. Here's a comprehensive list of potential conflicts:

1. **Type Name Conflicts**: Two schemas may have types with the same name but different fields or semantics.
   ```graphql
   # Schema A
   type User {
     id: ID!
     name: String!
   }

   # Schema B
   type User {
     userId: String!
     fullName: String!
     age: Int!
   }
   ```

2. **Field Name Conflicts**: Within a type, two schemas might have fields with the same name but different types or semantics.
   ```graphql
   # Schema A
   type Product {
     price: String!
   }

   # Schema B
   type Product {
     price: Float!
   }
   ```

3. **Directive Conflicts**: Different schemas might use the same directive name but with different implementations or semantics.

4. **Enum Value Conflicts**: Two schemas might define the same Enum type with different values or the same values but with different semantics.
   ```graphql
   # Schema A
   enum Color {
     RED
     BLUE
   }

   # Schema B
   enum Color {
     RED
     GREEN
   }
   ```

5. **Union and Interface Conflicts**: Conflicts can arise if two schemas define the same union or interface but with different member types.
   ```graphql
   # Schema A
   union SearchResult = User | Product

   # Schema B
   union SearchResult = User | Order
   ```

6. **Input Type Conflicts**: Two schemas might have input types with the same name but with different fields or field types.
   ```graphql
   # Schema A
   input UpdateUserInput {
     id: ID!
     name: String!
   }

   # Schema B
   input UpdateUserInput {
     userId: String!
     fullName: String!
   }
   ```

7. **Default Value Conflicts**: Different default values for the same field or argument in two schemas.

8. **Scalar Type Conflicts**: Two schemas might define a custom scalar with the same name but with different serialization or parsing logic.
   ```graphql
   # Schema A
   scalar Date

   # Schema B
   scalar Date
   ```

9. **Resolver Conflicts**: If the business logic (resolvers) for a particular type or field differs between two schemas.

10. **Argument Conflicts**: For a given field, two schemas might have arguments with the same name but different types or semantics.
    ```graphql
    # Schema A
    type Query {
      user(id: ID!): User
    }

    # Schema B
    type Query {
      user(username: String!): User
    }
    ```

11. **Description Conflicts**: Different descriptions for the same type, field, enum, etc., in two schemas.

12. **Deprecation Conflicts**: A field might be deprecated in one schema but not in the other.

13. **Directives on Different Locations**: A directive might be used on a valid location in one schema but an invalid location in another.

14. **Schema Definition Conflicts**: Differences in the root operation types (`query`, `mutation`, `subscription`) between schemas.

## Conflict Resolution

Here is a summary of possible ways to resolve graph conflicts:

| **Approach**      | **Resolution Methods**                                                                                       |
|-------------------|----------------------------------------------------------------------------------------------------------------|
| **Renaming**      | Rename conflicting types, fields, directives, enums, unions, inputs, scalars, or arguments.                    |
| **Merging**       | Combine fields, enum values, union members, input fields, resolver logic, descriptions, or root operations.    |
| **Exclusion**     | Omit conflicting types, fields, directives, enums, unions, inputs, scalars, arguments, or operations.          |
| **Overriding**    | Use one entity's default, resolver, description, or deprecation over another.                                  |
| **Resolvers**     | Employ custom resolvers for merging or decision-making.                                                       |
| **Modification**  | Adjust directive locations or handle default values in resolvers.                                              |
| **New Elements**  | Introduce new custom directives.                                                                              |
| **Union Creation**| Form new union types for conflicting fields.                                                                   |

## Technical Requirements
Implement a `merge` method on Config:

```rust
fn merge(mut self: Config, other: Config) -> Result<Config, ValidationError<String> {
  // ... implement this function
} 
```
- Merge should happen where other overwrites self.
- Incase of a conflict a `ValidationError` should be returned.
- Use the following algorithm to merge:
    **Server**
    This is going to be a deep merge of json values:
    - Add missing in configurations in self from other.
    - Keep configs in self that are missing in other.
    - In case of conflict use the one on the other.
    
    **Type**
    - Add new types in self from other.
    - Incase a type exists in both self and other, create a Least Upper Bound with the same name.
    
    **Input**
    - Add new types from Right into Left.
    - Incase an input type exists in both Left and Right, create the Greatest Lower Bound with the same name. 
    
    **Field**
    - Perform a best effort merge.
    - Ensure inputs and outputs can be merged, if not fail with a validation error.
  
- Unit tests should written using only .graphQL files.

**Comment by Yougigun** [comment]
Hi @tusharmath 
I am still trying to figure out the structure of Config!
I have some questions. 
1. could you elaborate on the least upper bound and greatest lower bound?
2. I found the [Server](https://github.com/tailcallhq/tailcall/blob/main/src/config/server.rs#L10C14-L10C14), [Type](https://github.com/tailcallhq/tailcall/blob/main/src/config/config.rs#L112]) and [Filed](https://github.com/tailcallhq/tailcall/blob/main/src/config/config.rs#L152). but I need to figure out what input is in the context.
3. Ensure inputs and outputs can be merged << does it mean the filed in [HTTP type](https://github.com/tailcallhq/tailcall/blob/458716df62eacd670e8ccd20f9c10160ff752bc4/src/config/config.rs#L247-L248)?
4. Can you provide examples of .graphql files and the expected merged result?

Thanks in advance

**Comment by tusharmath** [comment]
@Yougigun Sure!

The idea of LUB (Least Upper Bound) is a bit like finding a common ancestor that is as close as possible to the things you are considering, in a hierarchy of types. For eg:

1. **Animal Hierarchy**:
    - `Animal`: The most general type.
        - `Mammal`: A subtype of `Animal`.
        - `Bird`: Another subtype of `Animal`.
            - `Penguin`: A subtype of `Bird`.
            - `Sparrow`: Another subtype of `Bird`.
        - `Reptile`: Another subtype of `Animal`.

2. **Finding the LUB**:
    - If you have a `Penguin` and a `Sparrow`, their LUB would be `Bird` since that's the closest common ancestor type.
    - If you have a `Mammal` and a `Bird`, their LUB would be `Animal` since they don't share a closer common ancestor.
    - If you have a `Mammal` and a `Reptile`, again their LUB would be `Animal`.

3. **Finding the GLB**:
    - If you have a `Penguin` and a `Sparrow`, their GLB would be more specific than `Bird`, but since there isn't a more specific common subtype, the GLB is undefined in this case.
    - If you have a `Mammal` and an `Animal`, their GLB would be `Mammal` since `Mammal` is the most specific type that is a subtype of both `Mammal` and `Animal`.
    - If you have a `Bird` and an `Animal`, their GLB would be `Bird`.

In GraphQL terms we can find LUB as follows 

```graphql
# Config 1
type Foo {
  a: String
  b: Int
}


# Config 2
type Foo {
  b: Int!
  c: Boolean
}

# GLB
type Foo {
  a: String
  b: Int
  c: Boolean
}

# LUB
type Foo {
  a: String
  b: Int
  c: Boolean
}

# GLB

type Foo {
  a: String
  b: Int!
  c: Boolean
}
```

In general LUB of two types can be considered as a union of two types and GLB is the moral equivalent of an intersection.

**Comment by tusharmath** [comment]
> could you elaborate on the least upper bound and greatest lower bound?

Explained above

> I found the [Server](https://github.com/tailcallhq/tailcall/blob/main/src/config/server.rs#L10C14-L10C14), [Type](https://github.com/tailcallhq/tailcall/blob/main/src/config/config.rs#L112%5D) and [Filed](https://github.com/tailcallhq/tailcall/blob/main/src/config/config.rs#L152). but I need to figure out what Input is in the context.

Input is just a field that's set to `true` in type. Structurally they are similar to types.

> Ensure inputs and outputs can be merged << does it mean the filed in [HTTP type](https://github.com/tailcallhq/tailcall/blob/458716df62eacd670e8ccd20f9c10160ff752bc4/src/config/config.rs#L247-L248)?
Can you provide examples of .graphql files and the expected merged result?

Take a look at the above examples of merged graphql types. Let me know if it's still not clear of if there are edge case that haven't been covered.

**Comment by Yougigun** [comment]
@tusharmath Thanks for your kind explanation! 

> Input is just a field that's set to `true` in type. Structurally they are similar to types.
I am guessing what you said is like `interface`, `scalar`..etc. Those reuse Type struc with similar structures. 
But, I don't see `input` filed in the Type that can be set to true.
https://github.com/tailcallhq/tailcall/blob/main/src/config/config.rs#L112-L123

**Comment by tusharmath** [comment]
My bad, i think based on where the type is used we infer that as input or
output. There was a field earlier for input but we realised this
information can be inferred.

**Comment by tusharmath** [comment]
@Yougigun I think this issue needs a lot more fleshing out before we get started. I am removing the bounty for now. I have updated the main issue with more details about the scope of the conflict resolution one might need to think about.

**Comment by Yougigun** [comment]
@tusharmath  I was thinking of listing all types like interface, scalar,...etc. to discuss how to handle them when conflicting. Also, a certain type may need to consider conflict in different situations. For example, interface type , A impl B interface in original config but C impl B'(same name with B) in other config.  the fields of interface are different and may cause both(A and C) impl fail in either LUB or GLB of B interface merge.

Glad to see that you'd like to flesh out the details before starting.

**Comment by Yougigun** [comment]
> @Yougigun I think this issue needs a lot more fleshing out before we get started. I am removing the bounty for now. I have updated the main issue with more details about the scope of the conflict resolution one might need to think about.

no problem. when I was thinking of it. I feel I also have to list all the types of conflict situations to discuss before starting.

**Comment by tusharmath** [comment]
Merge has been implemented for now. We can write more intelligent merges as a separate project.
