### ISSUE TITLE
Load Config via HTTP

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#441]
Currently Tailcall server can load on configurations that are on the file system. We would like to load these configurations over HTTP. This will allow the server to update automatically without performing restarts on production.

**Technical Requirements**
- `tc start` should also take http endpoints as inputs.
- Update cli documentation to depict that it supports both file and http paths.
- Incase of load failure error should be shown on the console
  **Refresh Mechanism:** Implement a refresh mechanism to check for updates to the configuration file at a defined interval.
    - The refresh interval should be configurable, with a reasonable default value (e.g., 5 minutes).
    - An additional feature could be to implement a smart refresh mechanism which would use HTTP headers like ETag or Last-Modified to determine if the configuration has changed and only download the new configuration if there's a change. This can be done via http_client as it supports http caching as per RFC.

**Additional Note**
- Http url hosting the configuration could expose data in any of the formats - YML, JSON, GraphQL, and we should support all. refer to #439 for more details.

PS: Make sure you update documentation on https://tailcall.run/docs 

**Design**
- Write config reading logic to a `config::read::ConfigReader` module.
- Module should be responsible for reading the file from http and disk.
- Module should have support to reload config via poll
- Should expose an API that gives access to current configuration without any async
- Add unit tests.

**Comment by wrath-of-god** [comment]
Is this open for try @tusharmath / @neo773 ?

**Comment by neo773** [comment]
@wrath-of-god 
Hi there, I have a working PR at https://github.com/tailcallhq/tailcall/pull/499
I'm working on the changes requested by tushar

**Comment by tusharmath** [comment]
@wrath-of-god We encourage every one to try :) but it's hard to compete with @neo773 🙏

**Comment by ssddOnTop** [comment]
I think #499 has done a great job, only a few changes are needed, I think I can add the schema part

**Comment by ssddOnTop** [comment]
> I think #499 has done a great job, only a few changes are needed, I think I can add the schema part

@tusharmath can you assign the task to me?

**Comment by tusharmath** [comment]
@ssddOnTop Going forward we will only allow one person to an issue. Let me confirm with @neo773 

@neo773 can you confirm that you are not working on this anymore?

**Comment by neo773** [comment]
@ssddOnTop 
Are you open to splitting the bounty if you add the changes to #499?

cc @tusharmath

**Comment by ssddOnTop** [comment]
> @ssddOnTop Are you open to splitting the bounty if you add the changes to #499?
> 
> cc @tusharmath

@neo773 I'd have to use your existing code then, looks like I can do that

**Comment by neo773** [comment]
> > @ssddOnTop Are you open to splitting the bounty if you add the changes to #499?
> > cc @tusharmath
> 
> @neo773 I'd have to use your existing code then, looks like I can do that for 50-50

Works for me.
