### ISSUE TITLE
Optimize CI/CD Pipeline to Skip builds & Deploy on Irrelevant Changes

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcall#443]
**Issue**:
Our CI/CD pipeline currently triggers builds and deployments for every code change, including when there are no changes in core application files (e.g., `.rs`, `cargo.toml`, `cargo.lock`, `fly.toml`, `DockerFile`) or when only test files are modified.

**Expected Behavior**:
The pipeline should:
1. Identify and act based on the nature of code changes.
2. Trigger builds and deployments only when changes can potentially alter the binary/artifact.

**Comment by Yougigun** [comment]
I'd like to give it a shot.

**Comment by Yougigun** [comment]
@amitksingh1490 
done. please help review and test!
https://github.com/tailcallhq/tailcall/pull/454
