### ISSUE TITLE
Add validation of templates in schema at parsing stage

### ISSUE THREAD

**Issue by meskill** [tailcallhq/tailcall#449]
**Is your feature request related to a problem? Please describe.**
Improper usage of templates in schema will lead to empty value resolved that is hard to debug properly.

**Describe the solution you'd like**
Add validation for the usage of templates i.e. that only acceptable range of keys is used (value, vars, headers) and there is at least one property access (`value.a`, `headers.test-header`)

**Comment by tusharmath** [comment]
@meskill I think this was a problem while using parameters in the route of a url. We fixed it s now you will get an error if you use a path that's optional. Let me know if there is any other case that we should be covering?
