### ISSUE TITLE
Broken enableCacheControlHeader Feature

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#459]
Cache control header is supposed to be inferred from the received HTTP responses within a GraphQLRequestContext.
The current implementation is logically incorrect and lacks test. 

**Technical Requirement**
- Cache Information could be stored within RequestContext
- Minimum TTL could be evaluated from RequestContext and then set in header.

**Comment by sujeetsr** [comment]
The current implementation of DataLoader is global, so currently it picks the minimum ttl of the http response across graphql requests, and sets it in cache control header. This is incorrect, the ttl should be per graphql request.
