### ISSUE TITLE
Support GraphQL DataSource

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#461]
Moving the [discussion](https://github.com/tailcallhq/tailcall/discussions/460?converting=1) into an issue:

**Problem Statement**
Tailcall needs a primitive to connect and query other GraphQL services.

**Proposal**
_users.localhost:8001_

```graphql
schema @server(port: 8000, baseURL: "https://jsonplaceholder.typicode.com") {
  query: Query
}

type Query {
  users: [User] @http(path: "/users")
  user(id: Int): [User] @http(path: "/users/{{args.id}}")
}
```

_posts.localhost:8001_

```graphql
schema @server(port: 8001, baseURL: "https://jsonplaceholder.typicode.com") {
  query: Query
}

type Query {
  posts: [Post] @http(path: "/posts")
  post(id: Int): [User] @http(path: "/posts/{{args.id}}")
}
```

**compose:9000**

```graphql
schema 
  @server(port:9000) 
  @graphQLSchema(url: "https://posts.localhost:8001/graphql", name: "posts")
  @graphQLSchema(url: "https://users.localhost:8001/graphql", name: "users") {
  query: Query
}

type Query {
  users: Json @graphQL(query: {users: {}}, schema: "users")
  user(id: Int): Json  @graphQL(query: {user: {id: "{{args.id}}"}}, schema: "users")
  posts: Json @graphQL(query: {posts: {}}, schema: "posts")
  post(id: Int): Json @graphQL(query: {post: {id: "{{args.id}}"}}, schema: "post")
}

extend type Post {
  user: Json @graphQL(query: {user: {id: "{{value.id}}"}}, schema: "users")
}
```

New annotations have to be added (names are open for feedback).
- `@graphQL`: Works like `@http` but connects and queries GraphQL services. The content inside of `query` is just a JSON representation of a GraphQL query. Eg:
  ```graphql
  # Actual GraphQL Query
  query foo(a: 1, b: true, c: "Hello") { x y z }
  
  # Json Repr
  {query: {a: 1, b: true, c: "Hello"}}
  ```
  We don't need to specify the field selection set for the query since that's decided by the actual GraphQL query.
- `@graphQLSchema`: This stores the potential graphQL schemas that we could like to compose.
- `Json` type is used as a scalar while defining the configuration. However once the client-sdl is created, Json is replaced with the correct concrete types.

**Comment by sujeetsr** [comment]
Questions:
- Would this composed spec be created in an automated way, when the subgraphs are added? (like Apollo Rover does)?
- Would the composition logic rely on types and field names to figure out relationships? ie if `Post` contains a `userId`, then its the `id` of a `User` ? 
- How do we handle relationships that don't follow the above convention? (Both Apollo and Fusion have additional annotations for this)
- There are multiple "standards" for composition - [Apollo Federation](https://www.apollographql.com/docs/federation/subgraph-spec/), [Open Federation](https://spec.open-federation.org/draft#), and [GraphQL Fusion](https://chillicream.com/blog/2023/08/15/graphql-fusion) (which seems to be a superset of Open Federation, ie it can compose REST, gRPC, too), but only Apollo has something complete. The others are very much wip. Do we create our own composition directives, or follow one of these?
