### ISSUE TITLE
Merge `@groupBy` and `@http`

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#463]
Currently `groupBy` operator is used for batching and only supports Http. Even the implementation currently is very http specific. We can merge them.

**Before:**
```graphql
type Post {
  id: Int!
  userId: Int!
  title: String!
  body: String!
  user: User @http(path: "/users", query: [{key: "id", value: "{{value.userId}}"}]) @groupBy(key: "id", path: ["id"])
}
```

**After:**
```graphql
type Post {
  id: Int!
  userId: Int!
  title: String!
  body: String!
  user: User 
    @http(
      path: "/users", query: [{key: "id", value: "{{value.userId}}"}],
      batch: {
        groupByPath: ["id"], 
        selectKey: "id"
      }
    )
}
```

**IMPORTANT:**
Update the documentation on https://github.com/tailcallhq/tailcallhq.github.io

**Comment by tobihans** [comment]
Hi @tusharmath, I'd like to work on this. So that I can understand more tailcall's codebase.
Do you mind assigning me, please ?

**Comment by tusharmath** [comment]
@tobihans Fantastic! Let us know on the discord channel, if you get stuck or need any kind of help understanding some bits.

**Comment by tobihans** [comment]
I will, thank you !
