### ISSUE TITLE
Move server start processing to separate function

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcall#464]
```rust
  let config = Config::from_sdl(&server_sdl)?;
  let port = config.port();
  let server = config.server.clone();
  let blueprint = Blueprint::try_from(&config).map_err(CLIError::from)?;
  let state = Arc::new(ServerContext::new(blueprint, server));
  ```
  This processing should be moved to common fn and should also be used in `test_execution` spec in `graphql_spec.rs`

**Comment by tusharmath** [comment]
@amitksingh1490 Can you expand a little bit more on what's required from this issue?

**Comment by amitksingh1490** [comment]
Hi @ologbonowiwi, Yes we have to duplicate this logic in tests, Ideally that should be reused.

**Comment by tusharmath** [comment]
Closing this one as we don't need to start the server for any tests any more.
