### ISSUE TITLE
Add server side integration tests

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcall#466]
**Technical Requirements**
- Run various tests where an actual server is started using different configurations.
- Send real graphQL requests and expect real graphQL responses.
- The query to the server and the expected responses should be saved in .graphQL files.

**Comment by melsonic** [comment]
I am still working on this one

**Comment by Min2who** [comment]
can you assign me this issue @tusharmath @amitksingh1490

**Comment by tusharmath** [comment]
@Min2who We opened up another issue in place of this one — #576. This is a much larger and IMO, a much cleaner way to test our application. 

@amitksingh1490 is working on it. I think I will close this one for now. Feel free to connect with him if you are interested :)
