### ISSUE TITLE
Deploy ci step should be done only on release

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcall#490]
Deploy CI step runs on every main merge, but it should only happen once per release when the release is published

**Comment by Pranav2612000** [comment]
I'll like to work on this issue @amitksingh1490 
If I understand correctly, we want [this](https://github.com/tailcallhq/tailcall/blob/2f999f15b745e0884d3ffc8e2465bda60dd57a79/.github/workflows/ci.yml#L91) workflow to run only on release, which at the moment runs on every push to `main`.

I was thinking of making it run on every release only by [this](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release) approach. Does that look good?

**Comment by amitksingh1490** [comment]
@Pranav2612000  yes, you are correct, please go ahead
