### ISSUE TITLE
CI: Windows support

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcall#498]
Add support for windows all cpu architectures in release step of CI

**Comment by Apoorv012** [comment]
How is this a good first issue?

**Comment by tusharmath** [comment]
Because even chat gpt can do it 😂

**Comment by Apoorv012** [comment]
Thank you for the response! I appreciate the humor, but I'd like to understand the specifics of the issue a bit better. Could you please provide more details or guidance on how to approach and solve this 'good first issue'? This would be very helpful for someone like me who's looking to contribute and learn more about the project.

**Comment by tusharmath** [comment]
@Apoorv012 You can have a look at how SWC does this on the CI https://github.com/swc-project/swc/blob/main/.github/workflows/CI.yml

It isn't very different than supporting other platforms. Initial googling will lead you to — https://stackoverflow.com/questions/31492799/cross-compile-a-rust-application-from-linux-to-windows which describes how to build an exe from linux.

**Comment by Apoorv012** [comment]
Ok, I will begin work on this issue.

**Comment by meskill** [comment]
> @Apoorv012 You can have a look at how SWC does this on the CI https://github.com/swc-project/swc/blob/main/.github/workflows/CI.yml
> 
> It isn't very different than supporting other platforms. Initial googling will lead you to — https://stackoverflow.com/questions/31492799/cross-compile-a-rust-application-from-linux-to-windows which describes how to build an exe from linux.

actually we doesn't even need to do cross compilation in this case as we can run ci workflow on windows vm with `runs-on` option in github actions. It should be simpler as it doesn't require installation for build tools in linux. Just make sure to build it both for 32 and 64bit architecture

**Comment by Dhanus3133** [comment]
Kindly assign this issue to me. I would like to attempt.

**Comment by tusharmath** [comment]
fixed in #580

**Comment by s-vamshi** [comment]
Hey @Dhanus3133, did you receive bounty and were you able to use it?
I am also from India but I see that stripe doesn't allow payment outside india so just wanted to confirm.

**Comment by Dhanus3133** [comment]
Yes @s-vamshi. Follow the steps shown in [Algora Earnings](https://console.algora.io/user/payouts).

**Comment by s-vamshi** [comment]
Thanks for the link, I have setup stripe in through earnings page, did you have any sole proprietorship/company in India to get credited the bounty money?

**Comment by s-vamshi** [comment]
Sorry to bother you @Dhanus3133 because when I contacted Algora, they told that sole proprietorship is necessary so reconfirming with you😅

**Comment by Dhanus3133** [comment]
@s-vamshi DM on discord `@dhanus`

**Comment by s-vamshi** [comment]
@Dhanus3133 I am not able to find you in discord can you please use my username _Vamshi#7540_

**Comment by ologbonowiwi** [comment]
@s-vamshi you can setup a wise.com account and ask the alvora folks to transfer it to you. 

I live in Brazil and Stripe does not work here, they always pay me via wise and I never had issues so far

**Comment by s-vamshi** [comment]
@ologbonowiwi Indian's can receive payments from other countries using wise as well😅.
Do you have any idea if [Buy me a cofee](https://www.buymeacoffee.com/?source=fba1&utm_source=FriendlyGAd&utm_medium=BmcAdSearch&utm_campaign=April2020&gclid=EAIaIQobChMIps_3vOi-ggMVGxB7Bx0Veg1zEAAYASAAEgJ8z_D_BwE) works?
