### ISSUE TITLE
Issue Pulling Docker Image

### ISSUE THREAD

**Issue by neo773** [tailcallhq/tailcall#502]
https://tailcall.run/docs/guides/installation/#docker

<img width="682" alt="Screenshot 2023-10-17 at 4 27 37 PM" src="https://github.com/tailcallhq/tailcall/assets/62795688/8fd5ce85-e0bb-4ee4-8628-1107a9241505">

**Additional Information**

Use GCR: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

**Comment by ayewo** [comment]
@rishi-raj-jain I'm sorry I couldn't resist working on this after waiting for 6+ hours[^1] for you to submit a PR 🙂

/attempt #502

[^1]: github.com/tailcallhq/tailcallhq.github.io/issues/20#issuecomment-1766102378
