### ISSUE TITLE
Validate blueprint component in using `validate_or`

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#503]
We are using `?` operator to get each component of `Blueprint { schema, definitions, server, upstream }`.

This exits with the first error that's produced. Instead we should use `validate_or` to validate all of them independently and then combine the result to produce the Blueprint.

**Tech Requirements**
- Add unit tests to make sure all errors a captured an combined together.

**Comment by tusharmath** [comment]
fixed in https://github.com/tailcallhq/tailcall/commit/56d33b3bf9dd709f376906dad305eed08fbb18a2

**Comment by algora-pbc** [comment]
🎉🎈 @ShashwatAgrawal20 has been awarded **$25** by **Tailcall Inc.**! 🎈🎊
