### ISSUE TITLE
Make client decoupled with server

### ISSUE THREAD

**Issue by Yougigun** [tailcallhq/tailcall#504]
try to move a upstream-related fields from server to upstream. And make the client only depends on upstream config. 

Original Ref:
              I tried to remove the server field from RequestContext. But there are some values needed in the Server.
e.g. 
https://github.com/tailcallhq/tailcall/blob/8ed004cab159593137dbd949a0916444c4a1a6cd/src/lambda/expression.rs#L137
https://github.com/tailcallhq/tailcall/blob/8ed004cab159593137dbd949a0916444c4a1a6cd/src/lambda/evaluation_context.rs#L61...

_Originally posted by @Yougigun in https://github.com/tailcallhq/tailcall/pull/479#discussion_r1360583662_

**Comment by tusharmath** [comment]
fixed in #479
