### ISSUE TITLE
Trigger lint via from CI

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#505]
- We should be able to **auto fix** the PR by running the `./lint` command. 
- This should only happen if a `ci:lint` label is added. 
- Once fixed, the new changes should be pushed. 
- This should happen independent to other builds.

**Comment by adithyaakrishna** [comment]
@tusharmath How abt we add husky and lint-staged commands to do the lining on the contributor's side only? We can use pre-commit hooks 👀

**Comment by tusharmath** [comment]
@adithyaakrishna was closed by #507

**Comment by ayewo** [comment]
@neo773 looks like you forgot to add your `/attempt #issue` so that @algora-pbc can sync up your `/claim #issue` before triggering the automated payout.

(Talk about good ol' fashioned two-phase commit 😁).

**Comment by tusharmath** [comment]
@adithyaakrishna I am not a fan of pre-commit hooks. You can always by pass them and otherwise they just slowdown the CLI experience.
