### ISSUE TITLE
Doc: Design a comprehensive logging specification

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#524]
**Description:**

Logging is something that currently is quite basic. We need to improve the logging experience following some convention and open standards. We need it to be configurable and flexible. It should be able to work with spans and provide time duration of upstream request. The level of granularity in terms of tracing should also be configurable. Some inspiration can be taken from proxies such as Nginx, HaProxy, Envoy etc.

**Objective:**

Develop a design and architecture for the above requirements and create a Pull Request (PR) on GitHub, submitting the proposal in the `doc/` folder, using the `.md` (Markdown) file format.

**Acceptance Criteria:**

To improve the likelihood of your PR being merged, ensure your proposal emphasizes:

1. **Clarity:** The design should be easy to understand and well-documented.
2. **Feasibility:** The proposed solution should be practical to implement.
3. **Maintainability:** The design should be easy to maintain and adapt in the future.
4. **Efficacy:** How effectively the proposed design addresses the problem at hand.

**IMPORTANT:** You just need to create documentation about the approach and not actually implement the approach.

**Comment by ayusham001** [comment]
@tusharmath I would love to work on it
Can you please assign it to me?

**Comment by tusharmath** [comment]
@ayusham001 We will allow multiple proposals for this one, so keeping it open if anyone else want's to give it a shot.
