### ISSUE TITLE
Doc: Create a specification for support GRPC

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#525]
**Description:**

Create a specification to support GRPC protocol on Tailcall. Take inspiration from existing @http directives.

**Objective:**

Develop a design and architecture for the above requirements and create a Pull Request (PR) on GitHub, submitting the proposal in the `doc/` folder, using the `.md` (Markdown) file format.

**Acceptance Criteria:**

To improve the likelihood of your PR being merged, ensure your proposal emphasizes:

1. **Completeness:** The design should have enough details about how the feature should be implemented. Components affected, library used etc.
1. **Clarity:** The design should be easy to understand and well-documented.
2. **Feasibility:** The proposed solution should be practical to implement.
3. **Maintainability:** The design should be easy to maintain and adapt in the future.
4. **Efficacy:** How effectively the proposed design addresses the problem at hand.

**IMPORTANT:** You just need to create documentation about the approach and not actually implement the approach.

**Comment by anshumanjaiswal** [comment]
Hi @tusharmath, is this bounty up for attempt?

**Comment by tusharmath** [comment]
Creating bounty for specs was unfortunately a failed experiment.
