### ISSUE TITLE
Bug: Batching doesn't work in certain cases

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#529]
**Steps**

Consider the following Server configuration:

```graphql
schema
  @server(port: 8000, enableGraphiql: "/graphiql")
  @upstream(baseURL: "http://jsonplaceholder.typicode.com", enableHttpCache: true, batch: {delay: 5000}) {
  query: Query
}

type Query {
  user(id: Int): User @http(path: "/users", query: [{key: "id", value: "{{args.id}}"}]) @groupBy
}

type User {
  id: Int!
  name: String
}
```

With the following GraphQL query 

```graphql
{
  user1:user(id: 1) {
    name
  }
  
  user2:user(id: 2) {
    name
  }
}
```

**Observeration**
```
[2023-10-22T10:31:47Z INFO  tailcall::http::server] 🚀 Tailcall launched at [127.0.0.1:8000]
[2023-10-22T10:31:47Z INFO  tailcall::http::server] 🌍 Playground: http://127.0.0.1:8000/graphiql
[2023-10-22T10:31:54Z INFO  tailcall::http::client] GET http://jsonplaceholder.typicode.com/users?id=1 
[2023-10-22T10:32:00Z INFO  tailcall::http::client] GET http://jsonplaceholder.typicode.com/users?id=2 
```

- Two separate requests are made one after the other.
- Each request is made after 5000ms, effectively responding in 10 seconds.

**Expected**
- Only one batched request should be made in 5 seconds.

**Comment by sujeetsr** [comment]
Some more context: 
The following test *does* work, so the bug doesn't seem to be in the implementation of `groupBy` logic in data_loader.rs.

```rust
#[tokio::test]
async fn test_group_by() {
    let client = MockHttpClient { request_count: Arc::new(AtomicUsize::new(0)) };

    let loader = HttpDataLoader { client: client.clone(), batched: Some(GroupBy::default()) };
    let loader = loader.to_data_loader(Batch::default().delay(1));

    let request1 = reqwest::Request::new(reqwest::Method::GET, "http://example.com/users?id=1".parse().unwrap());
    let request2 = reqwest::Request::new(reqwest::Method::GET, "http://example.com/users?id=2".parse().unwrap());
    let key1 = DataLoaderRequest::new(request1, BTreeSet::new());
    let key2 = DataLoaderRequest::new(request2, BTreeSet::new());
    let future1 = loader.load_one(key1);
    let future2 = loader.load_one(key2);
    let _ = join_all([future1, future2]).await;
    assert_eq!(
      client.request_count.load(Ordering::SeqCst),
      1,
      "Only 1 request should be made for group by"
    );
}
```

When the query mentioned in the issue is run however, dataloader's `load` method is called twice, once with each key, instead of being called once

**Comment by git-bruh** [comment]
@sujeetsr This seems to be because the logic in `lambda/expression.rs` https://github.com/tailcallhq/tailcall/blob/ec41cdfafe0f99b47cccec951661b2d63344486a/src/lambda/expression.rs#L116-L128 calls `load_one`, `await`'s the result and returns the result body, rather than "queueing" all known requests, collecting the futures and then joining them once the grouping has been done internally (howsoever that happens, haven't looked through all the abstractions yet)

So this is more of a refactoring issue than a bug, it works fine in the test since we call `load_one` individually in tests, but in actual usage of the API, that is not the case

**Comment by sujeetsr** [comment]
@git-bruh the `load_one` method is from `async_graphql::dataloader::DataLoader` and it internally calls the `load` method in `data_loader.rs` with multiple keys by queuing the calls to `load_one`. 
https://async-graphql.github.io/async-graphql/en/dataloader.html#dataloader

**Comment by mrkirthi-24** [comment]
sujeetsr I just need some. Can i give it a try??

**Comment by sujeetsr** [comment]
This is a bug in `async-graphql`, this PR should fix it:
https://github.com/async-graphql/async-graphql/pull/1405/files

**Comment by tusharmath** [comment]
It appears that there is a bug in the graphQL library we are using, the fix has been proposed in https://github.com/async-graphql/async-graphql/pull/1405

Removing bounty on this right now.

**Comment by tusharmath** [comment]
This was fixed in async-graphql.
