### ISSUE TITLE
GITHUB STARS not updating on website

### ISSUE THREAD

**Issue by mrkirthi-24** [tailcallhq/tailcall#535]
### Prerequisites

- [ ] I have checked the existing issues to ensure this is not a duplicate.
- [ ] I am running the latest version of Tailcall.

### Steps to reproduce

1.
2.
3. ... (add as many steps as needed)

### Expected behavior

A description of what you expected to happen.

### Actual behavior

A description of what actually happened.

### Environment information:

- **Operating System**: (e.g., Ubuntu 20.04, macOS Big Sur, Windows 10)
- **Tailcall Version**: (e.g., v1.0.2)
- **Rust Version**: (e.g., `rustc 1.58.0`)
- **GraphQL Client/version** (e.g., `curl/8.1.2`)

### Additional context

Add any other context about the problem here, such as relevant logs, error messages, or stack traces.

### Logs

```
Paste any relevant logs here.
```

**Comment by mayant15** [comment]
Seems to work for me, just takes a while. I'm on Firefox 118.0.2 on Mac.

**Comment by tusharmath** [comment]
It's updating for me too.
