### ISSUE TITLE
Code structure improvements

### ISSUE THREAD

**Issue by thaodt** [tailcallhq/tailcall#554]
**Description**
- Consider introducing a service layer to handle business logic and separate it from the HTTP/gRPC logic. This will make the code more modular and easier to test.
- Use dependency injection to pass dependencies to components. This makes the code more flexible and easier to test.
- Consider moving some files from the root (src) to `utils` subdir instead. For e.g.` javascript.rs`, `path_string.rs`, `print_schema.rs`, `has_header.rs` should belong to `utils` subdir.

**Solution**
For illustrating how these things look like:
```bash
src/
|----------
├── di.rs                 // add new - dependency injection container 
├── document.rs
├── endpoint.rs
├── grpc
│   ├── client.rs
│   ├── mod.rs
│   └── reflection_client.rs
|   └── handler.rs        //    add new - grpc handler
├── has_headers.rs
├── http
│   ├── client.rs
│   ├── data_loader_request.rs
│   ├── data_loader.rs
│   ├── handler.rs        //    add new - http handler
│   ├── memo_client.rs
│   ├── method.rs
│   ├── mod.rs
│   ├── request_context.rs
│   ├── response.rs
│   ├── server_context.rs
│   └── server.rs
├── lib.rs
├── main.rs
├── mustache.rs
├── path_string.rs
├── print_schema.rs
├── request_template.rs
├── service               // add new - service layer
│   ├── grpc.rs
│   ├── http.rs
│   └── mod.rs
```

**Comment by tusharmath** [comment]
@thaodt Let me know if you think I should assign it to someone else.

**Comment by thaodt** [comment]
> @thaodt Let me know if you think I should assign it to someone else.

nope. I have code on local already, will push soon.

**Comment by tusharmath** [comment]
@thaodt It's been a while and I have unassigned this issue from you for now so that others can give this one a shot. Let me know if you are close and would like to continue, I can assign it back to you.

**Comment by thaodt** [comment]
Hi yes. Im close to make a PR, please assign it back to me

> @thaodt It's been a while and I have unassigned this issue from you for now so that others can give this one a shot. Let me know if you are close and would like to continue, I can assign it back to you.

**Comment by amitksingh1490** [comment]
@thaodt whats the progress on this? Can we have a draft PR for this to see If this is heading in right direction.

**Comment by thaodt** [comment]
> @thaodt whats the progress on this? Can we have a draft PR for this to see If this is heading in right direction.

Hi @amitksingh1490 sorry for taking a while to get back to you, I'm engaging deeply in another project and unfortunately Im no longer interests in Tailcall. 
Anyone feel free to take it, this issue was raised by me. Please ping me directly to discuss if you want to have more insights in this.
The idea was reducing the tight-coupled in the code to support more protocols better instead of the current one. Its sticking too tight in http handles on some parts I saw. It will make you duplicated code if you want to support grpc / add more protocols in the future.

**Comment by tusharmath** [comment]
Will close this issue in that case. Code structure has improved by a lot since the issue was opened with each PR getting getting merged.

**Comment by thaodt** [comment]
> Will close this issue in that case. Code structure has improved by a lot since the issue was opened with each PR getting getting merged.

Good to hear that @tusharmath. In fact, I still see the tightnesses. for e.g. https://github.com/tailcallhq/tailcall/blob/main/src/blueprint/into_schema.rs#L42 the `RequestContext` is originated from `http`. In case we use grpc, the RequestContext need to be generic and it could be http / grpc.

**Comment by tusharmath** [comment]
Sad to see you go to a different project @thaodt. I hope you will come back for some exciting new things soon!
