### ISSUE TITLE
Add tailcall to public benchmarks

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#558]
Add tailcall to https://github.com/graphql-crystal/benchmarks

Note it should take the latest release version of tailcall.

**Comment by alankritdabral** [comment]
@tusharmath I am new to git hub .Does  "public benchmarks" for the GraphQL Crystal project would involve measuring and evaluating the performance of the GraphQL implementation in the Crystal programming language under various scenarios and workloads?

**Comment by sc231997** [comment]
Hi @tusharmath 
The PR will be raised for https://github.com/graphql-crystal/benchmarks . So how will be able to claim the bounty?

**Comment by sc231997** [comment]
@tusharmath can you assign this issue to me.

**Comment by sc231997** [comment]
> Hi @tusharmath The PR will be raised for https://github.com/graphql-crystal/benchmarks . So how will be able to claim the bounty?

Looks like you have to tip a user in this case using `/tip $amount @user` https://docs.algora.io/tipping

**Comment by Dhanus3133** [comment]
I would like to attempt this issue

**Comment by tusharmath** [comment]
This is the accepted PR — https://github.com/graphql-crystal/benchmarks/pull/210#issuecomment-1792472130
