### ISSUE TITLE
Allow Empty Wrappers

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#564]
Empty wrapping of resolvers should be allowed. However it should fail if no resolver is found anywhere on the to it's leaf nodes. 

**Config**
```graphql
schema @server(port: 8000) @upstream(baseURL: "http://jsonplaceholder.typicode.com") {
  query: Query
}

type Query {
  posts: InPost
}

type InPost {
  get: [Post] @http(path: "/posts")
}
```
**Actual**
```bash
Error: Invalid Configuration
Caused by:
  • No resolver has been found in the schema [at Query.posts]
```

**Expected**
Server should be able to start successfully. 

---
The following should continue to throw errors because no resolver is found to resolve Post

**Config**
```graphql
schema @server(port: 8000) @upstream(baseURL: "http://jsonplaceholder.typicode.com") {
  query: Query
}

type Query {
  posts: InPost
}

type InPost {
  get: [Post]
}

type Post {
  id: Int!
  userId: Int!
  title: String!
  body: String!
  user: User @http(path: "/users/{{value.userId}}")
}

```

**Expected Error**
```
Error: Invalid Configuration
Caused by:
  • No way to resolve fields in Post from Query ❯ InPost ❯ Post [at Post]
```

**Comment by ezhil56x** [comment]
@tusharmath Can I work on this 🙋🏻

**Comment by ssddOnTop** [comment]
@tusharmath can you assign this to me

**Comment by amitksingh1490** [comment]
@Shylock-Hg, I'm sorry for the delay in getting back to your message and for assigning the task you were interested in to @ssddOnTop. We value your willingness to contribute to Tailcall and want to ensure that your contributions are recognized and appreciated. Would you be interested in taking on issue #414? We're looking forward to your involvement. Thank you for your understanding

**Comment by tusharmath** [comment]
@Shylock-Hg Apologies for the delay. This has been a miss from our end. Looking forward to your PR!
