### ISSUE TITLE
Static initialization of global variables

### ISSUE THREAD

**Issue by artech-git** [tailcallhq/tailcall#567]
I was studying the codebase recently, and something which drew my attention was the way how global statics were initialized !

currently it is being done using `lazy_static` crate but I think this can be made better using `once_cell` crate with some additional advantages as described below

currently we initialize global statics under lazy_static! macro blocks

```rust
lazy_static::lazy_static! {
  static ref TEST_VALUES: Value = {
    ...
    ...
    Value::Object(root)
  };
  ```
  with the help of `once_cell::sync::Lazy` initializer like this
  
 ```rust
static TEST_VALUES: Lazy<Value> = Lazy::new(|| {
    ...
    ...
   Value::Object(root)
 });
```
`Lazy<T>` implements the `Deref `& `DerefMut` traits for generic `T` hence it fits in the most scenarios without any special needs of changing huge parts of the codebases.

According to me these are the following benefits it will bring to the project 

1. **Simpler Syntax**:  `once_cell` provides a simpler and more ergonomic syntax for defining and initializing lazy values.
2. **No Global Mutex**: `lazy_static ` uses a global mutex to ensure thread safety during initialization. This can introduce contention in multi-threaded applications. `once_cell` uses per-value locks, which can be more efficient in certain scenarios. 
3 **Reduced Compilation Time**: `lazy_static` can slow down the compilation of your Rust project because it generates a lot of code for global initialization. In contrast, `once_cell ` is more lightweight in terms of generated code, leading to shorter compilation times.
4. **No Macro Magic**: `lazy_static` relies on macros to define lazy static variables. Some developers find this macro-based approach less intuitive, especially when working with complex data types. `once_cell` uses standard Rust syntax, making it easier to work with.
5. **Dynamic Initialization**: once_cell allows us to initialize a value based on runtime conditions or dynamic data, whereas lazy_static is more suited for statically initialized values.
6. **Compatibility with const**: In some cases, once_cell can be used with const values, which allows us to create lazily initialized constants.

To know more about this you can check the docs [here](https://docs.rs/once_cell/latest/once_cell/sync/struct.Lazy.html#impl-Deref-for-Lazy%3CT,+F%3E) and let me know what you think.

**Comment by tusharmath** [comment]
This is great idea. Would be interested in pick this up?

**Comment by artech-git** [comment]
> This is great idea. Would be interested in pick this up?

Sure I will work on this ASAP.

**Comment by tusharmath** [comment]
Please go ahead @artech-git
