### ISSUE TITLE
Run Formatter and lint passes with errors also

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcall#572]
### Describe the bug

`./lint.sh --mode=check` gives an error still the CI checks pass.

### Steps to reproduce

1. Check the Run Formatter and lint check step in any PR

### Expected behavior

`CI check` should fail if there are clippy errors

### Actual behavior

Errors are in log but the check still passes

### Screenshots

<img width="1264" alt="image" src="https://github.com/tailcallhq/tailcall/assets/23661702/c17a5fb3-bd5e-47f1-85c3-c37c67298b52">

### Environment information:
CI

**Comment by tusharmath** [comment]
fixed in #578
