### ISSUE TITLE
GroupBy does not work when the type of the grouped field is a list

### ISSUE THREAD

**Issue by sujeetsr** [tailcallhq/tailcall#574]
### Prerequisites

- [x] I have checked the existing issues to ensure this is not a duplicate.
- [x] I am running the latest version of Tailcall.

### Describe the bug
If the field with the batched api is a list, with a groupBy, an error is returned while querying

```graphql
type User {
  id: Int!
  name: String!
  username: String!
  email: String!
  phone: String
  website: String
  posts: [Post] @http(path: "/posts?userId={{value.id}}" groupBy: ["userId'])
}
```

**Comment by tusharmath** [comment]
fixed in #571
