### ISSUE TITLE
[External] GraphQL LSP Server Crash

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#579]
Original Issue: https://github.com/graphql/graphiql/issues/3429

**Comment by xonx4l** [comment]
can you assign it to me @tusharmath

**Comment by tusharmath** [comment]
@xonx4l were you able to make any progress on this issue?

**Comment by xonx4l** [comment]
YEAH I TRIED TO REPRODUCE BUT ON MY SYSTEM IT WORKS FINE . MAYBE I WILL EXPLORE WITH DIFFERENT CONFIG .

**Comment by A-N-uraag** [comment]
Hi @tusharmath, can I get assigned? I could reproduce the issue and am currently stepping through the LSP server to fix it.

**Comment by tusharmath** [comment]
👍

**Comment by A-N-uraag** [comment]
Hi @tusharmath, This will be fixed with https://github.com/graphql/graphiql/pull/3464. Here is a recording showing that the server does not crash anymore.

https://github.com/tailcallhq/tailcall/assets/47111459/f1f4bd66-4bfc-4c1e-b663-e83303a9ae60

**Comment by ologbonowiwi** [comment]
/claim tailcallhq/tailcall#576 on the PR to claim the bounty @A-N-uraag

**Comment by A-N-uraag** [comment]
Looks like it is not working since graphql org does not have the algora-bot setup, @ologbonowiwi.

**Comment by ologbonowiwi** [comment]
Hey @algora-pbc, a hand here? 🤌🏽

**Comment by algora-pbc** [comment]
Thanks for the ping, claim's been recorded! 🫡

<a href="https://tailcallhq.algora.io/bounties"><img src="https://github.com/tailcallhq/tailcall/assets/136125894/c866aab2-b77c-4faf-a933-47659c44c7bc" width="221" /></a>

(Btw we were literally experimenting with a solution to this edge case right now -- hoping to ship it in the near future)

**Comment by A-N-uraag** [comment]
Hi @tusharmath, the referred PR has been merged. Please have a look when free. Thanks.

**Comment by A-N-uraag** [comment]
/claim https://github.com/graphql/graphiql/pull/3467
Had to re-work the PR to add the changeset.

**Comment by tusharmath** [comment]
@A-N-uraag Since this is an external issue, I will be rewarding bounty as a tip.

/tip 100$ @A-N-uraag

**Comment by tusharmath** [comment]
/tip 50$ @A-N-uraag 

For solving a major pain point for the graphql community 🙏 🙏 🙏 
Thank you @A-N-uraag !!!

**Comment by A-N-uraag** [comment]
@algora-pbc A little help here with the second tip please? Thanks.
