### ISSUE TITLE
Example didnt work for json & yml

### ISSUE THREAD

**Issue by thaodt** [tailcallhq/tailcall#599]
### Prerequisites

- [x] I have checked the existing issues to ensure this is not a duplicate.
- [x] I am running the latest version of Tailcall.

### Describe the bug

I'm checking on the latest main branch and when Im running the start and check command, it threw this error:

### Steps to reproduce

Run `cargo r check examples/jsonplaceholder.yml` or `cargo r check examples/jsonplaceholder.json`
or `cargo r start examples/jsonplaceholder.json` or `cargo r start examples/jsonplaceholder.yml`
Output: 
```
Error: missing field `added_fields` at line 41 column 7
```

### Expected behavior

It should start server as normal.

### Actual behavior

throw out the error above.

### Screenshots

![image](https://github.com/tailcallhq/tailcall/assets/5485589/33605575-33fd-4174-828f-d9222471c28f)

### Environment information:

- **Operating System**: Arch Linux 6.5.9
- **Tailcall Version**: tc 0.1.0-dev
- **Rust Version**: `rustc 1.73.0`

**Comment by artech-git** [comment]
@thaodt on my machine this error shows
```
Error: missing field `upstream` at line 82 column 1
```

**Comment by artech-git** [comment]
@thaodt I researched it a bit, I think 8ed004ca could be the commit from where this starts !
