### ISSUE TITLE
Add support for `only` `skip` and `failing` annotations in `GraphQLSpec`

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#603]
Currently there is no way for a developer to control which spec to run, ignore or expect to fail.

```diff
 struct GraphQLSpec {
   path: PathBuf,
   client_sdl: String,
   server_sdl: Vec<String>,
   merged_server_sdl: String,
   sdl_errors: Vec<SDLError>,
   test_queries: Vec<GraphQLQuerySpec>,
+  annotation: Option<Annotation>
 }

+ enum Annotation {Skip, Only, Fail}
```

The annotations will contain `skip` or `only` or `failing`

**Technical Specifications**
- `only`: If any spec contains `only` only that spec should be executed. Eg:
  ```graphql
  #> spec-only
  
  #> server-sdl
  schema { query: Query }
  
  #> client-sdl
  schema {query: Query}
  ```

- `skip`: if a spec contains `skip` then that should be skipped, and a warn log should be printed. Eg:

  ```graphql
  #> spec-skip
  
  #> server-sdl
  schema { query: Query }
  
  #> client-sdl
  schema {query: Query}
  ```

- `fail`: Expect the spec to fail. Panic incase it doesn't fail. Eg:
  ```graphql
  #> spec-fail
  
  #> server-sdl
  schema { query: Query }
  
  #> client-sdl
  schema {query: Query}
  ```

**Comment by tobihans** [comment]
Please, can I get assigned, @tusharmath ?

**Comment by tusharmath** [comment]
Sure @tobihans !

**Comment by tusharmath** [comment]
@tobihans did u get a chance to work on it or can we release it for others to try?

**Comment by ologbonowiwi** [comment]
Hey @tusharmath, I want to give a suggestion.

IDK if it is possible, but a desirable behavior it'd be `cargo test name-of-test.graphql`, as we have this kind of experience in lots of frameworks, so it'd be kind of familiar to new contributors.

**Comment by tobihans** [comment]
I'm on it @ologbonowiwi

**Comment by tobihans** [comment]
> Hey @tusharmath, I want to give a suggestion.
> 
> IDK if it is possible, but a desirable behavior it'd be `cargo test name-of-test.graphql`, as we have this kind of experience in lots of frameworks, so it'd be kind of familiar to new contributors.

Can you elaborate more, please ?

**Comment by ologbonowiwi** [comment]
Surely I can.

so I came from the Node.js ecosystem, and popular libraries like jest and test have an interesting standard for selecting which test you want to execute.

You can go to the root of a project with Jest and type `jest <pattern-of-your-file>,` and jest will execute only files with that pattern. Bringing it to our context, we would type, for example, `cargo test http,` which would run all tests with `http` on their name.

Note that this is nice to have (in my opinion), but it's not part of @tusharmath's description of what needs to be done, so I don't recommend implementing it now.

**Comment by tobihans** [comment]
Ok, I get you now. Yeah, cargo provide test filtering AFAIK. It's not related to the description as you said. Thanks
