### ISSUE TITLE
Support HTTP2 on Tailcall WebServer

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#605]
Currently tailcall only support HTTP 1.1. We need a configuration to enable HTTP 2 also. 

It should be configured via the `version` field inside of `@server`. By default it should be HTTP1.
```graphql
schema @server(version: HTTP2) {
  query: Query
}

type Query {
  user: User
}
```

**Comment by tusharmath** [comment]
@ssddOnTop you already have https://github.com/tailcallhq/tailcall/issues/441 assigned to you Let someone else get a chance to do this one.

**Comment by ologbonowiwi** [comment]
I'll give this a shot /attempt #605

**Comment by ologbonowiwi** [comment]
Hey guys, can you assign this to me? I'm working on it @tusharmath @sujeetsr @amitksingh1490

**Comment by ologbonowiwi** [comment]
if the user sets version HTTP2, what should we do?

receive the certificates from the user? create certificates locally and push them to the tailcall repo?

**Comment by neo773** [comment]
@ologbonowiwi 
Damn did not see the GitHub issue activity as I went out for a walk after wrapping up work.
How far were you into it?

**Comment by ologbonowiwi** [comment]
NP @neo773. I was the same as you except for the changes on `src/http/server.rs`. You did not need to use certificates to set up the server?

**Comment by neo773** [comment]
> NP @neo773. I was the same as you except for the changes on `src/http/server.rs`. You did not need to use certificates to set up the server?

Nope, tailcall doesn’t support https yet
