### ISSUE TITLE
Fail with an error if no platform build is found

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#606]
**Steps**
```bash
npm i -g @tailcallhq/tailcall
```

Because all platform dependencies are optional, sometimes nothing gets installed. In that case, there should be an error issued stating that the platform is not yet supported, and the user should create an issue on our github repository.

**Comment by Min2who** [comment]
can you assign this to me @tusharmath

**Comment by Min2who** [comment]
@tusharmath I can use an external library right

**Comment by Min2who** [comment]
@tusharmath is this approach correct
![Screenshot (83)](https://github.com/tailcallhq/tailcall/assets/127925465/79a931c4-e20c-4e43-893f-3bcf342c4544)

**Comment by jkcs** [comment]
@tusharmath Regarding this issue, I have a few questions. Are you suggesting the following: 
1. When users globally install `@tailcallhq/tailcal`l using `npm i -g @tailcallhq/tailcall`, perform a platform compatibility check?
2. When users install `@tailcallhq/tailcall` within a project using `npm i @tailcallhq/tailcall`, also perform the compatibility check?

Current: Only when installing the package within a project (not globally), the corresponding platform-specific implementation package is directly installed.

If you want the code to execute during global installation, placing it in the postinstall script will not work. If you want to achieve execution during global installation, you can assign this issue to me.

**Comment by sc231997** [comment]
I am also facing a similar issue my os:linux and arch:x64 and none of the packages are getting installed.
