### ISSUE TITLE
Integrate Scarf SDK on NPM

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#612]
Integrate scarf sdk with `@tailcallhq/tailcall`.

**Additional Info**
https://www.npmjs.com/package/@scarf/scarf

**Comment by Min2who** [comment]
can this be assigned to me @tusharmath

**Comment by Min2who** [comment]
@tusharmath from which credentials does we create a package entry on Scarf
means should i use my personal credentials

**Comment by Min2who** [comment]
@tusharmath   Arjun(from team scarf) said that you have created the package entry do i need to get access to it to start working or i can proceed with it

**Comment by jkcs** [comment]
@tusharmath I just reviewed the previous pull request, and I feel that it did not resolve the issue. If you're willing, I can include the solution in my own pull request.

**Comment by Min2who** [comment]
@tusharmath i have added a PR please review it

**Comment by Min2who** [comment]
@tusharmath  I have added the PR hope you review it soon

**Comment by Min2who** [comment]
@tusharmath if i am approaching the problem wrongly

**Comment by jkcs** [comment]
I will queue

**Comment by jkcs** [comment]
I'll join the queue
