### ISSUE TITLE
`tc start` should show n + 1 issues at log-level=INFO

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#637]
N + 1 issues are displayed only in the check command at the moment. We propose that the users should be able to see the total number of N + 1 issues that exist at the time of `tc start`.

The N + 1 information is only shown in case the log level is <= INFO.

**Comment by neo773** [comment]
Can I get assigned?

**Comment by A-N-uraag** [comment]
Hi @tusharmath, Can I work on this?

**Comment by A-N-uraag** [comment]
Hi @neo773, I just opened the feed to ask if I can work on this to gain some more experience(and hunt the bounty ngl) with the codebase. I see that the code coverage is not done in your PR yet. Can I add the tests for this? We could split the bounty if you like but I am fine with you having fully too. I just want to gain some experience around the project.

**Comment by neo773** [comment]
@A-N-uraag 
I think that should be done in a separate PR as it's not in the scope of this issue.
And as far I recall there's partial coverage via unit tests.

**Comment by A-N-uraag** [comment]
Hi @neo773 and @tusharmath. I have submitted a PR since the earlier one was different that what was expected. Hope that's fine.
