### ISSUE TITLE
tc.exe is not compatible with the version of Windows you're running

### ISSUE THREAD

**Issue by jkcs** [tailcallhq/tailcall#647]
### Prerequisites

- [ ] I have checked the existing issues to ensure this is not a duplicate.
- [x] I am running the latest version of Tailcall.

### Describe the bug

Installed `tailcal`l error on a 64-bit Windows operating system, installed the 32-bit `core-win32-x64-msvc`.

### Steps to reproduce

1. On a 64-bit platform running Windows 10
2. Execute the command: `npm i -g @tailcallhq/tailcall`
3. Execute the command: `tc`

### Expected behavior

Everything is fine.

### Actual behavior

A dialog box stating 'tc.exe failed to start or run. Please contact the software vendor to inquire about a version compatible with 64-bit Windows'

### Screenshots

![image](https://github.com/tailcallhq/tailcall/assets/38372737/3b19ccc7-90fb-47f9-a30a-f5309ece52d4)
![image](https://github.com/tailcallhq/tailcall/assets/38372737/2038af99-5a9e-4157-8504-ca52ea728089)

### Environment information:

- **Operating System**:  Windows 10
- **Tailcall Version**:  last
- **Rust Version**:  -
- **GraphQL Client/version** (e.g., `curl/8.1.2`)

### Additional context

`@tailcallhq/core-win32-x64-msvc`  does not support 64-bit Windows programs

**Comment by amitksingh1490** [comment]
@jkcs could you please specify the tailcall version you are trying to install?
is it v0.15.1

**Comment by jkcs** [comment]
@amitksingh1490 The result is the same.

**Comment by amitksingh1490** [comment]
@jkcs are you running this on VM or actual windows machine.
also can you try downloading and executing this on your machine
https://github.com/tailcallhq/tailcall/releases/download/untagged-59144574d23bdbdf7af5/tailcall-aarch64-pc-windows-msvc.exe

**Comment by jkcs** [comment]
@amitksingh1490 Actual windows. I tried "[tailcall-x86_64-pc-windows-msvc.exe](https://github.com/tailcallhq/tailcall/releases/download/v0.15.1/tailcall-x86_64-pc-windows-msvc.exe)" and it's okay. As for the link you sent, when I opened it, it showed a 404 error
