### ISSUE TITLE
Add tests for `cache-control` header using http_spec

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#652]
Write tests under `/http` to assert if the cache control headers are being forwarded correctly when set in any upstream responses. Also test if minimum is computed correctly in case multiple requests sent upstream have different cache control headers.

**Comment by ezhil56x** [comment]
@tusharmath Can I work on this 🙋🏻

**Comment by A-N-uraag** [comment]
Hi @tusharmath, it's taking a bit longer to understand the LSP server codebase(re: #579). I will keep working on it. But, can I tackle this first? Would love a break from typescript and do rust 🦀.

/attempt

**Comment by tusharmath** [comment]
@A-N-uraag Let's welcome @ezhil56x to the tailcall community and give him a chance :)

**Comment by ologbonowiwi** [comment]
@ezhil56x If you need a hand feel free to reach out on #contributors on Discord :smile:

**Comment by tusharmath** [comment]
This is a small change, opening this issue up for everyone to pick up!
