### ISSUE TITLE
Cache Control Bug with no-store

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#670]
The bug is pointed to in this PR

https://github.com/tailcallhq/tailcall/pull/669/files#diff-3b02f0ed8b516a325866c0d66fe5898cb708590994d2452158fdda5cbba46163R83

**Comment by Min2who** [comment]
can you assigned me this @tusharmath

**Comment by A-N-uraag** [comment]
/attempt
@Min2who, I already worked on one half of it while writing the tests.

**Comment by Min2who** [comment]
@A-N-uraag sorry for seeing it late i have made the changes required what shall i do?

**Comment by A-N-uraag** [comment]
Oh, ok. Go ahead and push them then. 👍🏻

**Comment by amitksingh1490** [comment]
@A-N-uraag I have assigned this to you as you have already partially worked on this one. And this is kinda blocker for this release

**Comment by A-N-uraag** [comment]
Hi @amitksingh1490 , thanks. Will start working on it.

**Comment by b4s36t4** [comment]
@amitksingh1490 @tusharmath  I found the root-cause for the issue. But the solution I'm thinking could be wrong or not collide with the standards or so. 

Can I raise a draft PR to support the issue?
