### ISSUE TITLE
Add a test for server start 

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#687]
Write a test that does the following

- Starts a GraphQL server on port 8000.
- Make 100 requests to the server.
- Assert the shape of the response received.
- Kill the server and end the test.

**Technical Requirements**
- Use the following GraphQL Config
  ```graphql
  schema @server(port: 8000) {
    query: Query
  }
  
  type Query {
    greet: String @const(data: "Hello World!")
  }
  ```
- Test should run under 100ms.

**Comment by neo773** [comment]
Can I get assigned

**Comment by ologbonowiwi** [comment]
Hey @yuvrajjsingh0, the issue is already assigned to neo so even if you open a PR before him your PR can be closed as he started to work on it already. 

I highly recommend for you to search any other open issue that does not have anyone assigned to. We have some of them :smiley:

**Comment by melsonic** [comment]
I want to work on this one. Can anyone assign this to me?
