### ISSUE TITLE
Simplify init subcommand

### ISSUE THREAD

**Issue by alexanderjophus** [tailcallhq/tailcall#698]
**Is your feature request related to a problem? Please describe.**
Following on from our discussion in discord.
- The first question doesn't make too much sense to me. If I didn't mean to call the command, I would cancel the command. It also errors if the directory doesn't exist.
- If the directory I'm targeting doesn't exist, init should create the directory
- I wasn't initially aware that init created 2 hidden files, as well as an empty file with the name of the schema I wanted

Feel free to break this up into smaller tickets, especially the last point.

**Describe the solution you'd like**
- Remove the first question
- Create the directory (or at least ask if I want it created if it doesn't already exist)
- Some output of what was created would be helpful (I appreciate this is in the docs already), or maybe expand on the help section of the subcommand.

**Describe alternatives you've considered**
See above (for the or)

**Additional context**
<img width="614" alt="image" src="https://github.com/tailcallhq/tailcall/assets/12949385/c8658bc1-299f-4b77-ba75-acfa28d69178">
Diagram should be amended to say errors if the user presses no at first and the dir doesn't exist.

**Comment by tusharmath** [comment]
May be we can just stick to generating a `.tailcallrc.graphql` file every time someone says `init`. Ask the user if it can be overwritten incase it already exists. The rest of the stuff is quite opinionated, confusing and would rather keep it in the tailcall documentation than integrating in the CLI. Let me know what you think.

**Comment by alexanderjophus** [comment]
I'd still highlight to the user a file is going to be created for `.tailcall.graphql`, but otherwise that sounds really good.

**Comment by tusharmath** [comment]
Perfect. Can you please update the issue with the exact requirements?

**Comment by rajdip-b** [comment]
can i be assigned this issue?

**Comment by tusharmath** [comment]
@meskill This is the overall flow I am thinking (psuedo rust code) — 

run the `tailcall init` command
```rust
tc_rc = fs::exist(".tailcallrc.graphql")
gq_rc = fs::exist(".graphqlrc.yml")

if gq_rc {
  if tc_rc {
    match confirm_overwrite() {
      YES => write(tc_rc),
      No  => ()
    };
  }
} else {
  write(gq_rc);
  write(tc_rc);
}

if !gq_rc.contains(tc_rc) {
  match confirm_update() {
    YES => write(gq_rc);
    No  => write(gq_rc);
  }
}
```

**Comment by meskill** [comment]
@tusharmath mostly agree.

just small adjustments:
- first two nested ifs should be separated since if .tailcallrc.graphql exists we need to ask for overwrite permission anyway
- in both No actions we should do nothing

**Comment by meskill** [comment]
> @meskill This is the overall flow I am thinking (psuedo rust code) —
> 

There is an updated version of the pseudocode 

```rust
let mut tc_rc = fs::exist(".tailcallrc.graphql")
let mut gq_rc = fs::exist(".graphqlrc.yml")

if gq_rc {
  tc_rc = gq_rc.get_tc_rc();  
} else {
  write(gq_rc);
}

if tc_rc {
  match confirm_overwrite() {
    YES => write(tc_rc),
    No  => ()
  };
} else {
  write(tc_rc);
}

if !gq_rc.contains(tc_rc) {
  match confirm_update() {
    YES => write(gq_rc);
    No  => ();
  }
}
```

**Comment by meskill** [comment]
@neo773 Do you still have intention to finish this?
