### ISSUE TITLE
Remove nginx setup from Macro Benchmarks ci job

### ISSUE THREAD

**Issue by meskill** [tailcallhq/tailcall#724]
The nginx is started in `Macro Benchmarks` job but is not actually used for server. Remove nginx mentions in the `bot.yml` but preserve all the nginx config in the repo for future usages and testing

**Comment by ezhil56x** [comment]
@tusharmath Can I get this assigned?

**Comment by Rutik7066** [comment]
Hey @tusharmath i would like work on this it will take few mins.
