### ISSUE TITLE
Automatically open the GraphiQL IDE on Start

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#735]
On `tailcall start` command, the CLI should automatically open the default browser with the configured IDE link.

**Technical Specification**
- Make sure this only happens if the graphiql setting is enabled.
- Do not write code from scratch, instead use https://github.com/amodm/webbrowser-rs or https://github.com/Seeker14491/opener and justify your reasoning in the PR.

**Comment by guptadeepak8** [comment]
Can you assign me ?
