### ISSUE TITLE
Show log info instead of error

### ISSUE THREAD

**Issue by ologbonowiwi** [tailcallhq/tailcall#738]
### Prerequisites

- [x] I have checked the existing issues to ensure this is not a duplicate.
- [x] I am running the latest version of Tailcall.

### Describe the bug
The `main` branch has an unexpected behavior on test execution. As shown on [this pipeline execution](https://github.com/tailcallhq/tailcall/actions/runs/7164375841/job/19504325802#step:6:344), we have an `http_spec` test that is logging `ERROR`, when there is no actual test failing.

### Steps to reproduce

1. Pull last changes from main
2. Run `cargo test`

### Expected behavior

The log should be `INFO http_spec] Graphql datasource your_file_path/tailcall/tests/http/graphql-dataloader-batch-keys.yml ... ok`

### Actual behavior

The log is `ERROR http_spec] Graphql datasource your_file_path/tailcall/tests/http/graphql-dataloader-batch-keys.yml ... failed`

### Screenshots
<img width="1340" alt="image" src="https://github.com/tailcallhq/tailcall/assets/100464352/283c4e0a-b164-4b01-bab2-8558d8f4d6a3">

As mentioned by @amitksingh1490 
> this error shows that the test is supposed to fail and failing as expected.

**Comment by ezhil56x** [comment]
Can I get this assigned?
