### ISSUE TITLE
Remove the spawner field from DataLoader

### ISSUE THREAD

**Issue by shashitnak** [tailcallhq/tailcall#739]
**The Problem**
A part of the issue #419 to make the DataLoader more efficient. Since it is known which `async` runtime has to be used, `DataLoader` doesn't need to take a `spawner` in the constructor.

**Solution**
Remove `spawner` field from `DataLoader` type in `src/data_loader/data_loader.rs` and make the changes accordingly.

**Comment by Rutik7066** [comment]
hey @tusharmath i would like to work on this. could you assign this to me.
