### ISSUE TITLE
Inconsistent styling between check and start

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#757]
Adding a screenshot of how the errors look today.

<img width="773" alt="Screenshot 2023-12-17 at 10 35 55 AM" src="https://github.com/tailcallhq/tailcall/assets/194482/a264cbe4-3127-49e1-b213-40fbc8b5f106">

**Expectation**
- We need the `check` command to show errors in the same way as the `start` command. 
- There should be absolute reuse of code, practically `start` should be re-using `check`.

**Comment by NishanthMolleti** [comment]
can I work on it @tusharmath
