### ISSUE TITLE
Stackoverflow Errors on recursive types

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#758]
Across the Config to Blueprint compiler the current implementation leverages recursion, which breaks  whenever there are recursive types. There is no one strategy we can use everywhere to fix this.

**Example**

```graphql
schema {
  query: Query
}

type Query {
  list: List
}

type List {
  head: Int!
  tail: List
}
```

```bash
tailcall start ./app.graphql
```

**Additional Information**
- JsonSchema might need a bit of re-write. It doesn't support recursive types at the moment.

**Comment by ologbonowiwi** [comment]
I know it's assigned, declaring myself willing to collaborate/on the queue on this one 🤚🏽

**Comment by Rutik7066** [comment]
hey @A-N-uraag  your PR is closed is there anything left ?

**Comment by tusharmath** [comment]
Opening this up for everyone to attempt.

**Comment by ayewo** [comment]
@Rutik7066 this is your chance

**Comment by tusharmath** [comment]
@Rutik7066 already has an issue assigned to him.

**Comment by meskill** [comment]
assigning back to @A-N-uraag since they have work in progress on it

**Comment by KiranKBR** [comment]
@tusharmath could you assign to me?

**Comment by digital-phoenix** [comment]
@tusharmath is this still an issue?
