### ISSUE TITLE
Add a `@link` operator

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#760]
### Overview
Introducing the `@link` operator for linking and importing of external files in configurations.

#### Proposed GraphQL Schema Definition
Create a link operator that has `src`, `type` and `id` fields as follows.
```graphql
schema 
  @link(type: "tailcall/graphql", src: "https://abc.com/graphql")
  @link(id: "abc" type: "tailcall/yml", src: "https://abc.com/application.yml")
  @link(type: "tailcall/graphql", src: "https://abc.com/application.graphql") {
  query: Query
}
```

**Technical Requirements**
- Each file is resolved and inside of config_reader.
- Resolved files are either merged with the original config or attached as an extension in the config_set.

**Comment by ssddOnTop** [comment]
May I try

**Comment by b4s36t4** [comment]
Would love to work on this.

**Comment by Ashu999** [comment]
next in line, if need to reassign

**Comment by amitksingh1490** [comment]
@b4s36t4 Should we reassign this?

**Comment by tusharmath** [comment]
Releasing this issue for everyone to attempt. @Ashu999 let me know if you'd want me to assign it to you.

**Comment by Ashu999** [comment]
@tusharmath yes please, assign it to me

**Comment by SourikAdhikary** [comment]
Happy to do this if a need comes up.

**Comment by guhitb** [comment]
I'd like to work on this, can I be assigned?
