### ISSUE TITLE
improve `@const` to support reading data from files and urls

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#764]
Currently `@const` only supports resolving data using an inlined approach.

```graphql
type Query {
  user: User @const(data: {name: "John", age: 21})
}
```

**Proposal**
We need to support data via `@link` so that we can refer to data that is on some remote location or local file system.

```graphql
schema @link(id: "constData", type: Data, src: "https://abc.com/constant-json-data") {
  query: Query
}
type Query {
  user: User @const(data: "{{link.constData}}") #Refer to the id of the linked data source.
}
```

**Additional Info:**
This should only be taken up after #760 is implemented.

**Comment by melsonic** [comment]
in line

**Comment by melsonic** [comment]
up for it
