### ISSUE TITLE
Bug in evaluating {{args}} in mustache template

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcall#774]
### Prerequisites

- [x] I have checked the existing issues to ensure this is not a duplicate.
- [x] I am running the latest version of Tailcall.

### Describe the bug

When there are multiple named args defined in a query and you need to pass them as body in your http request. The mustache evaluation just evaluate to a empty string. e.g
```graphql
type Query {
  firstUser(id: Int, name: String): User @http(method: POST, path: "/users", body: "{{args}}")
}
```

### Steps to reproduce

1. Failing test is written in #773 

### Expected behavior

1. `args` object should be sent as json in the body when specified in a mustache template like this `"{{args}}"`.
1. There should not be any performance drop.
1. remove `runner: fail` from the test and the test should pass.

### Actual behavior

Empty String is sent as body.

**Comment by Kartik1397** [comment]
@tusharmath I would like to work on this issue
/attempt #774

**Comment by Ashu999** [comment]
would like to work on this

**Comment by Sambit003** [comment]
@amitksingh1490 @tusharmath Can I start working on this issue ?

**Comment by amitksingh1490** [comment]
@Kartik1397 Please go ahead

**Comment by ologbonowiwi** [comment]
I have a 90% solution here (the investigation went well; the only remaining thing is a reference error on the compiler).

If you end up not finishing (or want to collaborate on it :smile:) let me know @Kartik1397. From my findings, the data we need to return is under `graphql_ctx.args()` (sharing so you do not need to do the investigation blindly :smile:)
