### ISSUE TITLE
Dynamically Load JS Execution Engine

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#781]
Currently, JS execution is behind a feature flag and you need to rebuild the application using those flags to write any custom JS code. This makes it harder to try out the JS features using Tailcall.

**Technical Requirements**
- Build on top of optimizations done in #611 by @meskill 
- JS Execution should be downloaded and integrated dynamically if a `@js` is detected anywhere in the configuration
- Download and linking should happen only if the user consents to downloading the feature.

**Comment by noctisatrae** [comment]
Hey! This is such a compelling challenge to tackle! I just need some information before getting started with a PR though:

- 1. Can you show me where others operators are implemented ? So I can mimic the way you've done certains things which will allow me to write consistent code for the codebase!

**Comment by ologbonowiwi** [comment]
/attempt #781

I'd like more information on one unclear thing: Can you give use-case examples about how this will be used? What we could/need to execute on/with JS?

**Comment by tusharmath** [comment]
@ologbonowiwi check out #611. It has tests and examples. Lets connect on discord if something is not clear.

**Comment by ologbonowiwi** [comment]
[thread on discord](https://discord.com/channels/1044859667798568962/1189207082285682818) discussing about this issue.

I'm dropping this here as context to help whoever will work on this one. Unfortunately, there is much to do here, and I'd need more time/focus to handle it. Unassigning from me; everyone else, feel free to attempt :smile:

**Comment by tusharmath** [comment]
@Khalid6468 Let me know if you'd want to try this.

**Comment by shashitnak** [comment]
@tusharmath I would like to attempt this if no one else is currently working on this

**Comment by tusharmath** [comment]
Go ahead

**Comment by ologbonowiwi** [comment]
This needs to be closed, no @tusharmath?
