### ISSUE TITLE
Feature add `compose` command

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#782]
We should create a new compose command that allows us to compose configurations. This feature is already implemented via `check` command.

**Usage for `compose`**
Print the composed configuration on the terminal using a format
```bash
tailcall compose a.yml b.graphql c.json --format=YML
```

**Improvements in `check`**
Passing `--blueprint` should print the blueprint on the CLI.
```bash
tailcall check a.yml b.graphql c.json --blueprint
```

**Additional Requirements**
- Drop the `--out` parameter from `check`

**Comment by adelinaenache** [comment]
Hey, may I work on this?

**Comment by Ashu999** [comment]
in queue if re-assigned

**Comment by melsonic** [comment]
in queue

**Comment by adelinaenache** [comment]
@tusharmath Hey there, I have some questions: 
1.  In what format should be the configuration displayed in the terminal? (when there is no out file)? 
2. If there is no out file, wouldn't be a good idea to add a parameter that specify the format of the composed config displayed? 
3. What is the difference between the blueprint and the config? I can see that there is a function `display_schema` that prints only the schema from the blueprint, but I am not sure that is what it should output.

**Comment by tusharmath** [comment]
@adelinaenache Good questions
> In what format should be the configuration displayed in the terminal? (when there is no out file)?

Default should be "pretty" json. But user should be able to customize it via the `--format`.

> If there is no out file, wouldn't be a good idea to add a parameter that specify the format of the composed config displayed?

Yes. We can add a `--format` option.

> What is the difference between the blueprint and the config? I can see that there is a function display_schema that prints only the schema from the blueprint, but I am not sure that is what it should output.

Config is what is inputted by the user. It validated and converted into a blueprint. The blueprint is like config, but stricter. If we have a blueprint we can be sure that a graphql server can be built using it, however we can't guarantee the same using a Config.

**Comment by adelinaenache** [comment]
> Config is what is inputted by the user. It validated and converted into a blueprint. The blueprint is like config, but stricter. If we have a blueprint we can be sure that a graphql server can be built using it, however we can't guarantee the same using a Config.

Ok so I'm trying to figure out what should I output when `--blueprint` is used vs when it's not used. Until now, I get that I should use the Config class to output normal configuration and the generated `Blueprint` class when using `--blueprint`.
So, what am I getting until now is:
1. For normal configuration (without --blueprint option), shouldn't be any validity check in place? (just read from files and do not convert it into a blueprint, output the config just like with `check`)
2. With `--blueprint` option, should I add some additional code on the `Blueprint` that converts it to either YML or json and use that to write to file? 
3. Why we disallow writing GQL schemas with `--blueprint`?

**Comment by tusharmath** [comment]
> For normal configuration (without --blueprint option), shouldn't be any validity check in place? (just read from files and do not convert it into a blueprint, output the config just like with check)

Yes we should just compose them together without validating.

> With --blueprint option, should I add some additional code on the Blueprint that converts it to either YML or json and use that to write to file?

You can use serde and serde_yml to do this.


>  Why we disallow writing GQL schemas with --blueprint?

I am not sure what you mean by this question.

**Comment by tusharmath** [comment]
@adelinaenache Let me know if you are still on this or if I should reassign.

**Comment by melsonic** [comment]
@tusharmath I want to work on this one can you assign this to me?
