### ISSUE TITLE
Support for reading environment variables

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcall#790]
In our configuration, wherever we support mustache templates, we should support the ability to read environment variables.

**Example Usage:**
```graphql
  schema 
    @server(vars: [{key: "auth", value: "{{env.AUTH_TOKEN}}"}])
    @upstream(baseURL: "http://{{env.UPSTREAM_HOST_NAME}}:{{env.UPSTREAM_PORT}}") {
  query: Query
}
```

**Technical Requirements:**
- Environment variables should be read at the time of starting the server.
- Tests should be added in `tests/http` in yml format.

**Comment by ezhil56x** [comment]
Can I work on this?

**Comment by Rutik7066** [comment]
hey @tusharmath may i attempt this one.

**Comment by abhijitSingh86** [comment]
May I attempt this one?

**Comment by ezhil56x** [comment]
@tusharmath
I am unable to make up with this. Please assign this to the next person or someone who can work on this

**Comment by ologbonowiwi** [comment]
Hey @amitksingh1490 @tusharmath, for this one IMO we should have a new operator like `@env` for setting the env file path (or files path potentially). What do you think guys?

And btw, I'd love to work on this one :smile:

**Comment by tusharmath** [comment]
@ologbonowiwi Env variables are available to read via rust's native API I don't think we need another `@env` operator. Have a look at https://www.thorsten-hans.com/working-with-environment-variables-in-rust/
