### ISSUE TITLE
Log Level should be passed as an environment variable

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcall#791]
**Problem:**
Currently log-level can only be specified in the `start` command via the `--log-level` parameter. There is no way to configure the log level in other commands. 

**Proposal**
Instead of a cli param, we should set the log level using environment variables. 

```bash
# Option 1
TAILCALL_LOG_LEVEL=DEBUG tailcall start ./main.graphql

# Option 2
TC_LOG_LEVEL=DEBUG tailcall start ./main.graphql
```

**Technical Requirements**
- Log level should be read from `TAILCALL_LOG_LEVEL` and then from `TC_LOG_LEVEL`.
- Drop the `--log-level` from the `start` command

**Comment by adelinaenache** [comment]
Hi there, may I do this?

**Comment by abhijitSingh86** [comment]
May I attempt this one?
