### ISSUE TITLE
Support for IO calls in `@unsafeJS` operator

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcall#795]

**Comment by SourikAdhikary** [comment]
Hi @amitksingh1490 , could you add more context to this?

**Comment by amitksingh1490** [comment]
@SourikAdhikary We haven't finalised the design and requirement on this yet.

**Comment by SourikAdhikary** [comment]
@amitksingh1490 Okay! Happy to discuss on this and take it up if possible
