### ISSUE TITLE
Write a guide on Logging

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#809]
Write an engaging document on the new logging feature that's been added to tailcall. Ensure that there is enough depth in the content. The current document isn't detailed enough.

**Requirements**
- Update the doc written here https://github.com/tailcallhq/tailcall/blob/main/docs/guides/logging.md
- Add examples of how it can be used.
- Use [excalidraw](https://excalidraw.com/) if you need to create images to explain something.

**Comment by melsonic** [comment]
i want to work on this one @tusharmath please assign this to me

**Comment by ezhil56x** [comment]
Can I get this assigned?
