### ISSUE TITLE
Write a guide on using HTTP2 in Tailcall

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#810]
Write a detailed guide on how one can leverage HTTP2 using Tailcall. Talk about both using it on the ingress and the egress side.

**Technical Requirements**
- Add it in docs/guides
- Use excalidraw for imagery.

**Comment by Min2who** [comment]
@tusharmath i can work on that

**Comment by ShatilKhan** [comment]
@tusharmath I'd like to work on this, please assign

**Comment by Min2who** [comment]
@ShatilKhan im already working on it
