### ISSUE TITLE
Write a guide about config and blueprint

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#811]
Write a note about blueprint and config and there relevance in tailcall. 

**Additional Note**
- Refer to the `architecture.excalidraw` file to understand the architecture. Feel free to update it. Use this extension to view the file https://marketplace.visualstudio.com/items?itemName=pomdtr.excalidraw-editor
- Make sure the content is deep enough.

**Comment by ibishal** [comment]
can i try this @tusharmath ?

**Comment by tusharmath** [comment]
@ibishal 
This would be a little difficult for someone who has never contributed to tailcall. Feel free to send a draft though.

**Comment by ibishal** [comment]
ok i will make a draft PR for this
