### ISSUE TITLE
Support HTTP2 without SSL

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#812]
Currently, tailcall's HTTP2 server only works with SSL. We wish to change this so that HTTP2 can work without SSL. As per the HTTP2 specification, SSL isn't required for HTTP2 to work.

**Comment by Rutik7066** [comment]
Hi @tusharmath i don't have any issue assigned to me i would like work in this so could you please assign this to me.

**Comment by AliYar-Khan** [comment]
@tusharmath I will like to work on this.

**Comment by tusharmath** [comment]
For internal ie. Within the VPC where we do service to service communication SSL is not used typically. Http2 can improve performance in such cases.
