### ISSUE TITLE
chore: Enforce PR Naming Convention Check

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#814]
#### Description
Implement a case-sensitive check to enforce the PR naming convention `<type>(<optional scope>): <title>`. PRs not following this format should automatically fail.

#### Requirements
- Create a GitHub Action or CI/CD script to validate PR titles.
- PR titles must follow the format: `<type>(<optional scope>): <title>`.
- Fail the PR check if the title doesn't match the format.
- Provide clear error messages for non-compliant PR titles.

#### Title Components

**Type:** The <type> part of the PR title refers to the kind of change that is being proposed. Common types include **feat** (new feature), **fix** (bug fix), **docs** (documentation changes), **style** (code style changes), **refactor** (code refactoring), **test** (adding or updating tests), and **chore** (maintenance and tooling changes).

**Scope:** The <scope> part provides a more specific context of the PR. It could refer to a particular module, component, or aspect of the project. The scope helps to categorize the PRs and gives a quick hint about which part of the project is affected.

**Title:** The <title> is a concise description of the changes made. It should be clear and descriptive enough to give an overview of the PR's content without needing to dive into the details.

**Comment by guptadeepak8** [comment]
@tusharmath can i assigned for this

**Comment by ssddOnTop** [comment]
oh this was already assigned.. sorry my bad

@guptadeepak8 if you want me to close pr, lmk

**Comment by ssddOnTop** [comment]
I accidentally mentioned this PR.. how to cancel bounty for this

**Comment by jkcs** [comment]
Might I be assigned this?
