### ISSUE TITLE
redo github labels

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#816]
The github labels are quite a mess right now. Here is a proposed way to standardize them. 

<img width="1241" alt="Screenshot 2023-12-30 at 4 01 00 PM" src="https://github.com/tailcallhq/tailcall/assets/194482/51be95df-7727-4653-9201-45bcf901e25d">

We need a better way to manage and version control it. We can use the **github-label-sync** module for this purpose (feel free to use something else if appropriate). 

**Expectation**
Create a label configuration and a CI integration to apply the label configuration. 

**Additional Information**

[GitHub Labels that are logical, colorful and sensible](https://seantrane.com/posts/logical-colorful-github-labels-18230/)

[Sane Github Labels](https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63)

[Label Configuration](https://github.com/Financial-Times/github-label-sync?tab=readme-ov-file#label-config-file)

**Comment by ologbonowiwi** [comment]
Let me give my 5 cents here: We could also have labels on which part of the project the issue refers to (e.g., blueprint, config, etc.).

**Comment by Min2who** [comment]
@ologbonowiwi we can use git-labelmaker right?

**Comment by tusharmath** [comment]
@ologbonowiwi That should be conveyed via the PR title. `feat(blueprint): add my awesome feature`

**Comment by Min2who** [comment]
@tusharmath may i give a try

**Comment by alankritdabral** [comment]
@tusharmath @Min2who 
i  also want to give a shot lets keep it open for all

**Comment by Min2who** [comment]
@alankritdabral let this issue be assigned to someone
