### ISSUE TITLE
Rust TLS version upgrade

### ISSUE THREAD

**Issue by Lo236816** [tailcallhq/tailcall#827]
>@tusharmath there are some breaking changes in the latest version of `rustls` which I was able to fix but latest version of `hyper-rustls` still depends on the old version of `rustls`. I checked the git repo of `hyper-rustls`, they have already made the changes according to `rustls 0.22.0` in their `main` branch but it is not published on crates.io. Directly putting the repo url in `Cargo.toml` fixes the issue but I don't know if we should do that or wait until latest changes are published for `hyper-rustls`>ASK FOR PERMISSION TO AUTHOR$<

_Originally posted by @shashitnak in https://github.com/tailcallhq/tailcall/issues/712#issuecomment-1845325514_
            —%%%%NO CHANGES%%%%—

**Comment by tusharmath** [comment]
@Lo236816 updated the issue title and description to make it more readable.

**Comment by tusharmath** [comment]
Hopefully this gets some attention — https://github.com/rustls/hyper-rustls/issues/247
