### ISSUE TITLE
Integrate Grammarly on Docs

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#830]
Make sure the CI breaks if the docs have any grammatical mistakes. Use https://www.grammarly.com/ for this purpose.

**Technical Requirements:**
- Run it once over all the current md files in the `/docs` folder.
- Job should run only if there is a change in an `md file.

**Comment by rishi-raj-jain** [comment]
Thanks! On it now!

**Comment by rishi-raj-jain** [comment]
@amitksingh1490 @tusharmath 

Is there a CLI or JS module for Grammarly? I'm currently unable to find the official API/Docs for the same.

I do see SDK's but they require it to be opened in a web browser.

**Comment by tusharmath** [comment]
@rishi-raj-jain that's for you to figure out 🤭

**Comment by Min2who** [comment]
@rishi-raj-jain check this (grammarly-api)[https://github.com/stewartmcgown/grammarly-api#unofficial-grammarly-api-client]

**Comment by rishi-raj-jain** [comment]
I pass it to @neo773 😂

**Comment by rishi-raj-jain** [comment]
> @rishi-raj-jain check this https://github.com/stewartmcgown/grammarly-api#unofficial-grammarly-api-client

That's unmaintained...

**Comment by rishi-raj-jain** [comment]
> @rishi-raj-jain check this https://github.com/stewartmcgown/grammarly-api#unofficial-grammarly-api-client

there's always risk to proxies...

**Comment by neo773** [comment]
Doesn't looks like Grammarly offers an API and that package seems to be internal API which is probably against their TOS.
We could use OpenAI's Function calling for this, would be perfect.
@Min2who you wanna attempt this?

**Comment by rishi-raj-jain** [comment]
I'm happy to attempt if we're deviating from Grammarly. The reason I passed it is only for using Grammarly which I wasn't able to.

**Comment by ezhil56x** [comment]
How about using [proofread-prs](https://github.com/marketplace/actions/proofread-prs) which uses [LanguageTool's API](https://languagetool.org/). If we are planning to use this instead of Grammarly I'm up to work on this 🤚🏻

**Comment by Min2who** [comment]
Grammarly does not provide any api , If @tusharmath yu would like to add openAI API up for it

**Comment by tusharmath** [comment]
@Min2who Sure! Let's try and see if it's any good.

**Comment by ologbonowiwi** [comment]
I'd like to work on it :smile:

**Comment by Min2who** [comment]
@tusharmath can we use [text-gears](https://textgears.com/api) for this
