### ISSUE TITLE
Improve cargo build time in debug mode

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#831]
The debug build time for tailcall is fairly high. This issue targets improving the clean build time for the project by 70%.

**Comment by neo773** [comment]
@tusharmath 
Seems like the conversation got lost in Discord reposting it here
<img width="768" alt="image" src="https://github.com/tailcallhq/tailcall/assets/62795688/f5f30677-01a4-47a7-a532-80a546d13114">

**Comment by tusharmath** [comment]
Fantastic, raise a PR ill have a look

**Comment by neo773** [comment]
@ologbonowiwi 
Nope

**Comment by tusharmath** [comment]
@neo773 did you make any progress on this? I remember you posted something on discord, but didn't create PR.

**Comment by neo773** [comment]
@tusharmath 
Yes, the approach required upfront tooling installed (sccache) you can’t put it in cargo.toml as it requires exposing the path along with some variables and also takes a while to install.

**Comment by avdb13** [comment]
> @tusharmath Yes, the approach required upfront tooling installed (sccache) you can’t put it in cargo.toml as it requires exposing the path along with some of other variables and also takes a while to install.

Does this render the solution ineffective? There is no mention of whether the build times in question are in CI or local debug builds, quite a difference between the two.

**Comment by ologbonowiwi** [comment]
> There is no mention of whether the build times in question are in CI or local debug builds

As the issue's description mentions
> **The debug build** time for tailcall is fairly high. This issue targets improving **the clean build** time for the project by 70%.

From our understanding so far the issue was aiming to solve local builds, but I hit the same wall as @neo773, most solutions found to improve build time require some sort of cache in a build that was done before, which require tooling to be installed on the contributor's machine. 

If such solution is the expected, I'll be happy to open a PR; I have some code locally already
