### ISSUE TITLE
feat: add support for `@expr`

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#839]
Tailcall needs to perform logical operations while composing APIs. Currently, this isn't possible with `@http` and `@grpc`. Logical operations include performing conditionals, setting default values, handling errors etc. We will create a new operator called `@expr` which will do this for us.

**Proposal**

```graphql
schema @upstream(baseURL: "https://jsonplaceholder.typicode.com") {
  query: Query
}

type Query {
  users: [User] @expr(body: {http: {path: "/users"}})
}
```
Here `expr` just provides operators to be embedded directly in the body. In the above case we are inserting an `http` into the expr.`Expr` basically allows the composing of other operators that already exist to resolve data. The above example is morally equivalent to using `@http` directly:

```graphql
type Query {
  users: [User] @http(path: "/users")
}
```

Here is how the `config.rs` would look like
```rust
enum Expr {
  Http(Http), // reuse existing Http operator
  Grpc(Grpc), // reuse existing Grpc operator
  Const(Const), // reuse existing Const operator
}
```

Config to Blueprint should also be updated such that `config::Expr` and be converted into `Expression`.

**Future Work**

This will allow us to define more operators in the future such as conditional operators. eg:

```graphql
type User {
  name: String
  age: Int
  id: Int
  canVote: Boolean
    @expr(
      body: {
        if: {
          cond: { eq: [{ var: "args.age" }, 18] }
          then: { const: true }
          else: { const: false }
        }
      }
    )
}
```

This is how the updated version of `Expr` would look like:

```rust
enum Expr {
  Http(Http),
  Grpc(Grpc),
  Const(Const),
  If { cond: Box<Expr>, then: Box<Expr>, else, Box<Expr> },
  Eq(Box<Expr>, Box<Expr>),  
}
```

This could potentially open up a large number of possible use cases and freedom to define very powerful operators.

**Comment by mayant15** [comment]
I've tried to draft up an implementation for this in #843 

How about having syntax that's something like this?
```
type User {
  id: Int
  name: String
  age: Int
  canVote: Boolean {
    if (args.age >= 18) { @const(true) } else { @const(false) }
  }
  canDrive: Boolean {
    if (@https(path: "/age/{{ args.id }}").age >= 18) { @const(true) } else { @const(false) }
  }
}
```
Have existing operators accessible with the same syntax (looks like [Zig's builtins](https://ziglang.org/documentation/master/#Builtin-Functions)), but an `{}` after the type implicitly becomes an expression.

**Comment by tusharmath** [comment]
@mayant15 I saw the PR, thanks!
Unfortunately, we need to stay within the boundaries of what GraphQL syntax supports today. For something like above to work, we will need to write our own parser for GraphQL.
