### ISSUE TITLE
Create a `@call` operator 

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#846]
The `@call` operator will allow our users to call the resolver by name that is specified in the root Query and Mutation. Here is an example of how it would work.

```graphql
schema {
  query: Query
}

type Query {
  posts: [Post] @http(path: "/path")
  user(id: Int): User @http(path: "/user/{{args.id}}")
}

type Post {
  id: Int
  title: String
  userId: Int
  user: User @call(query: "user", args: {id: "{{value.userId}}"})
}
```

The `@call` will simply call the resolver that's set in `Query.user` field with the arguments specified via `args`.

This feature gives us the ability to define functions using the Tailcall DSL, which means we can add some form of reusability and modularity.

**Technical Requirements**
- The function can only be called if the input and output type match exactly. In the above example  `Query::user` returns a `User` and `Post::user` also returns a `User` so it's compatible with its return type. Similarly, we can see that the args are also exactly the same.

**Comment by Rutik7066** [comment]
hey @tusharmath . Previously assigned work is done now I am waiting for your confirmation to start working on this one.

**Comment by ologbonowiwi** [comment]
/attempt #846
Putting myself on the queue 🤚🏽

**Comment by tusharmath** [comment]
@Khalid6468 All the best! Looking forward to your PR.

**Comment by meskill** [comment]
@Khalid6468 could you please share your status on this?

If it's not much it's might be better to reassign to @ologbonowiwi that made some progress on this

**Comment by Khalid6468** [comment]
@meskill I haven't made much progress on this one so far and its taking some time to understand the codebase and get familiar. I went through different operator implementations and just started working on the implementation for this one. You can reassign it as it might take a day or two more for me to complete this and it would just be duplication of effort.

**Comment by ologbonowiwi** [comment]
Up. We started to review/make some changes again yesterday.
