### ISSUE TITLE
Write a guide for using environment variables

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#852]
Write a guide about environment variables in tailcall. Cover aspects such as -
- Why is it needed?
- Where can one use it?
- Security aspects of using env variables.
- Some best practices

Make sure the guide is free-flowing and engaging. 

**PS: DON'T CREATE LOW-EFFORT CHATGPT GENERATED CONTENT!**

**Comment by rajdip-b** [comment]
Hey can i try this?

**Comment by Amanullah1002** [comment]
Please assign this to me . 
/attempt #852

**Comment by rajdip-b** [comment]
@tusharmath hey, should I take the discussion to Discord or do it in here?

**Comment by tusharmath** [comment]
Discord is preferred.
