### ISSUE TITLE
Write a guide on mustache templates

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#856]
Tailcall allows the use of mustache templates in various places of the configuration. Write a guide about the power it gives to the developers and it's limitations.

**Requirements**
- Explain what it does and why do we need it.
- List down all the places where mustache templates can be used.
- Link to `context.md` in the document for further reading.
- Back link to `mustache.md` in the `context.md`.
- Make no grammatical or spelling errors.
- Keep the guide tone neutral, non non-emotional.
- Keep the writing style free-flowing and engaging.
- Fact-check everything, connect on Discord if you are confused.
- Make the writing cohesive, to the point, and related to the title.

**PS: DON'T CREATE LOW-EFFORT CHATGPT GENERATED CONTENT!**

**Comment by ibishal** [comment]
can i work on it?

**Comment by Rutik7066** [comment]
Can get assigned for this one

**Comment by rajdip-b** [comment]
would like to be on the queue since this is kind of related to #852

**Comment by tusharmath** [comment]
Closing this in favour of https://github.com/tailcallhq/tailcallhq.github.io/issues/117
