### ISSUE TITLE
fix auto labelling of pull requests

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#857]
We have a `autolabler` setting in `release_drafter.yml` which should automatically apply labels to pull requests but it doesn't happen.

Identify the issue of why it doesn't automatically add labels based on the title of the PR or branch name and fix it.

**Comment by Min2who** [comment]
can i work on it?

**Comment by melsonic** [comment]
Can i work on this one?

**Comment by ayewo** [comment]
Man, in just 10 minutes and issue is already assigned …

**Comment by melsonic** [comment]
@alankritdabral dude I was working on this one

**Comment by janvi01** [comment]
can I work on this if it's available? @tusharmath

**Comment by amitksingh1490** [comment]
Fixed
