### ISSUE TITLE
Read environmental variables from `.env` files

### ISSUE THREAD

**Issue by rajdip-b** [tailcallhq/tailcall#859]
**Is your feature request related to a problem? Please describe.**
Most of the time we have a `.env` file in our directory that contains all the secret. Right now, there is no way to directly use this file to resolve the env keys in the mustache statement.

**Describe the solution you'd like**
It would be nice to automatically detect and parse all environment variables in our mustache templates, rather than having to explicitely specifying them in our runtime environment.

Usage: 
If we have a `.env` file with the following content in it,
```
API_ENDPOINT=myapi.com
```

Then, this block should work by default.

```graphql showLineNumbers
type Query {
  users: [User]! @http(baseUrl: "{{env.API_ENDPOINT}}", path: "/users")
}
```

**Comment by ologbonowiwi** [comment]
Agree. I suggested it when working on #790, but it was outside that issue's scope.

**Comment by ksh0205** [comment]
Hi @tusharmath, Can I give it a shot? Can you assign the issue to me.

**Comment by ologbonowiwi** [comment]
I'd like to work on this one as I implemented part of the env thing already

**Comment by ologbonowiwi** [comment]
I started working on it, and I'll use `env-file-reader` to read the env.

one question: Do we want a new operator or a new field on an existing operator?

IMO, we could add an `env_file`, `env_path`, or something like that on the `@server` operator or create an `@env` operator.

e.g.:
```graphql
# new field on server operator
@server(env_path: ".env.something")

# OR

# new env operator
@env(path: ".env.something")
```

what do you think @tusharmath?

**Comment by ologbonowiwi** [comment]
As discussed [on Discord](https://discord.com/channels/1044859667798568962/1156188728474214472/1191854194051776532), we'll use `@link` for that, so we're blocked until #886 be resolved.

**Comment by Bhavyajain21** [comment]
is this closed? I still this issue as open in algora

**Comment by ologbonowiwi** [comment]
It's really open @Bhavyajain21. I'm assigned to this one but feel free to give it a shot if you want to

**Comment by tusharmath** [comment]
fixed in https://github.com/tailcallhq/tailcall/pull/1523
