### ISSUE TITLE
Write a guide to build a GraphQL endpoint over REST

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#872]
Write a guide to use REST APIs. Make sure it covers the feature in depth. Emphasize on how easy it is to use Tailcall to build a GraphQL API on top of REST. Take an interesting use case other than the jsonplaceholder example that's used everywhere.

**Requirements**
- Make no grammatical or spelling errors.
- Keep the guide tone neutral, non non-emotional.
- Keep the writing style free-flowing and engaging.
- Fact-check everything, connect on Discord if you are confused.
- Make the writing cohesive, to the point, and related to the title.

**PS: DON'T CREATE LOW-EFFORT CHATGPT GENERATED CONTENT!**

**Comment by rajdip-b** [comment]
can i give this a shot?

**Comment by pi600** [comment]
can i work on it?

**Comment by janvi01** [comment]
Hey @tusharmath I would like to work on it if it's available

**Comment by tusharmath** [comment]
@janvi01 you can try this — https://github.com/tailcallhq/tailcall/issues/875

**Comment by nxshanth13** [comment]
@tusharmath. i think i can try it.

**Comment by FaizanShaikh-3033** [comment]
Please assign it to me, i can do it.

**Comment by oliverqx** [comment]
@tusharmath can I work on this?

**Comment by tusharmath** [comment]
Sure. Go ahead.

**Comment by rajdip-b** [comment]
Hey @tusharmath, I have ready raised a PR for this for quite a long time now - https://github.com/tailcallhq/tailcallhq.github.io/pull/87/files

**Comment by guptadeepak8** [comment]
hey @tusharmath is this open pls assign it to me
