### ISSUE TITLE
Write a guide to setup tailcall on AWS serverless

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#873]
Write an engaging guide to deploy tailcall on AWS serverless. Leverage AWS features to manage tailcall configuration and server deployment and configuration.

**Requirements**
- Make no grammatical or spelling errors.
- Keep the guide tone neutral, non non-emotional.
- Keep the writing style free-flowing and engaging.
- Fact-check everything, connect on Discord if you are confused.
- Make the writing cohesive, to the point, and related to the title.

**PS: DON'T CREATE LOW-EFFORT CHATGPT GENERATED CONTENT!**

**Comment by ibishal** [comment]
@tusharmath can i work on that

**Comment by tusharmath** [comment]
@ibishal Please do some research on this first. I think it might require some work on our end before.

**Comment by ibishal** [comment]
ok @tusharmath
