### ISSUE TITLE
Support serverless via AWS Lambda

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#874]
AWS has support to run Rust binaries on serverless.

**Technical Requirements**
- Reuse code as much as possible.
- Create a separate binary for AWS serverless
- Update CI jobs to create AWS Lambda binaries.

**Additional Links**
https://github.com/aws-samples/serverless-rust-demo/

**Comment by ezhil56x** [comment]
@tusharmath I have some experience with AWS and I'm a AWS Certified Cloud Practitioner. Happy to take up this!

**Comment by tusharmath** [comment]
Great!

**Comment by ayewo** [comment]
@tusharmath I’m on standy 🙃 just in case.

**Comment by atharv4git** [comment]
I currently work as a backend developer intern at a company which uses AWS lambda in their CI/CD, would be happy to work on this project if the issue remains 😊

**Comment by ezhil56x** [comment]
@ayewo 
I couldn't make up. Feel free to take up this 🤗

Found some resources that would help
[https://docs.aws.amazon.com/lambda/latest/dg/lambda-rust.html](https://docs.aws.amazon.com/lambda/latest/dg/lambda-rust.html)
[https://www.cargo-lambda.info/](https://www.cargo-lambda.info/)

**Comment by ayewo** [comment]
Thanks for the heads up @ezhil56x 👍.

**Comment by ayewo** [comment]
@tusharmath 

Specifically, what commands from the `tailcall` binary do you want to expose using AWS Lambda?

**Comment by atharv4git** [comment]
@tusharmath okay thanks for the information

**Comment by ayewo** [comment]
> Specifically, what commands from the `tailcall` binary do you want to expose using AWS Lambda?

@tusharmath would appreciate a response here.

**Comment by tusharmath** [comment]
On AWS we don't care about the commands. Tailcall should load a configuration over HTTP and start a serverless implementation immediately.

**Comment by ayewo** [comment]
@tusharmath an AWS Lambda function doesn’t load configuration over HTTP, it can only handle inbound HTTP requests. 

Any relevant configuration has to be baked into the runtime—the machine image used to start up the Lambda function.

So it sounds like you want to Tailcall to act as if it were a Lambda function that can handle *arbitrary* GraphQL calls? 

I’m afraid Lambda functions weren’t made for that since JSON is what is used for most payloads.
