### ISSUE TITLE
Write a guide about entity level caching in graphql

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#875]
Write a guide about entity level caching using Tailcall.

**Requirements**
- Make no grammatical or spelling errors.
- Keep the guide tone neutral, non non-emotional.
- Keep the writing style free-flowing and engaging.
- Fact-check everything, connect on Discord if you are confused.
- Make the writing cohesive, to the point, and related to the title.

**PS: DON'T CREATE LOW-EFFORT CHATGPT GENERATED CONTENT!**

**Additional Information**
- https://www.youtube.com/watch?v=iMJmsAzjA9A&t=173s
- https://www.youtube.com/watch?v=CV3puKM_G14

**Comment by pi600** [comment]
can i give it a try?

**Comment by ibishal** [comment]
@tusharmath could you assign me this?

**Comment by janvi01** [comment]
hey @tusharmath I would like to work on this.

**Comment by ibishal** [comment]
can i attempt this @tusharmath

**Comment by ishqDehlvi** [comment]
@tusharmath Can you please assign this task to me??

**Comment by tusharmath** [comment]
@ishqDehlvi go ahead.

**Comment by ishqDehlvi** [comment]
@tusharmath I have created an overall sketch 
`
Introduction
Understanding Entity-Level Caching
Tailcall's @cache Operator and entity level caching
Usage Examples
Best Practices
Integration with GraphQL Schema
Handling Cache Expiry and Refresh
Common Pitfalls and Solutions
Conclusion
`
Is it good for the guide??

**Comment by xonx4l** [comment]
Made a Pr -: https://github.com/tailcallhq/tailcallhq.github.io/pull/132#issue-2171107535
