### ISSUE TITLE
Support for `application/x-www-form-urlencoded` in `@http`

### ISSUE THREAD

**Issue by rajdip-b** [tailcallhq/tailcall#887]
**Is your feature request related to a problem? Please describe.**
Currently, the default action of the `@http` directive is to treat the request body as a JSON object. While this works with most APIs, some APIs do expect `application/x-www-form-urlencoded`. 

P.S. specifying `Content-Type: application/x-www-form-urlencoded` in the `@http` headers doesn't work

**Describe the solution you'd like**
It would be really nice to have a feature where the request body gets treated based upon the content-type header. The default option is to go for `application/json`. But if specified otherwise, we should encode in `application/x-www-form-urlencoded`

**Comment by tusharmath** [comment]
**Proposed Solution**
Update the `@http` directive to support multiple types of content encoding.

```graphql
enum Encoding {
  # Default Encoding
  APPLICATION_JSON

  # New Encoding
  APPLICATION_X_WWW_FORM_URLENCODED

  # Future Encoding
  TEXT_HTML
  APPLICATION_XML
  TEXT_PLAIN
  IMAGE_JPEG
  IMAGE_PNG
  APPLICATION_PDF
  MULTIPART_FORM_DATA
}
directive @http(
  path: String!
  method: Method = GET
  query: [KeyValue]
  body: String
  baseURL: String
  headers: [KeyValue]
  groupBy: [String!]
  # A new optional field
  encoding: Encoding
) on FIELD_DEFINITION
```

Based on the `encoding`, the HTTP client should if the request body needs to be sent as an `application/json` which should be the default or something else as specified in the `@http` directive.

**Comment by rajdip-b** [comment]
can i work on this?
