### ISSUE TITLE
feat: generate json schema for YAML and JSON configurations

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#890]
**Problem**
IntelliSense works in VS code only on the `.graphql` files because of `.tailcallrc.graphql`. We propose generating a JSON-schema file so that YML and JSON also get a great developer experience. 

**Proposal**
Autogenerate the json schema file which is equivalent to `.tailcallrc.graphql`.

**Technical**
- Use the macro API to derive the auto-completions
- Lint existing YML and JSON configurations in the project using the JSON Schema
- Document how to use the IntelliSense features in VSCode and other IDEs.

**Additional Links:**
- https://dev.to/brpaz/how-to-create-your-own-auto-completion-for-json-and-yaml-files-on-vs-code-with-the-help-of-json-schema-k1i
- https://json-schema.org/
- https://www.schemastore.org/json/

**Comment by ssddOnTop** [comment]
can you assign this to me
