### ISSUE TITLE
refactor: auto-generate `.tailcallrc.graphql`

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#895]
Its slowly becoming difficult to manage `.tailcallrc.graphql`. With each PR we need to update the file manually.

**Proposal**
Use the macro API and hints on the Config type to generate a `.tailcallrc.graphql`

**Technical Requirements**
- Make sure the documentation is picked up from the struct/enums defined.
- Ensure it semantically matches the current version of the file.

**Comment by rajdip-b** [comment]
@tusharmath can i try this?

**Comment by Asmi1143** [comment]
i wanna try

**Comment by Gua00va** [comment]
I want to work on this issue. Can you assign it to me. Thanks in advance!!

**Comment by ssddOnTop** [comment]
@rajdip-b did you make any progress on this? Actually I am working on #890 and this is very similar to that, I think we can directly merge both the issues, so if you have not made any progress, I'd like to take over this issue

**Comment by rajdip-b** [comment]
Hey @ssddOnTop, I'm working in #896 right now and will be taking up another issue after that. So yeah, feel free to take this up!

**Comment by tusharmath** [comment]
Apparently no PR was received, let me know if anyone is interested in doing this?

**Comment by ssddOnTop** [comment]
@tusharmath did some work on 896 and this is almost same.. will move to this after current task

**Comment by ssddOnTop** [comment]
I won't be able to work on this issue, @rajdip-b you may continue

**Comment by rajdip-b** [comment]
@ssddOnTop sure thing!

**Comment by rajdip-b** [comment]
@ssddOnTop @tusharmath hey folks, I checked with the json auto generation PR. Unfortunately, I couldnt find any library that can generate grapgql. So, do you guys have any tool in mind? alternatively, we can transform the json file into graphql if thats possible

**Comment by meskill** [comment]
The issue if solved by https://github.com/tailcallhq/tailcall/pull/1003
