### ISSUE TITLE
Create git hook to run `./lint.sh --mode=fix` on push/commit.

### ISSUE THREAD

**Issue by ologbonowiwi** [tailcallhq/tailcall#912]
**Is your feature request related to a problem? Please describe.**
One frustrating example I can relate is to have a feature fully developed, to push and wait a few mins and when I get back to the PR I see one lint error that could be fixed with `./lint.sh --mode=fix`

**Describe the solution you'd like**
A git hook that runs `./lint.sh --mode=fix` without me needing to run it manually

**Describe alternatives you've considered**
Run manually is the only alternative I guess

**Additional context**
Before we can jump into the code, we need to discuss
- [ ] which tool we'll use to make it happen? I'd avoid node/javascript tools as they're pretty slow.
- [ ] in which hooks we'll run the lint script?

**Comment by tusharmath** [comment]
You can add it to your git anyways.

**Comment by ologbonowiwi** [comment]
should I handle it on my workspace rather than adding it to the project itself then?

**Comment by neo773** [comment]
In my opinion a git hook would be better, in most PRs people usually forget running the lint command, there's added friction in waiting and finding out CI failed then heading back to your IDE and typing out the command and pushing.

Once cached subsequents lint runs only cost a few hundred miliseconds anyway if you're making a lot of commits.

**Comment by tusharmath** [comment]
What about integrating the linter with your IDE, such that every time you save the file autoformatted?

**Comment by ologbonowiwi** [comment]
Integrating prettier worked pretty well; still, I noticed some conflicts still, e.g., files without blank line between function/struct declaration not being saved correctly, which resulted in errors when running `./lint.sh --mode=check`.

The major drawback I can think of is that we have `cargo +nightly clippy --all-targets --all-features` on `./lint.sh` this would slow down the commits, and it'd lead to a poor DX.

The optimal option (and my personal suggestion) is: avoid running `run_cargo_clippy` when `./lint.sh --mode=fix` is invoked from the pre-commit hook. In this way, we'd improve the performance of `./lint.sh`, as the app build would be bypassed.
Let me know your thoughts and I can update the issue if needed.
