### ISSUE TITLE
data: add support to track google analytics

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#917]
Add support to track tailcall usage using Google Analytics

**Technical Requirements**
- Send events for each command that's executed via the CLI
- All calls should be fired and forgotten.
- Should only be activated on release builds.

**Comment by Akshay-Patel-dev** [comment]
Can I work on this

**Comment by ologbonowiwi** [comment]
Putting myself on the queue 🤚🏽

did you thought about which Google analytics library to use @tusharmath?

I found two in case it helps @Akshay-Patel-dev:
- https://docs.rs/google-analytics3/latest/google_analytics3/
- https://docs.rs/google-analyticsreporting4/latest/google_analyticsreporting4/

**Comment by Akshay-Patel-dev** [comment]
Hey @ologbonowiwi , you can take this up.

**Comment by mogery** [comment]
I'd be up for this! What exactly should be in the events that are reported to GA?

**Comment by lazyfuhrer** [comment]
I'm working on this. Can you assign it to me ? @tusharmath
