### ISSUE TITLE
Batching breaks if we provide multiple files

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcall#922]
### Prerequisites

- [X] I have checked the existing issues to ensure this is not a duplicate.
- [X] I am running the latest version of Tailcall.

### Describe the bug
When I provide two files one with upstream directive and one without. The batching stops working, However it works with just one file.
File 1 
```graphql
# posts.graphql
schema 
  @server(graphiql: true, vars: [{key: "1", value: "Cricket"}])
  @upstream(baseURL: "https://jsonplaceholder.typicode.com", batch: {delay: 1000}) {
  query: Query
}

type Query {
  posts: [Post] @http(baseURL: "https://jsonplaceholder.typicode.com", path: "/posts")
}

type Post {
  userId: ID!
  id: ID
  title: String
  body: String @modify(name: "description")
  user: User @http(baseURL: "https://jsonplaceholder.typicode.com", path: "/users", query: [{key: "id", value: "{{value.userId}}"}], groupBy: ["id"])
}
```
File 2
```graphql
# users.graphql
type User @addField(name: "street", path: ["address", "street"]) {
  id: ID
  name: String
  username: String
  address: Address @modify(omit: true)

}

type Address {
  street: String
}
```
### Steps to reproduce

1. tailcall start ./posts.graphql ./users.graphql
2. Make multiple requests with this query
```graphql
{
  posts {
    title
  }
}
```

### Expected behavior
It should make one request upstream to `/posts` within the provided delay

### Actual behavior

It is making multiple calls

### Additional context

This seems to be a bug in merge right is overiding the upstream config

## Technical Requirements
This part of the application doesn't have test. Make sure we add some.

**Comment by Kartik1397** [comment]
@amitksingh1490 Any particular reason why we only merging headers in case of multiple batch objects instead of just using `or` function?

https://github.com/tailcallhq/tailcall/blob/632812042abd30d55c93d694737949cb5c88d953/src/config/server.rs#L256-L262

There's also a test case for this.
https://github.com/tailcallhq/tailcall/blob/main/tests/graphql/merge/test-merge-batch.graphql
