### ISSUE TITLE
performance: improve performance of `RequestTemplate`

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#934]
The `set_body` method can be optimized for the case of `ApplicationXWwwFormUrlencoded`.
Currently, it renders the mustache template as a string, then converts it to serde_json and then again converts it to a form_url_encoded value.

Ideally, there it shouldn't take such redundant steps to make this transformation.

**Technical Requirements**
- Write idiomatic rust code while making an optimization
- Write criterion benchmarks to compare the before and after performance.

**Comment by SOUMOJIT-CHAKRABORTY** [comment]
Hi! @tusharmath I want to work on the issue, can you assign it to me.

**Comment by guhitb** [comment]
@tusharmath Can I be assigned to this?

**Comment by tusharmath** [comment]
Sure go ahead

**Comment by ologbonowiwi** [comment]
Hey @guhitb, can I take up from where you stopped on #1084?
