### ISSUE TITLE
chore: auto-release every commit

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#939]
We want to move away from discussing _"when should we make our next release?"_ 
Ideally, we would like to make a release with every commit on the main. We now have a great set of tests that we can rely on and it's time we consider continuous deployment. The other advantage of doing this would be that our documentation will be in sync with our code.

**Proposal**
- Publish every commit that is made on `main`.
- Don't release unless it's a `fix` or a `feature`.
- If it's a `fix` resolve with a patch upgrade.
- If it's a `feature` resolve with a minor upgrade.
- Major version, will not be touched until version 1 is released.

**Comment by ezhil56x** [comment]
/attempt #939

@tusharmath Can I get this assigned? Almost done with this
