### ISSUE TITLE
 Tailcall  does not seem to support configuring the cache size or max age for its built-in HTTP cache. 

### ISSUE THREAD

**Issue by xonx4l** [tailcallhq/tailcall#956]
**Is your feature request related to a problem? Please describe.**
Tailcall  does not seem to support configuring the cache size or max age for its built-in HTTP cache. 

Example -:
                httpCache:
   
                         maxSize: 1000

                         maxAge: 3600

                 
maxSize is the max number of responses to cache. Default is 1000.
maxAge is the max age in seconds to cache responses. Default is 3600 seconds (1 hour).

**Comment by tusharmath** [comment]
**Current**
```graphql
schema @upstream(httpCache: Boolean) {}
```

**Proposed**
```graphql
schema @upstream(cache: {http: {maxSize: Int}, entity: {maxSize: Int}}) {

}

type User @cache(maxAge: Int) {
  name: String
}
```
