### ISSUE TITLE
Move the expr integration tests to unit test and add tests for expr to cover all scenarios

### ISSUE THREAD

**Issue by shashitnak** [tailcallhq/tailcall#968]
**Description**

Move all the tests with prefix `test-expr-*` present in `tests/http` to `src/blueprint/from_config/operators/expr.rs` as unit tests and add more tests for `expr` to cover all the scenarios.

**Comment by guptadeepak8** [comment]
Can i get assigned?

**Comment by rajdip-b** [comment]
@tusharmath may I be assigned?
