### ISSUE TITLE
creating a query with nullable type throws a runtime error

### ISSUE THREAD

**Issue by shashitnak** [tailcallhq/tailcall#971]
### Prerequisites

- [x] I have checked the existing issues to ensure this is not a duplicate.
- [x] I am running the latest version of Tailcall.

### Describe the bug

Creating a query with a nullable type as the argument, throws a runtime error when the argument is used in the resolver instead of providing the correct error message. For example

```
type Query {
  user(id: Int): User @http(path: "/users/{{args.id}}")
}
```

### Steps to reproduce

1. create a `.graphql` config with the query provided above or a similar query
2. start the tailcall server with the config

### Expected behavior

The application should fail with an error message describing the problem with the config.

### Actual behavior

The application crashes with tokio runtime error

### Screenshots

<img width="1052" alt="image" src="https://github.com/tailcallhq/tailcall/assets/27275148/e89af2ad-4ea0-4724-a140-f9ca91f600ba">

### Environment information:

- **Operating System**: macOS
- **Tailcall Version**: v0.20.2
- **Rust Version**: `rustc 1.75.0`

**Comment by amitksingh1490** [comment]
fixed in #978
